DROP TABLE COUNTINGALLOCATION2HAPHI;
DROP TABLE COUNTINGALLOCATION3HAPHI;
DROP TABLE COUNTINGRESERVES2HAPHI;
DROP TABLE POLLINGALLOCATION2ORIGINAL;
DROP TABLE CREDITED;
DROP TABLE EKHRESERVES;

DROP TABLE logs.exemptedpersonnel_2024_03_08;
DROP TABLE logs.OFFICES_2024_03_08;
DROP TABLE logs.personnel_2024_03_08;
DROP TABLE MASTERS.ACPARTS2023;


DELETE FROM COUNTINGRESERVES;
DELETE FROM COUNTINGALLOCATION3;
DELETE FROM COUNTINGALLOCATION2;
DELETE FROM COUNTINGALLOCATION1;

DELETE FROM COUNTINGHALLSACS;
DELETE FROM COUNTINGTABLES;
DELETE FROM COUNTINGHALLS;
DELETE FROM COUNTINGVENUES;
DELETE FROM EXEMPTEDPERSONNEL;
DELETE FROM OTHERPERSONNEL;
DROP TABLE personnel20240419;
DROP TABLE personnel20240517;

DELETE FROM PERSONNELAPPOINTMENT;
DELETE FROM PERSONNELAPPOINTMENTLETTERS;
DELETE FROM POLLINGALLOCATION3;
DELETE FROM POLLINGALLOCATION1;
DELETE FROM POLLINGALLOCATION1;
DELETE FROM POLLINGRESERVES;
DELETE FROM TRAININGATTENDANCE;






DELETE FROM TRAININGLETTERNOFORMAT;
DELETE FROM TRAININGPERSONNEL;
DELETE FROM TRAININGSESSIONS;
DELETE FROM TRAININGVENUES;
DELETE FROM TRAININGPHASES;
DELETE FROM VEHICLES;

DELETE FROM MASTERS.MATERIALMOVEMENT;
DELETE FROM MASTERS.SECTOROFFICERS;
DELETE FROM MASTERS.SECTORSPS;
DELETE FROM MASTERS.SECTORS;



DELETE FROM LOGS.OFFICES;
DELETE FROM LOGS.PERSONNEL;
DELETE FROM LOGS.POLLINGALLOCATION2;
DELETE FROM LOGS.PSPARAMETERS;
DELETE FROM LOGS.SECTOROFFICERS;
DELETE FROM LOGS.SECTORS;
DELETE FROM LOGS.SECTORSPS;
DELETE FROM LOGS.TRAININGPERSONNEL;
DELETE FROM LOGS.TRAININGSESSIONS;
DELETE FROM LOGS.TRAININGVENUES;
