--CREATE TABLE PERSONNELDESIGNATION20250221130PM AS SELECT EMPLOYEECODE, PERSONNELCATEGORYCODE FROM PERSONNEL;
--INSERT INTO MASTERS.PERSONNELCATEGORIES VALUES (999, 'UNDEFINED');

--21 - CS, 22 -  CASST, 9 - MO,  23 TABULATOR

--SELECT * FROM MASTERS.PERSONNELCATEGORIES ORDER BY PERSONNELCATEGORYDESCRIPTION;

SELECT EO.OFFICENAME, PERSONNELCATEGORYDESCRIPTION, COUNT(*) FROM 
MASTERS.OFFICES EO INNER JOIN MASTERS.OFFICES O ON EO.OFFICECODE = O.REFERENCEOFFICECODE 
INNER JOIN PERSONNEL P ON O.OFFICECODE = P.OFFICECODE
INNER JOIN MASTERS.PERSONNELCATEGORIES PC ON PC.PERSONNELCATEGORYCODE = P.PERSONNELCATEGORYCODE 
WHERE 1 = 1 
--AND EO.OFFICECODE = '030001' 
AND TRAININGFLAGCODE = 'C'
GROUP BY EO.OFFICENAME,  PERSONNELCATEGORYDESCRIPTION 
ORDER BY EO.OFFICENAME,  PERSONNELCATEGORYDESCRIPTION;





