SELECT * FROM masters.rndcountingcategoriesmap;
SELECT * FROM MASTERS.PERSONNELCATEGORIES ORDER BY PERSONNELCATEGORYDESCRIPTION;

INSERT INTO MASTERS.rndcountingcategoriesmap
SELECT O.OFFICECODE, PC.PERSONNELCATEGORYCODE, 'R', 1, CURRENT_TIMESTAMP FROM MASTERS.OFFICES O , MASTERS.PERSONNELCATEGORIES PC WHERE ISELECTIONOFFICE = 'Y' AND O.ENABLED ='Y'
AND (O.OFFICECODE, PERSONNELCATEGORYCODE) NOT IN (SELECT OFFICECODE, PERSONNELCATEGORYCODE FROM MASTERS.rndcountingcategoriesmap)
AND TRAININGFLAGCODE ='C';

SELECT * FROM MASTERS.PERSONNELCATEGORIES PC ORDER BY PERSONNELCATEGORYDESCRIPTION ;


SELECT O.OFFICECODE, O.OFFICENAME, PC.PERSONNELCATEGORYCODE, PC.PERSONNELCATEGORYDESCRIPTION, M.FLAGCODE
FROM MASTERS.OFFICES O INNER JOIN MASTERS.RNDCOUNTINGCATEGORIESMAP M ON O.OFFICECODE = M.OFFICECODE
INNER JOIN MASTERS.PERSONNELCATEGORIES PC ON PC.PERSONNELCATEGORYCODE = M.PERSONNELCATEGORYCODE
WHERE O.OFFICECODE = '030001'
ORDER BY O.OFFICENAME, PC.PERSONNELCATEGORYDESCRIPTION ;

UPDATE MASTERS.RNDCOUNTINGCATEGORIESMAP  SET FLAGCODE = 'S' WHERE OFFICECODE = '030001' ;

UPDATE MASTERS.RNDCOUNTINGCATEGORIESMAP  SET FLAGCODE = 'R' WHERE OFFICECODE = '030001' AND PERSONNELCATEGORYCODE IN (21,22,9);
UPDATE MASTERS.RNDCOUNTINGCATEGORIESMAP  SET FLAGCODE = 'R' WHERE OFFICECODE = '050001' AND PERSONNELCATEGORYCODE IN (21,22,9);



INSERT INTO MASTERS.COUNTINGMASTERTABLE
SELECT OFFICECODE, NULL, '2024-06-04',  '2024-06-04', '5:00 A.M.', 1, CURRENT_TIMESTAMP FROM MASTERS.OFFICES WHERE ISELECTIONOFFICE = 'Y' AND ENABLED = 'Y'