SELECT DISTRICTNAME, OFFICENAME, D.DISTRICTCODE, OFFICECODE FROM MASTERS.DISTRICTS D INNER JOIN MASTERS.OFFICES O ON D.DISTRICTCODE = O.DISTRICTCODE 
WHERE ISELECTIONOFFICE ='Y'
ORDER BY DISTRICTNAME, OFFICENAME