/*

SELECT COUNT(*) FROM MASTERS.OFFICES O INNER JOIN MASTERS.OFFICESACS OAC ON O.OFFICECODE = OAC.OFFICECODE  INNER JOIN MASTERS.ASSEMBLYCONSTITUENCIES AC ON AC.ACNO = OAC.ACNO
INNER JOIN MASTERS.ACPARTS AP ON AC.ACNO = AP.ACNO INNER JOIN MASTERS.POLLINGSTATIONS PS ON (AP.ACNO = PS.ACNO  AND AP.PARTNO = PS.PARTNO)
WHERE O.OFFICECODE = '030001';


SELECT O.OFFICENAME, VUNITTYPEDESCRIPTION, TRAININGPOLLING, FITFORPOLLING , COUNT(*) FROM 
MASTERS.OFFICES O INNER JOIN EVMS.VOTINGUNITS VU ON O.OFFICECODE = VU.OFFICECODE
INNER JOIN MASTERS.VOTINGUNITTYPES VT ON VT.VUNITTYPECODE = VU.VUNITTYPECODE
GROUP BY O.OFFICENAME, VUNITTYPEDESCRIPTION, TRAININGPOLLING, FITFORPOLLING 
ORDER BY O.OFFICENAME, VUNITTYPEDESCRIPTION, TRAININGPOLLING, FITFORPOLLING DESC;

*/

SELECT O.OFFICENAME, VUNITTYPEDESCRIPTION, TRAININGPOLLING, FITFORPOLLING  FROM 
MASTERS.OFFICES O INNER JOIN EVMS.VOTINGUNITS VU ON O.OFFICECODE = VU.OFFICECODE
INNER JOIN MASTERS.VOTINGUNITTYPES VT ON VT.VUNITTYPECODE = VU.VUNITTYPECODE
INNER JOIN 

ORDER BY O.OFFICENAME, VUNITTYPEDESCRIPTION, TRAININGPOLLING, FITFORPOLLING DESC;





SELECT OFFICECODE, COUNT(*) , COUNT(*) + CEIL((40*COUNT(*))/100) FROM MASTERS.OFFICESACS OAC INNER JOIN MASTERS.ACPARTS AP ON (OAC.ACNO = AP.ACNO)
GROUP BY OFFICECODE
ORDER BY OFFICECODE;


SELECT OFFICECODE, VUNITTYPECODE, COUNT(*) FROM EVMS.EVMALLOCATION1 GROUP BY OFFICECODE, VUNITTYPECODE;
SELECT OFFICECODE, VUNITTYPECODE, COUNT(*) FROM EVMS.EVMALLOCATION2 GROUP BY OFFICECODE, VUNITTYPECODE;


SELECT * FROM 
EVMS.VOTINGUNITS V INNER JOIN 
EVMS.EVMALLOCATION1 E1 ON V.VUNITTYPECODE = E1.VUNITTYPECODE AND V.VOTINGUNITSLNO = E1.VOTINGUNITSLNO
INNER JOIN EVMS.EVMALLOCATION2 E2 
ON (E1.OFFICECODE = E2.OFFICECODE AND E1.VUNITTYPECODE = E2.VUNITTYPECODE AND E1.VOTINGUNITSLNO = E2.VOTINGUNITSLNO);


SELECT E1.ACNO, COUNT(*)/2 FROM EVMS.VOTINGUNITS V INNER JOIN 
EVMS.EVMALLOCATION1 E1 ON V.VUNITTYPECODE = E1.VUNITTYPECODE AND V.VOTINGUNITSLNO = E1.VOTINGUNITSLNO
INNER JOIN EVMS.EVMALLOCATION2 E2 
ON (E1.OFFICECODE = E2.OFFICECODE AND E1.VUNITTYPECODE = E2.VUNITTYPECODE AND E1.VOTINGUNITSLNO = E2.VOTINGUNITSLNO)
GROUP BY E1.ACNO ORDER BY E1.ACNO;




