SELECT M.HEADER1, M.HEADER2, M.HEADER3,D.PCNAME, EO.OFFICENAME AS ELECTIONOFFICE,
EO.SIGNATURE, EO.SIGNATORYNAME, EO.SIGNATORYDESIGNATION, INITCAP(DISTRICTNAME) AS DISTRICTNAME, INITCAP(DISTRICTHQ) AS DISTRICTHQ,
TO_CHAR(POLLDATE, 'dd-Mon-yyyy') AS POLLDATE, POLLSTART, POLLEND,
A1.ACNO, A1.PARTNO, A1.PSNO, AC.ACNO || '-' || ACNAME AS AC, AP.PARTNO || '-' || PARTNAME AS PART,PSNAME AS PSNAME ,
A1.EMPLOYEECODE AS PEMPLOYEECODE, A1.PERSONNELCATEGORYCODE AS PPERSONNELCATEGORYCODE ,UPPER(TRIM(PC1.PERSONNELCATEGORYDESCRIPTION)) AS PPERSONNELCATEGORYDESCRIPTION,
CASE WHEN P1.GENDER='MALE' THEN 'SHRI. ' || UPPER(P1.FULLNAME) WHEN P1.GENDER='FEMALE' THEN 'SMT./KUM. ' || UPPER(P1.FULLNAME) END AS PFULLNAME,
UPPER(TRIM(O1.OFFICENAME)) AS POFFICENAME, UPPER(TRIM(P1.DESIGNATION)) AS PDESIGNATION, P1.MOBILENO AS PMOBILENO, 
A2.PERSONNELCATEGORYCODE, UPPER(TRIM(PC2.PERSONNELCATEGORYDESCRIPTION)) AS PERSONNELCATEGORYDESCRIPTION234, A2.EMPLOYEECODE AS EMPLOYEECODE234,
CASE WHEN P2.GENDER='MALE' THEN 'SHRI. ' || UPPER(P2.FULLNAME) WHEN P2.GENDER='FEMALE' THEN 'SMT./KUM. ' || UPPER(P2.FULLNAME) END AS FULLNAME234,
UPPER(TRIM(O2.OFFICENAME)) AS OFFICENAME234, UPPER(TRIM(P2.DESIGNATION)) AS DESIGNATION234, P2.MOBILENO AS MOBILENO234,
CASE WHEN PSECT.GENDER='MALE' THEN 'SHRI. ' || UPPER(PSECT.FULLNAME) WHEN PSECT.GENDER='FEMALE' THEN 'SMT./KUM. ' || UPPER(PSECT.FULLNAME) END AS SECTOROFFICERNAME, UPPER(TRIM(PSECT.MOBILENO)) AS SECTOROFFICERMOBILENO ,
TO_CHAR(MM.MATERIALCOLLECTIONDATE, 'dd-mm-yyyy') AS MATERIALCOLLECTIONDATE , MATERIALCOLLECTIONTIME, MATERIALCOLLECTIONVENUE,
TO_CHAR(MM.EVMCOLLECTIONDATE, 'dd-mm-yyyy') AS EVMCOLLECTIONDATE , EVMCOLLECTIONTIME, EVMCOLLECTIONVENUE,
TO_CHAR(MM.MOVEMENTDATE, 'dd-mm-yyyy') AS MOVEMENTDATE , MOVEMENTTIME
FROM (SELECT P1.ACNO, P1.PARTNO, P1.PSNO, P1.PERSONNELCATEGORYCODE,  P1.EMPLOYEECODE   FROM POLLINGALLOCATION3 P1 WHERE PERSONNELCATEGORYCODE = 1 ) A1
INNER JOIN (SELECT P2.ACNO, P2.PARTNO, P2.PSNO, P2.PERSONNELCATEGORYCODE,  P2.EMPLOYEECODE   FROM POLLINGALLOCATION3 P2 WHERE P2.PERSONNELCATEGORYCODE > 1 ) A2
ON (A1.ACNO = A2.ACNO AND A1.PARTNO = A2.PARTNO AND A1.PSNO = A2.PSNO )
INNER JOIN VWPERSONNEL P1 ON P1.EMPLOYEECODE = A1.EMPLOYEECODE
INNER JOIN MASTERS.OFFICES O1 ON O1.OFFICECODE = P1.OFFICECODE
INNER JOIN MASTERS.PERSONNELCATEGORIES PC1 ON PC1.PERSONNELCATEGORYCODE= P1.PERSONNELCATEGORYCODE
INNER JOIN VWPERSONNEL P2 ON P2.EMPLOYEECODE = A2.EMPLOYEECODE
INNER JOIN MASTERS.OFFICES O2 ON O2.OFFICECODE = P2.OFFICECODE
INNER JOIN MASTERS.PERSONNELCATEGORIES PC2 ON PC2.PERSONNELCATEGORYCODE= P2.PERSONNELCATEGORYCODE
INNER JOIN MASTERS.POLLINGSTATIONS PS ON (PS.ACNO = A1.ACNO AND PS.PARTNO = A1.PARTNO AND PS.PSNO = A1.PSNO
AND PS.ACNO = A2.ACNO AND PS.PARTNO = A2.PARTNO AND PS.PSNO = A2.PSNO)
INNER JOIN MASTERS.ACPARTS AP ON (AP.ACNO = PS.ACNO AND AP.PARTNO = PS.PARTNO)
INNER JOIN MASTERS.ASSEMBLYCONSTITUENCIES AC ON AC.ACNO = AP.ACNO
INNER JOIN MASTERS.OFFICES EO ON (EO.OFFICECODE = O1.REFERENCEOFFICECODE AND EO.OFFICECODE = O2.REFERENCEOFFICECODE )
INNER JOIN MASTERS.DISTRICTS D ON D.DISTRICTCODE = EO.DISTRICTCODE
INNER JOIN MASTERS.MASTERTABLE M ON EO.OFFICECODE = M.OFFICECODE
INNER JOIN MASTERS.SECTORSPS SPS ON (AC.ACNO = SPS.ACNO AND AP.PARTNO = SPS.PARTNO AND SPS.ACNO = A1.ACNO AND SPS.PARTNO = A2.PARTNO)
INNER JOIN MASTERS.SECTOROFFICERS SOF ON (EO.OFFICECODE = SOF.OFFICECODE AND SPS.SECTORNO = SOF.SECTORNO)
INNER JOIN MASTERS.SECTORS S ON (EO.OFFICECODE = S.OFFICECODE AND SPS.SECTORNO = S.SECTORNO)
INNER JOIN VWPERSONNEL PSECT ON PSECT.EMPLOYEECODE = SOF.EMPLOYEECODE1
INNER JOIN MASTERS.MATERIALMOVEMENT MM ON (AC.ACNO = MM.ACNO AND AP.PARTNO = MM.PARTNO)
AND $X{IN, EO.OFFICECODE, electionoffice}
AND $X{IN, O.OFFICECODE ,officecode}
AND $X{IN, PC.PERSONNELCATEGORYCODE::TEXT,appointedas}
AND $X{IN, P.EMPLOYEECODE, employeecodes}
AND $X{IN, AC.ACNO::TEXT,acno}
ORDER BY A1.ACNO, A1.PARTNO, A1.PSNO, A1.PERSONNELCATEGORYCODE, A2.PERSONNELCATEGORYCODE
LIMIT 10