INSERT INTO MASTERS.SECTORSPS
SELECT DISTINCT OFFICECODE, SECTORNO, ACNO, PARTNO, USERID, ENTRYDATE FROM LOGS.SECTORSPS 
WHERE (ACNO, PARTNO, ENTRYDATE  ) IN (
SELECT ACNO, PARTNO, MAX(ENTRYDATE)  FROM LOGS.SECTORSPS 
GROUP BY ACNO, PARTNO
ORDER BY ACNO, PARTNO
)
AND (ACNO, PARTNO) NOT IN (SELECT ACNO, PARTNO FROM MASTERS.SECTORSPS)
ORDER BY ACNO, PARTNO
