SELECT * FROM ONLINEAPPLICATIONS WHERE ADCODE = 'M008' AND APPLICATIONCODE LIKE 'M001%';

UPDATE ONLINEAPPLICATIONS SET ADCODE = 'M001' WHERE ADCODE = 'M008' AND APPLICATIONCODE LIKE 'M001%';
UPDATE ONLINEAPPLICATIONS SET ADCODE = 'M002' WHERE ADCODE = 'M009' AND APPLICATIONCODE LIKE 'M002%';
UPDATE ONLINEAPPLICATIONS SET ADCODE = 'M003' WHERE ADCODE = 'M010' AND APPLICATIONCODE LIKE 'M003%';
UPDATE ONLINEAPPLICATIONS SET ADCODE = 'M004' WHERE ADCODE = 'M011' AND APPLICATIONCODE LIKE 'M004%';

UPDATE APPLICATIONSCOUNTER SET ADCODE = 'M001' WHERE ADCODE = 'M008' AND APPLICATIONCODE LIKE 'M001%';
UPDATE APPLICATIONSCOUNTER SET ADCODE = 'M002' WHERE ADCODE = 'M009' AND APPLICATIONCODE LIKE 'M002%';
UPDATE APPLICATIONSCOUNTER SET ADCODE = 'M003' WHERE ADCODE = 'M010' AND APPLICATIONCODE LIKE 'M003%';
UPDATE APPLICATIONSCOUNTER SET ADCODE = 'M004' WHERE ADCODE = 'M011' AND APPLICATIONCODE LIKE 'M004%';





DELETE FROM APPLICATIONSPHDETAILS WHERE APPLICATIONCODE LIKE 'M011%';
DELETE FROM APPLICATIONSUBJECTS WHERE APPLICATIONCODE LIKE 'M011%';
DELETE FROM APPLICATIONSQUALIFICATIONS WHERE APPLICATIONCODE LIKE 'M011%';
DELETE FROM APPLICATIONS WHERE APPLICATIONCODE LIKE 'M011%';
DELETE FROM APPLICATIONSCOUNTER WHERE APPLICATIONCODE LIKE 'M011%';
