-- ACS
SELECT  /*D.DISTRICTCODE, DISTRICTNAME, */ O.OFFICECODE, OFFICENAME, AC.ACNO , ACNAME 
FROM MASTERS.DISTRICTS D INNER JOIN MASTERS.ASSEMBLYCONSTITUENCIES AC ON D.DISTRICTCODE = AC.DISTRICTCODE 
INNER JOIN MASTERS.OFFICES O ON  D.DISTRICTCODE = O.DISTRICTCODE 
INNER JOIN  MASTERS.OFFICESACS OA ON (O.OFFICECODE = OA.OFFICECODE AND AC.ACNO = OA.ACNO)
ORDER BY AC.ACNO;


-- AC PARTS
SELECT  /*D.DISTRICTCODE, DISTRICTNAME, */ O.OFFICECODE, OFFICENAME, AC.ACNO , ACNAME , AP.PARTNO, PARTNAME
FROM MASTERS.DISTRICTS D INNER JOIN MASTERS.ASSEMBLYCONSTITUENCIES AC ON D.DISTRICTCODE = AC.DISTRICTCODE 
INNER JOIN MASTERS.OFFICES O ON  D.DISTRICTCODE = O.DISTRICTCODE 
INNER JOIN  MASTERS.OFFICESACS OA ON (O.OFFICECODE = OA.OFFICECODE AND AC.ACNO = OA.ACNO)
INNER JOIN MASTERS.ACPARTS AP ON (AC.ACNO = AP.ACNO)
WHERE TRIM(UPPER(PARTNAME)) = 'LAITKSEH'
ORDER BY AC.ACNO, AP.PARTNO
;

SELECT  OFFICENAME,M. HEADER1, M.HEADER2, M.HEADER3 , 
AC.ACNO , ACNAME, PARTS 
FROM MASTERS.DISTRICTS D INNER JOIN MASTERS.ASSEMBLYCONSTITUENCIES AC ON D.DISTRICTCODE = AC.DISTRICTCODE 
INNER JOIN MASTERS.OFFICES O ON  D.DISTRICTCODE = O.DISTRICTCODE 
INNER JOIN MASTERS.MASTERTABLE M ON O.OFFICECODE = M.OFFICECODE
INNER JOIN  MASTERS.OFFICESACS OA ON (O.OFFICECODE = OA.OFFICECODE AND AC.ACNO = OA.ACNO)
INNER JOIN 	(
		SELECT AP.ACNO, ARRAY_TO_STRING( ARRAY_AGG( AP.PARTNO || '-' || AP.PARTNAME), E'\n') AS PARTS
		FROM MASTERS.ACPARTS AP GROUP BY AP.ACNO ORDER BY AP.ACNO
		) PAGG
ON AC.ACNO =PAGG.ACNO 
ORDER BY AC.ACNO, PARTS
--AP.PARTNO, PS.PSNO




-- POLLING STATIONS
SELECT  /*D.DISTRICTCODE, DISTRICTNAME, */ O.OFFICECODE, OFFICENAME, AC.ACNO , ACNAME , AP.PARTNO, PARTNAME, PSNO, PSNAME
FROM MASTERS.DISTRICTS D INNER JOIN MASTERS.ASSEMBLYCONSTITUENCIES AC ON D.DISTRICTCODE = AC.DISTRICTCODE 
INNER JOIN MASTERS.OFFICES O ON  D.DISTRICTCODE = O.DISTRICTCODE 
INNER JOIN  MASTERS.OFFICESACS OA ON (O.OFFICECODE = OA.OFFICECODE AND AC.ACNO = OA.ACNO)
INNER JOIN MASTERS.ACPARTS AP ON (AC.ACNO = AP.ACNO)
INNER JOIN MASTERS.POLLINGSTATIONS PS ON (AP.ACNO = PS.ACNO AND AP.PARTNO = PS.PARTNO)
ORDER BY AC.ACNO, AP.PARTNO,PS.PSNO




--SECTORS
SELECT OFFICENAME,SECTORNAME, AC.ACNO , ACNAME , AP.PARTNO, PARTNAME, AC.ACNO || '-' || ACNAME AS AC, AP.PARTNO || '-' ||  PARTNAME AS PART
FROM MASTERS.OFFICES EO INNER JOIN MASTERS.OFFICESACS OA ON EO.OFFICECODE = OA.OFFICECODE
INNER JOIN MASTERS.ASSEMBLYCONSTITUENCIES AC ON AC.ACNO = OA.ACNO
INNER JOIN MASTERS.ACPARTS AP ON (AC.ACNO = AP.ACNO)
INNER JOIN MASTERS.POLLINGSTATIONS PS ON (AP.ACNO = PS.ACNO AND AP.PARTNO = PS.PARTNO)
INNER JOIN MASTERS.SECTORSPS SPS ON (AP.ACNO = SPS.ACNO AND AP.PARTNO = SPS.PARTNO)
INNER JOIN MASTERS.SECTORS S ON (EO.OFFICECODE = S.OFFICECODE AND S.SECTORNO =SPS.SECTORNO)
ORDER BY AC.ACNO, AP.PARTNO, PS.PSNO





-- ELECTION OFFICES 
SELECT * FROM MASTERS.OFFICES WHERE ISELECTIONOFFICE = 'Y' AND ENABLED = 'Y'

--NON ELECTION OFFICES 
SELECT 
O1.OFFICENAME, 
O2.* FROM MASTERS.OFFICES O1, MASTERS.OFFICES O2 WHERE O1.OFFICECODE = O2.REFERENCEOFFICECODE  AND O2.ISELECTIONOFFICE = 'N' AND O2.ENABLED = 'Y'


SELECT EO.OFFICENAME, O.OFFICENAME , O.HEADER1, O.HEADER2
FROM MASTERS.OFFICES EO INNER JOIN MASTERS.OFFICES O ON EO.OFFICECODE  = O.REFERENCEOFFICECODE 
WHERE ENABLED = 'Y'
ORDER  BY EO.OFFICENAME, O.OFFICENAME , O.HEADER1, O.HEADER2 ;





--personnel 
SELECT M. HEADER1, M.HEADER2, M.HEADER3, 
--EO.OFFICENAME AS ELECTIONOFFICE, 
O.OFFICENAME AS PARENTOFFICE, 
FULLNAME, GENDER, DESIGNATION, PERSONNELCATEGORYDESCRIPTION , DOB, 
O.OFFICENAME, CELLDESCRIPTION  
FROM MASTERS.OFFICES EO INNER JOIN MASTERS.OFFICES O ON EO.OFFICECODE  = O.REFERENCEOFFICECODE 
INNER JOIN PERSONNEL P ON O.OFFICECODE = P.OFFICECODE
INNER JOIN MASTERS.PERSONNELCATEGORIES PC ON PC.PERSONNELCATEGORYCODE = P.PERSONNELCATEGORYCODE
INNER JOIN MASTERS.CELLS C ON C.CELLCODE = PC.CELLCODE 
INNER JOIN MASTERS.MASTERTABLE M ON EO.OFFICECODE = M.OFFICECODE
INNER JOIN MASTERS.ASSEMBLYCONSTITUENCIES AC ON AC.ACNO = P.ACNO 
WHERE  O.ENABLED = 'Y' 
ORDER  BY EO.OFFICENAME, O.OFFICENAME , O.HEADER1, O.HEADER2
LIMIT 10 


--USERS
SELECT U.USERID, FULLNAME, OFFICENAME, EMAIL,USERPASSWORD,  MOBILENUMBER, U.ENABLED, DESIGNATION 
FROM USERS.USERACCOUNTS U INNER JOIN USERS.USEROFFICES UO ON U.USERID = UO.USERID
INNER JOIN MASTERS.OFFICES O ON O.OFFICECODE = UO.OFFICECODE 
ORDER BY OFFICENAME , FULLNAME
