SELECT O.OFFICECODE, 
TP.PHASENO, LETTERNOFORMAT, LETTERSLNO,
M.HEADER1, M.HEADER2, M.HEADER3,
EO.OFFICENAME AS ELECTIONOFFICE, TP.PHASENO, TS.SESSIONCODE, TO_CHAR(TS.TRAININGDATE,'DD-MM-YYYY') AS TRAININGDATE, TO_CHAR(STARTTIME,'HH:MI AM') || ' - '  || TO_CHAR(ENDTIME,'HH:MI AM') AS TIMINGS, VENUEDESCRIPTION, C.PERSONNELCATEGORYCODE, PERSONNELCATEGORYDESCRIPTION,
P.EMPLOYEECODE, UPPER(FULLNAME) AS FULLNAME, UPPER(DESIGNATION) AS DESIGNATION, UPPER(O.OFFICENAME) AS OFFICENAME, EO.SIGNATORYNAME, EO.SIGNATORYDESIGNATION, EO.SIGNATURE AS SIGNATURE1, EO.SIGNATURE AS SIGNATURE2, INITCAP(DISTRICTNAME) AS DISTRICTNAME, INITCAP(DISTRICTHQ) AS DISTRICTHQ, 
LETTERNOFORMAT,LETTERSLNO,
to_char(now(), 'DD') || get_ordinal_suffix(EXTRACT(DAY FROM CURRENT_DATE)::INTEGER) || ' ' || to_char(CURRENT_DATE, 'Month YYYY') AS LETTERDATE
FROM
MASTERS.DISTRICTS D INNER JOIN MASTERS.OFFICES EO ON D.DISTRICTCODE = EO.DISTRICTCODE INNER JOIN MASTERS.OFFICES O ON EO.OFFICECODE  = O.REFERENCEOFFICECODE
INNER JOIN MASTERS.MASTERTABLE M ON EO.OFFICECODE = M.OFFICECODE
INNER JOIN ELECTIONS.VWPERSONNEL P ON O.OFFICECODE = P.OFFICECODE
INNER JOIN MASTERS.PERSONNELCATEGORIES C ON C.PERSONNELCATEGORYCODE = P.PERSONNELCATEGORYCODE
INNER JOIN TRAININGPHASES TP ON EO.OFFICECODE = TP.OFFICECODE
INNER JOIN TRAININGTYPES TT ON TP.TRAININGTYPECODE = TT.TRAININGTYPECODE
INNER JOIN TRAININGVENUES TV ON TP.OFFICECODE = TV.OFFICECODE
INNER JOIN TRAININGLETTERNOFORMAT TF ON (EO.OFFICECODE = TF.OFFICECODE AND TP.TRAININGTYPECODE = TF.TRAININGTYPECODE AND TP.PHASENO = TF.PHASENO )
INNER JOIN TRAININGSESSIONS TS ON (EO.OFFICECODE = TS.OFFICECODE AND TP.TRAININGTYPECODE = TS.TRAININGTYPECODE AND TP.PHASENO = TS.PHASENO  AND  TV.VENUECODE = TS.VENUECODE)
INNER JOIN TRAININGPERSONNEL TPER ON (TS.SESSIONCODE = TPER.SESSIONCODE AND P.EMPLOYEECODE = TPER.EMPLOYEECODE)
WHERE 1 = 1
AND EO.OFFICECODE ='020001'
AND (TRIM(UPPER(FULLNAME)) LIKE 'THERESIA%'
OR TRIM(UPPER(FULLNAME)) LIKE '%WANDA%MAKDOH%')
AND TP.PHASENO IN (1,2,3)
ORDER BY EO.OFFICENAME, O.OFFICENAME, FULLNAME, TP.PHASENO, TS.TRAININGDATE , STARTTIME, ENDTIME, VENUEDESCRIPTION, C.PERSONNELCATEGORYCODE