SELECT P.EMPLOYEECODE, PERSONNELCATEGORYDESCRIPTION, OFFICENAME, 
FULLNAME, GENDER, TO_CHAR(DOB,'DD-MM-YYYY') AS DOB, DESIGNATION, BASICPAY, ACNO, PARTNO, MOBILENO, ISBLO, ISEXPECTINGLACTATING,ISAILING , EXPERIENCE
FROM MASTERS.OFFICES O INNER JOIN ELECTIONS.PERSONNEL P  ON O.OFFICECODE = P.OFFICECODE 
INNER JOIN MASTERS.PERSONNELCATEGORIES PC ON PC.PERSONNELCATEGORYCODE = P.PERSONNELCATEGORYCODE
LEFT OUTER JOIN
(
SELECT PE.EMPLOYEECODE , 
ARRAY_TO_STRING(ARRAY_AGG(PERSONNELCATEGORYDESCRIPTION || ' : No of times - ' || NUMBERS  || ' '),E':::::') AS EXPERIENCE
FROM MASTERS.PERSONNELCATEGORIES PC INNER JOIN ELECTIONS.PERSONNELEXPERIENCE PE ON PC.PERSONNELCATEGORYCODE = PE.PERSONNELCATEGORYCODE
GROUP BY PE.EMPLOYEECODE
) EX
ON P.EMPLOYEECODE = EX.EMPLOYEECODE
WHERE P.OFFICECODE LIKE '03%'
ORDER BY OFFICENAME, PC.PERSONNELCATEGORYCODE 

