SELECT P.EMPLOYEECODE, PERSONNELCATEGORYDESCRIPTION, OFFICENAME, 
FULLNAME, GENDER, TO_CHAR(DOB,'DD-MM-YYYY') AS DOB, DESIGNATION, BASICPAY, AP.ACNO, ACNAME, AP.PARTNO, PARTNAME, MOBILENO, ISBLO, ISEXPECTINGLACTATING,ISAILING , EPICCARDNO
FROM MASTERS.OFFICES O INNER JOIN ELECTIONS.PERSONNEL P  ON O.OFFICECODE = P.OFFICECODE 
INNER JOIN MASTERS.PERSONNELCATEGORIES PC ON PC.PERSONNELCATEGORYCODE = P.PERSONNELCATEGORYCODE1
INNER JOIN MASTERS.ACPARTS AP ON (AP.ACNO = P.ACNO AND AP.PARTNO = P.PARTNO)
INNER JOIN MASTERS.ASSEMBLYCONSTITUENCIES AC ON (AC.ACNO = P.ACNO )

WHERE P.OFFICECODE LIKE '03%'
ORDER BY OFFICENAME, PC.PERSONNELCATEGORYCODE 

