SELECT 

DOB, P.EMPLOYEECODE, FULLNAME, 

TO_CHAR(MOVEMENTDATE, 'DD-MM-YYYY') AS MOVEMENTDATE , AC.ACNO || '-' || ACNAME AS AC, AP.PARTNO || '-' || PARTNAME AS PART,
PERSONNELCATEGORYDESCRIPTION, P.EMPLOYEECODE,
CASE WHEN GENDER='MALE' THEN 'Shri. ' || INITCAP(FULLNAME) WHEN GENDER='FEMALE' THEN 'Smt./Kum. ' || INITCAP(FULLNAME) END AS FULLNAME,
DESIGNATION, O.OFFICENAME AS OFFICENAME, MOBILENO
FROM MASTERS.DISTRICTS D INNER JOIN MASTERS.OFFICES EO ON D.DISTRICTCODE = EO.DISTRICTCODE
INNER JOIN MASTERS.OFFICES O ON EO.OFFICECODE = O.REFERENCEOFFICECODE
INNER JOIN MASTERS.MASTERTABLE M ON EO.OFFICECODE = M.OFFICECODE
INNER JOIN VWPERSONNEL P ON O.OFFICECODE = P.OFFICECODE
INNER JOIN MASTERS.PERSONNELCATEGORIES PC ON PC.PERSONNELCATEGORYCODE = P.PERSONNELCATEGORYCODE
INNER JOIN POLLINGALLOCATION3 PA3 ON (P.EMPLOYEECODE = PA3.EMPLOYEECODE AND P.PERSONNELCATEGORYCODE = PA3.PERSONNELCATEGORYCODE)
INNER JOIN MASTERS.POLLINGSTATIONS PS ON (PS.ACNO = PA3.ACNO AND PS.PARTNO = PA3.PARTNO AND PS.PSNO = PA3.PSNO)
INNER JOIN MASTERS.ACPARTS AP ON (AP.ACNO = PS.ACNO AND AP.PARTNO = PS.PARTNO)
INNER JOIN MASTERS.ASSEMBLYCONSTITUENCIES AC ON AC.ACNO = AP.ACNO
INNER JOIN MASTERS.PSPARAMETERS PSP ON (PS.ACNO = PSP.ACNO AND PS.PARTNO = PSP.PARTNO AND PS.PSNO = PSP.PSNO)
INNER JOIN MASTERS.MATERIALMOVEMENT MM ON (PS.ACNO = MM.ACNO AND PS.PARTNO = MM.PARTNO)
WHERE 1 = 1
AND EO.OFFICECODE ='030001' AND MOVEMENTDATE = '2025-02-19'
ORDER BY MOVEMENTDATE, AC.ACNO, AP.PARTNO, P.PERSONNELCATEGORYCODE