SELECT AC.ACNO || '-' || ACNAME, AP.ACNO || '-' ||  AP.PARTNAME, PS.PSNO 
FROM MASTERS.ASSEMBLYCONSTITUENCIES AC INNER JOIN MASTERS.ACPARTS AP ON AC.ACNO = AP.ACNO INNER JOIN MASTERS.POLLINGSTATIONS PS ON ( AP.ACNO = PS.ACNO AND AP.PARTNO = PS.PARTNO)
WHERE (PS.ACNO, PS.PARTNO, PS.PSNO) NOT IN (SELECT ACNO, PARTNO, PSNO FROM MASTERS.PSPARAMETERS)
ORDER BY PS.ACNO, PS.PARTNO, PS.PSNO;
