--select * from pollingreserves LIMIT 1;
INSERT INTO POLLINGRESERVES 
SELECT EO.OFFICECODE, P.EMPLOYEECODE, CURRENT_TIMESTAMP, 22, 'Y' FROM MASTERS.OFFICES EO INNER JOIN MASTERS.OFFICES O ON EO.OFFICECODE = O.REFERENCEOFFICECODE 
INNER JOIN VWPERSONNEL P ON O.OFFICECODE = P.OFFICECODE 
WHERE EO.OFFICECODE = '080001'
AND PERSONNELCATEGORYCODE IN (1, 2, 3, 4 )
AND P.EMPLOYEECODE NOT IN (
SELECT EMPLOYEECODE FROM POLLINGALLOCATION3 WHERE OFFICECODE = '080001'
UNION ALL 
SELECT EMPLOYEECODE FROM POLLINGRESERVES WHERE OFFICECODE = '080001'
)