INSERT INTO COUNTINGRESERVES
SELECT '080001', EMPLOYEECODE, CURRENT_TIMESTAMP, 22, 'Y' FROM VWPERSONNEL WHERE PERSONNELCATEGORYCODE IN (21, 22) AND OFFICECODE LIKE '08%'
AND EMPLOYEECODE NOT IN 
(
SELECT EMPLOYEECODE FROM COUNTINGALLOCATION3
UNION ALL 
SELECT EMPLOYEECODE FROM COUNTINGRESERVES
);


