UPDATE MASTERS.OFFICES SET SIGNATORYDESIGNATION = 'Headmaster/Headmistress' WHERE OFFICECODE IN 
(
SELECT OFFICECODE  FROM MASTERS.OFFICES WHERE OFFICECODE LIKE '02%' 
--AND TRIM(UPPER(OFFICENAME)) LIKE '%SCHOOL%'
AND UPPER(SIGNATORYDESIGNATION) LIKE '%TEACHER%'
)
AND OFFICECODE IN 
(
SELECT OFFICECODE FROM LOGS.OFFICES WHERE OFFICECODE LIKE '02%' 
--AND TRIM(UPPER(OFFICENAME)) LIKE '%SCHOOL%' AND UPPER(SIGNATORYDESIGNATION) LIKE '%TEACHER%'
--AND TO_CHAR(ACTIONDATE, 'DD-MM-YYYY') ='20-03-2024'
)
)


