SELECT * FROM VWPOLLINGALLOCATION2
WHERE 1 = 1 
--AND (AGE  > 50  AND NONMOTORABLEDISTANCE > 1)
--AND (GENDER = 'FEMALE' AND NONMOTORABLEDISTANCE > 1)
AND (ACNO, PARTNO, PSNO, GENDER) IN (SELECT ACNO, PARTNO, PSNO, GENDER FROM VWPOLLINGALLOCATION2 VWA2 WHERE 1 = 1  AND GENDER='FEMALE' GROUP BY ACNO, PARTNO, PSNO, GENDER HAVING COUNT(*) = 1 AND GENDER = 'FEMALE') 
ORDER BY ACNO, PARTNO, PSNO


--SAME OFFICE
SELECT ACNO, PARTNO, PSNO, OFFICECODE FROM VWPOLLINGALLOCATION2 VWA2 WHERE 1 = 1  GROUP BY ACNO, PARTNO, PSNO, OFFICECODE HAVING COUNT(*) > 1

ORDER BY ACNO, PARTNO, PSNO


