-- INSERT ALL PS
INSERT INTO MASTERS.PSPARAMETERS SELECT ACNO, PARTNO, PSNO, 1, 1, 0 ,0,1, CURRENT_TIMESTAMP FROM MASTERS.POLLINGSTATIONS
WHERE (ACNO, PARTNO, PSNO) NOT IN (SELECT ACNO, PARTNO, PSNO FROM MASTERS.PSPARAMETERS);

SELECT * FROM MASTERS.PSRANDOMIZATIONTYPES ; 


--PINK POLLING STATIONS
UPDATE MASTERS.PSPARAMETERS SET PSRTYPESCODE = 2 WHERE PARTNO = 1;

--YOUTH POLLING STATIONS
UPDATE MASTERS.PSPARAMETERS SET PSRTYPESCODE = 2 WHERE PARTNO = 2;

--PWD MANAGED POLLING STATIONS
UPDATE MASTERS.PSPARAMETERS SET PSRTYPESCODE = 2 WHERE PARTNO = 1;