SELECT  DISTINCT EO.OFFICENAME, P.EMPLOYEECODE, INITCAP(TRIM(O.OFFICENAME)) AS OFFICENAME, FULLNAME, C.PERSONNELCATEGORYCODE, PERSONNELCATEGORYDESCRIPTION,   MOBILENO, 
COALESCE((SELECT ATTENDANCE FROM TRAININGSESSIONS TSI INNER JOIN TRAININGPERSONNEL TPI  ON TSI.SESSIONCODE= TPI.SESSIONCODE
INNER JOIN TRAININGATTENDANCE TAI ON (TSI.SESSIONCODE = TAI.SESSIONCODE AND TPI.EMPLOYEECODE = TAI.EMPLOYEECODE) WHERE TSI.PHASENO = 1 AND TPI.EMPLOYEECODE = P.EMPLOYEECODE),'N','Y') AS PHASE1, 

COALESCE((SELECT ATTENDANCE FROM TRAININGSESSIONS TSI INNER JOIN TRAININGPERSONNEL TPI  ON TSI.SESSIONCODE= TPI.SESSIONCODE
INNER JOIN TRAININGATTENDANCE TAI ON (TSI.SESSIONCODE = TAI.SESSIONCODE AND TPI.EMPLOYEECODE = TAI.EMPLOYEECODE) WHERE TSI.PHASENO = 2 AND TPI.EMPLOYEECODE = P.EMPLOYEECODE),'N','Y') AS PHASE2 

FROM MASTERS.DISTRICTS D INNER JOIN MASTERS.OFFICES EO ON D.DISTRICTCODE = EO.DISTRICTCODE INNER JOIN MASTERS.OFFICES O ON EO.OFFICECODE  = O.REFERENCEOFFICECODE  INNER JOIN MASTERS.MASTERTABLE M ON EO.OFFICECODE = M.OFFICECODE  INNER JOIN ELECTIONS.VWPERSONNEL P ON O.OFFICECODE = P.OFFICECODE  
INNER JOIN MASTERS.PERSONNELCATEGORIES C ON C.PERSONNELCATEGORYCODE = P.PERSONNELCATEGORYCODE  INNER JOIN TRAININGPHASES TP ON EO.OFFICECODE = TP.OFFICECODE  INNER JOIN TRAININGTYPES TT ON TP.TRAININGTYPECODE = TT.TRAININGTYPECODE  INNER JOIN TRAININGVENUES TV ON TP.OFFICECODE = TV.OFFICECODE  INNER JOIN TRAININGLETTERNOFORMAT TF ON (EO.OFFICECODE = TF.OFFICECODE AND TP.TRAININGTYPECODE = TF.TRAININGTYPECODE AND TP.PHASENO = TF.PHASENO )  INNER JOIN TRAININGSESSIONS TS ON (EO.OFFICECODE = TS.OFFICECODE AND TP.TRAININGTYPECODE = TS.TRAININGTYPECODE AND TP.PHASENO = TS.PHASENO  AND  TV.VENUECODE = TS.VENUECODE)  INNER JOIN TRAININGPERSONNEL TPER ON (TS.SESSIONCODE = TPER.SESSIONCODE AND P.EMPLOYEECODE = TPER.EMPLOYEECODE)  LEFT JOIN TRAININGATTENDANCE TAT ON (TS.SESSIONCODE = TAT.SESSIONCODE AND TPER.EMPLOYEECODE = TAT.EMPLOYEECODE)  
INNER JOIN POLLINGRESERVES R ON P.EMPLOYEECODE = R.EMPLOYEECODE 
WHERE 1 = 1   AND EO.OFFICECODE = '030001' 
ORDER BY EO.OFFICENAME, C.PERSONNELCATEGORYCODE, FULLNAME ; 
