
UPDATE MASTERS.ACPARTS SET PARTNAME =  REPLACE(PARTNAME, '''', '`')  WHERE PARTNAME LIKE '%''';
UPDATE MASTERS.POLLINGSTATIONS SET PSNAME =  REPLACE(PSNAME, '''', '`')  WHERE PSNAME LIKE '%''';
UPDATE MASTERS.POLLINGSTATIONS SET PSADDRESS =  REPLACE(PSADDRESS, '''', '`')  WHERE PSADDRESS LIKE '%''';
UPDATE MASTERS.ACPARTS SET PARTNAME =  REPLACE(PARTNAME, '''', '`')  WHERE PARTNAME LIKE '%''%';
UPDATE MASTERS.POLLINGSTATIONS SET PSNAME =  REPLACE(PSNAME, '''', '`')  WHERE PSNAME LIKE '%''%';
UPDATE MASTERS.POLLINGSTATIONS SET PSADDRESS =  REPLACE(PSADDRESS, '''', '`')  WHERE PSADDRESS LIKE '%''%';
--UPDATE MASTERS.OFFICES SET OFFICENAME = TRIM(OFFICENAME);
UPDATE MASTERS.OFFICES SET OFFICENAME   = UPPER(TRIM(REPLACE(OFFICENAME, '&', 'AND')))  WHERE OFFICENAME LIKE '%&%';
UPDATE ELECTIONS.TRAININGLETTERNOFORMAT SET LETTERNOFORMAT = TRIM(LETTERNOFORMAT);
UPDATE ELECTIONS.TRAININGVENUES SET VENUEDESCRIPTION=  REPLACE(VENUEDESCRIPTION, '''', '`')  WHERE VENUEDESCRIPTION LIKE '%''%';
UPDATE MASTERS.OFFICES SET OFFICENAME   = UPPER(TRIM(REPLACE(OFFICENAME, '''', '`')))  WHERE OFFICENAME LIKE '%''%';
