/*

SELECT  'UPDATE PERSONNEL SET PERSONNELCATEGORYCODE = ' ||  PL.PERSONNELCATEGORYCODE || ' WHERE EMPLOYEECODE = ''' ||  P.EMPLOYEECODE || ''';'
FROM 
MASTERS.OFFICES EO INNER JOIN MASTERS.OFFICES O ON EO.OFFICECODE = O.REFERENCEOFFICECODE 
INNER JOIN PERSONNEL P ON O.OFFICECODE = P.OFFICECODE
INNER JOIN MASTERS.PERSONNELCATEGORIES PC ON PC.PERSONNELCATEGORYCODE = P.PERSONNELCATEGORYCODE 
INNER JOIN LOGS.PERSONNEL PL ON P.EMPLOYEECODE = PL.EMPLOYEECODE 
WHERE 1 = 1 AND EO.OFFICECODE = '030003' 
--AND TRAININGFLAGCODE = 'C'
AND P.PERSONNELCATEGORYCODE = 999
AND PL.ACTIONDATE >= '2025-02-21'
--GROUP BY EO.OFFICENAME,  PERSONNELCATEGORYDESCRIPTION
ORDER BY EO.OFFICENAME,  PERSONNELCATEGORYDESCRIPTION
;

*/

SELECT P.EMPLOYEECODE, P.PERSONNELCATEGORYCODE FROM 
MASTERS.OFFICES EO INNER JOIN MASTERS.OFFICES O ON EO.OFFICECODE = O.REFERENCEOFFICECODE 
INNER JOIN PERSONNEL P ON O.OFFICECODE = P.OFFICECODE
INNER JOIN PERSONNELDESIGNATION20250221130PM PD ON P.EMPLOYEECODE = PD.EMPLOYEECODE
INNER JOIN MASTERS.PERSONNELCATEGORIES PC ON PC.PERSONNELCATEGORYCODE = P.PERSONNELCATEGORYCODE 
WHERE 1 = 1 

AND P.PERSONNELCATEGORYCODE <> PD.PERSONNELCATEGORYCODE 
AND EO.OFFICECODE = '030003' 
ORDER BY EO.OFFICENAME,  PERSONNELCATEGORYDESCRIPTION;

