SELECT 
EO.OFFICECODE, 
TP.PHASENO, 
TO_CHAR(TS.TRAININGDATE,'DD-MM-YYYY') AS TRAININGDATE, 
VENUEDESCRIPTION, 
FULLNAME, DESIGNATION, INITCAP(TRIM(O.OFFICENAME)) AS OFFICENAME, PERSONNELCATEGORYDESCRIPTION, MOBILENO, 
CASE WHEN ATTENDANCE = 'Y' THEN 'PRESENT' ELSE 'ABSENT' END AS ATTENDANCE  
FROM MASTERS.DISTRICTS D INNER JOIN MASTERS.OFFICES EO ON D.DISTRICTCODE = EO.DISTRICTCODE INNER JOIN MASTERS.OFFICES O ON EO.OFFICECODE  = O.REFERENCEOFFICECODE
INNER JOIN MASTERS.MASTERTABLE M ON EO.OFFICECODE = M.OFFICECODE
INNER JOIN ELECTIONS.VWPERSONNEL P ON O.OFFICECODE = P.OFFICECODE
INNER JOIN MASTERS.PERSONNELCATEGORIES C ON C.PERSONNELCATEGORYCODE = P.PERSONNELCATEGORYCODE
INNER JOIN TRAININGPHASES TP ON EO.OFFICECODE = TP.OFFICECODE
INNER JOIN TRAININGTYPES TT ON TP.TRAININGTYPECODE = TT.TRAININGTYPECODE
INNER JOIN TRAININGVENUES TV ON TP.OFFICECODE = TV.OFFICECODE
INNER JOIN TRAININGLETTERNOFORMAT TF ON (EO.OFFICECODE = TF.OFFICECODE AND TP.TRAININGTYPECODE = TF.TRAININGTYPECODE AND TP.PHASENO = TF.PHASENO )
INNER JOIN TRAININGSESSIONS TS ON (EO.OFFICECODE = TS.OFFICECODE AND TP.TRAININGTYPECODE = TS.TRAININGTYPECODE AND TP.PHASENO = TS.PHASENO  AND  TV.VENUECODE = TS.VENUECODE)
INNER JOIN TRAININGPERSONNEL TPER ON (TS.SESSIONCODE = TPER.SESSIONCODE AND P.EMPLOYEECODE = TPER.EMPLOYEECODE)
INNER JOIN TRAININGATTENDANCE TAT ON (TPER.EMPLOYEECODE = TAT.EMPLOYEECODE)
WHERE 1 = 1 
AND TP.PHASENO =1 AND P.EMPLOYEECODE like '02%'
ORDER BY EO.OFFICENAME, TP.PHASENO, O.OFFICENAME, FULLNAME, TS.TRAININGDATE , STARTTIME, ENDTIME, VENUEDESCRIPTION, C.PERSONNELCATEGORYCODE
