SELECT P1.ACNO, P1.PARTNO, P1.PSNO, P1.EMPLOYEECODE, P1.FULLNAME, P1.DESIGNATION, P1.OFFICENAME, P1.PERSONNELCATEGORYDESCRIPTION,P1.MOBILENO,
P2.EMPLOYEECODE, P2.FULLNAME, P2.DESIGNATION, P2.OFFICENAME, P2.PERSONNELCATEGORYDESCRIPTION,P2.MOBILENO,
P3.EMPLOYEECODE, P3.FULLNAME, P3.DESIGNATION, P3.OFFICENAME, P3.PERSONNELCATEGORYDESCRIPTION,P3.MOBILENO,
P4.EMPLOYEECODE, P4.FULLNAME, P4.DESIGNATION, P4.OFFICENAME, P4.PERSONNELCATEGORYDESCRIPTION,P4.MOBILENO
FROM 
(SELECT AC.ACNO, AP.PARTNO, PS.PSNO,
PC.PERSONNELCATEGORYDESCRIPTION, P.EMPLOYEECODE, CASE WHEN GENDER='MALE' THEN 'Shri. ' || INITCAP(FULLNAME) WHEN GENDER='FEMALE' THEN 'Smt./Kum. ' || INITCAP(FULLNAME) END AS FULLNAME,
DESIGNATION, O.OFFICENAME AS OFFICENAME, MOBILENO 
FROM MASTERS.DISTRICTS D INNER JOIN MASTERS.OFFICES EO ON D.DISTRICTCODE = EO.DISTRICTCODE
INNER JOIN MASTERS.OFFICES O ON EO.OFFICECODE = O.REFERENCEOFFICECODE
INNER JOIN MASTERS.MASTERTABLE M ON EO.OFFICECODE = M.OFFICECODE
INNER JOIN VWPERSONNEL P ON O.OFFICECODE  = P.OFFICECODE
INNER JOIN POLLINGALLOCATION2 PA2 ON (P.EMPLOYEECODE = PA2.EMPLOYEECODE AND P.PERSONNELCATEGORYCODE = PA2.PERSONNELCATEGORYCODE)
INNER JOIN MASTERS.POLLINGSTATIONS PS ON (PS.ACNO =PA2.ACNO AND PS.PARTNO = PA2.PROVISIONALPARTNO AND PS.PSNO = PA2.PROVISIONALPSNO)
INNER JOIN MASTERS.ACPARTS AP ON (AP.ACNO = PS.ACNO AND AP.PARTNO = PS.PARTNO)
INNER JOIN MASTERS.ASSEMBLYCONSTITUENCIES AC ON AC.ACNO = AP.ACNO
INNER JOIN MASTERS.PERSONNELCATEGORIES PC ON PC.PERSONNELCATEGORYCODE = P.PERSONNELCATEGORYCODE
AND EO.OFFICECODE = '030001'   
AND PC.PERSONNELCATEGORYCODE = 1
) P1, 
(SELECT AC.ACNO, AP.PARTNO, PS.PSNO,
PC.PERSONNELCATEGORYDESCRIPTION, P.EMPLOYEECODE, CASE WHEN GENDER='MALE' THEN 'Shri. ' || INITCAP(FULLNAME) WHEN GENDER='FEMALE' THEN 'Smt./Kum. ' || INITCAP(FULLNAME) END AS FULLNAME,
DESIGNATION, O.OFFICENAME AS OFFICENAME, MOBILENO 
FROM MASTERS.DISTRICTS D INNER JOIN MASTERS.OFFICES EO ON D.DISTRICTCODE = EO.DISTRICTCODE
INNER JOIN MASTERS.OFFICES O ON EO.OFFICECODE = O.REFERENCEOFFICECODE
INNER JOIN MASTERS.MASTERTABLE M ON EO.OFFICECODE = M.OFFICECODE
INNER JOIN VWPERSONNEL P ON O.OFFICECODE  = P.OFFICECODE
INNER JOIN POLLINGALLOCATION2 PA2 ON (P.EMPLOYEECODE = PA2.EMPLOYEECODE AND P.PERSONNELCATEGORYCODE = PA2.PERSONNELCATEGORYCODE)
INNER JOIN MASTERS.POLLINGSTATIONS PS ON (PS.ACNO =PA2.ACNO AND PS.PARTNO = PA2.PROVISIONALPARTNO AND PS.PSNO = PA2.PROVISIONALPSNO)
INNER JOIN MASTERS.ACPARTS AP ON (AP.ACNO = PS.ACNO AND AP.PARTNO = PS.PARTNO)
INNER JOIN MASTERS.ASSEMBLYCONSTITUENCIES AC ON AC.ACNO = AP.ACNO
INNER JOIN MASTERS.PERSONNELCATEGORIES PC ON PC.PERSONNELCATEGORYCODE = P.PERSONNELCATEGORYCODE
AND EO.OFFICECODE = '030001'   
AND PC.PERSONNELCATEGORYCODE = 2) P2, 
(SELECT AC.ACNO, AP.PARTNO, PS.PSNO,
PC.PERSONNELCATEGORYDESCRIPTION, P.EMPLOYEECODE, CASE WHEN GENDER='MALE' THEN 'Shri. ' || INITCAP(FULLNAME) WHEN GENDER='FEMALE' THEN 'Smt./Kum. ' || INITCAP(FULLNAME) END AS FULLNAME,
DESIGNATION, O.OFFICENAME AS OFFICENAME, MOBILENO 
FROM MASTERS.DISTRICTS D INNER JOIN MASTERS.OFFICES EO ON D.DISTRICTCODE = EO.DISTRICTCODE
INNER JOIN MASTERS.OFFICES O ON EO.OFFICECODE = O.REFERENCEOFFICECODE
INNER JOIN MASTERS.MASTERTABLE M ON EO.OFFICECODE = M.OFFICECODE
INNER JOIN VWPERSONNEL P ON O.OFFICECODE  = P.OFFICECODE
INNER JOIN POLLINGALLOCATION2 PA2 ON (P.EMPLOYEECODE = PA2.EMPLOYEECODE AND P.PERSONNELCATEGORYCODE = PA2.PERSONNELCATEGORYCODE)
INNER JOIN MASTERS.POLLINGSTATIONS PS ON (PS.ACNO =PA2.ACNO AND PS.PARTNO = PA2.PROVISIONALPARTNO AND PS.PSNO = PA2.PROVISIONALPSNO)
INNER JOIN MASTERS.ACPARTS AP ON (AP.ACNO = PS.ACNO AND AP.PARTNO = PS.PARTNO)
INNER JOIN MASTERS.ASSEMBLYCONSTITUENCIES AC ON AC.ACNO = AP.ACNO
INNER JOIN MASTERS.PERSONNELCATEGORIES PC ON PC.PERSONNELCATEGORYCODE = P.PERSONNELCATEGORYCODE
AND EO.OFFICECODE = '030001'   
AND PC.PERSONNELCATEGORYCODE = 3) P3, 
(SELECT AC.ACNO, AP.PARTNO, PS.PSNO,
PC.PERSONNELCATEGORYDESCRIPTION, P.EMPLOYEECODE, CASE WHEN GENDER='MALE' THEN 'Shri. ' || INITCAP(FULLNAME) WHEN GENDER='FEMALE' THEN 'Smt./Kum. ' || INITCAP(FULLNAME) END AS FULLNAME,
DESIGNATION, O.OFFICENAME AS OFFICENAME, MOBILENO 
FROM MASTERS.DISTRICTS D INNER JOIN MASTERS.OFFICES EO ON D.DISTRICTCODE = EO.DISTRICTCODE
INNER JOIN MASTERS.OFFICES O ON EO.OFFICECODE = O.REFERENCEOFFICECODE
INNER JOIN MASTERS.MASTERTABLE M ON EO.OFFICECODE = M.OFFICECODE
INNER JOIN VWPERSONNEL P ON O.OFFICECODE  = P.OFFICECODE
INNER JOIN POLLINGALLOCATION2 PA2 ON (P.EMPLOYEECODE = PA2.EMPLOYEECODE AND P.PERSONNELCATEGORYCODE = PA2.PERSONNELCATEGORYCODE)
INNER JOIN MASTERS.POLLINGSTATIONS PS ON (PS.ACNO =PA2.ACNO AND PS.PARTNO = PA2.PROVISIONALPARTNO AND PS.PSNO = PA2.PROVISIONALPSNO)
INNER JOIN MASTERS.ACPARTS AP ON (AP.ACNO = PS.ACNO AND AP.PARTNO = PS.PARTNO)
INNER JOIN MASTERS.ASSEMBLYCONSTITUENCIES AC ON AC.ACNO = AP.ACNO
INNER JOIN MASTERS.PERSONNELCATEGORIES PC ON PC.PERSONNELCATEGORYCODE = P.PERSONNELCATEGORYCODE
AND EO.OFFICECODE = '030001'   
AND PC.PERSONNELCATEGORYCODE = 4) P4
WHERE P1.ACNO = P2.ACNO AND P1.PARTNO = P2.PARTNO AND P1.PSNO  = P2.PSNO
AND P1.ACNO = P3.ACNO AND P1.PARTNO = P3.PARTNO AND P1.PSNO  = P3.PSNO
AND P1.ACNO = P4.ACNO AND P1.PARTNO = P4.PARTNO AND P1.PSNO  = P4.PSNO
ORDER BY ACNO, PARTNO, PSNO


