SELECT P.EMPLOYEECODE, FULLNAME, O.OFFICENAME, DESIGNATION , PERSONNELCATEGORYDESCRIPTION, GENDER, ACNO, DATE_PART('YEAR',AGE(NOW(),DOB)) 
FROM MASTERS.OFFICES EO INNER JOIN MASTERS.OFFICES O ON EO.OFFICECODE   = O.REFERENCEOFFICECODE  INNER JOIN VWPERSONNEL P ON O.OFFICECODE = P.OFFICECODE  
INNER JOIN MASTERS.PERSONNELCATEGORIES PC ON P.PERSONNELCATEGORYCODE = PC.PERSONNELCATEGORYCODE  
INNER JOIN (SELECT DISTINCT TA.EMPLOYEECODE FROM TRAININGATTENDANCE TA) T ON P.EMPLOYEECODE = T.EMPLOYEECODE  
WHERE P.EMPLOYEECODE NOT IN (SELECT EMPLOYEECODE FROM POLLINGALLOCATION2)  AND EO.OFFICECODE = '090001' ORDER BY FULLNAME 



SELECT EMPLOYEECODE
FROM MASTERS.OFFICES EO INNER JOIN MASTERS.OFFICES O ON EO.OFFICECODE   = O.REFERENCEOFFICECODE  INNER JOIN VWPERSONNEL P ON O.OFFICECODE = P.OFFICECODE  
WHERE EO.OFFICECODE = '090001' AND PERSONNELCATEGORYCODE IN (1, 2, 3, 4)
AND EMPLOYEECODE NOT IN (
SELECT P.EMPLOYEECODE
FROM MASTERS.OFFICES EO INNER JOIN MASTERS.OFFICES O ON EO.OFFICECODE   = O.REFERENCEOFFICECODE  INNER JOIN VWPERSONNEL P ON O.OFFICECODE = P.OFFICECODE  
INNER JOIN MASTERS.PERSONNELCATEGORIES PC ON P.PERSONNELCATEGORYCODE = PC.PERSONNELCATEGORYCODE  
INNER JOIN (SELECT DISTINCT TA.EMPLOYEECODE FROM TRAININGATTENDANCE TA) T ON P.EMPLOYEECODE = T.EMPLOYEECODE  
WHERE P.EMPLOYEECODE NOT IN (SELECT EMPLOYEECODE FROM POLLINGALLOCATION2)  AND EO.OFFICECODE = '090001' 


UNION ALL 

SELECT P.EMPLOYEECODE
FROM MASTERS.OFFICES EO INNER JOIN MASTERS.OFFICES O ON EO.OFFICECODE   = O.REFERENCEOFFICECODE  INNER JOIN VWPERSONNEL P ON O.OFFICECODE = P.OFFICECODE  
INNER JOIN MASTERS.PERSONNELCATEGORIES PC ON P.PERSONNELCATEGORYCODE = PC.PERSONNELCATEGORYCODE  
INNER JOIN (SELECT DISTINCT TA.EMPLOYEECODE FROM TRAININGATTENDANCE TA) T ON P.EMPLOYEECODE = T.EMPLOYEECODE  
WHERE P.EMPLOYEECODE IN (SELECT EMPLOYEECODE FROM POLLINGALLOCATION2)  AND EO.OFFICECODE = '090001' 

)




875 


484
343






