CREATE SCHEMA sources AUTHORIZATION elections;

--RENAMING COLUMNS
SELECT 'ALTER TABLE ' || TABLE_SCHEMA || '."' || TABLE_NAME || '"  RENAME COLUMN  "' || COLUMN_NAME || '"  TO ' || COLUMN_NAME || ';'
, S.* 
FROM INFORMATION_SCHEMA.COLUMNS S WHERE TABLE_SCHEMA = 'sources'  ORDER BY TABLE_NAME, ORDINAL_POSITION ;



--RENAMING TABLES
SELECT 'ALTER TABLE ' || TABLE_SCHEMA || '."' || TABLE_NAME || '" RENAME TO  ' || TABLE_NAME  || ';'  FROM INFORMATION_SCHEMA.TABLES WHERE TABLE_SCHEMA ='sources';




SELECT 'ALTER TABLE ' || TABLE_SCHEMA || '."' || TABLE_NAME || '" RENAME TO  ' || TABLE_NAME  || ';'  FROM INFORMATION_SCHEMA.TABLES WHERE TABLE_SCHEMA ='sources'

/*
ALTER TABLE sources."ECI_AC_LIST" RENAME TO  AC_LIST;
ALTER TABLE sources."ECI_BLOCKS" RENAME TO  BLOCKS;
--ALTER TABLE sources."ECI_DIST_LIST" RENAME TO  DIST_LIST;
--ALTER TABLE sources."ECI_NNN" RENAME TO  NNN;
ALTER TABLE sources."ECI_PART_LIST" RENAME TO  PART_LIST;
ALTER TABLE sources."ECI_POST_OFFICES" RENAME TO  POST_OFFICES;
ALTER TABLE sources."ECI_POLICE_STATIONS" RENAME TO  POLICE_STATIONS;
ALTER TABLE sources."ECI_PS_BUILDINGS" RENAME TO  PS_BUILDINGS;
ALTER TABLE sources."ECI_SECTION_LIST" RENAME TO  SECTION_LIST;
ALTER TABLE sources."ECI_SUB_DIVISIONS" RENAME TO  SUB_DIVISIONS;
ALTER TABLE sources."ECI_VILLAGES" RENAME TO  VILLAGES;
ALTER TABLE sources."ECI_PS_BUILDING" RENAME TO  PS_BUILDING;
*/






