ALTER TABLE SOURCES.SOURCEELECTORALROLLS ADD COLUMN ISADCVOTER CHARACTER VARYING(1) DEFAULT 'Y' ;
ALTER TABLE SOURCES.SOURCEELECTORALROLLS ADD CONSTRAINT sourceerollscheck1 CHECK (ISADCVOTER::text = ANY (ARRAY['Y'::character varying::text, 'N'::character varying::text]));

ALTER TABLE SOURCES.AC_LIST ADD CONSTRAINT ACLISTPK PRIMARY KEY (ASMBLY_NO);
ALTER TABLE SOURCES.PART_LIST ADD CONSTRAINT PARTLISTPK PRIMARY KEY (ASMBLY_NO, PART_NUMBER);
ALTER TABLE SOURCES.SECTION_LIST ADD CONSTRAINT SECTIONLISTPK PRIMARY KEY (ASMBLY_NO, PART_NO, SECTION_NO);
DELETE FROM SOURCES.SOURCEELECTORALROLLS WHERE ASSEMBLY_CONSTITUENCY_NUMBER IS NULL OR PART_NUMBER IS NULL;
ALTER TABLE SOURCES.SOURCEELECTORALROLLS ADD CONSTRAINT EROLLSPK PRIMARY KEY (ASSEMBLY_CONSTITUENCY_NUMBER, PART_NUMBER,PART_SERIAL_NUMBER);




INSERT INTO MASTERS.DISTRICTS VALUES (13,'AMLAREM','AMLAREM','S', 17, 275,'AML','1 - Shillong (ST) Parliamentary Constituency');
INSERT INTO MASTERS.DISTRICTS VALUES (14,'PYNURSLA','PYNURSLA','S', 17, 275,'PYN','1 - Shillong (ST) Parliamentary Constituency');
INSERT INTO MASTERS.DISTRICTS VALUES (15,'SOHRA','SOHRA','S', 17, 275,'SOH','1 - Shillong (ST) Parliamentary Constituency');
INSERT INTO MASTERS.DISTRICTS VALUES (16,'CHOKPOT','CHOKPOT','S', 17, 275,'CKT','2 - Tura (ST) Parliamentary Constituency');
INSERT INTO MASTERS.DISTRICTS VALUES (17,'RAKSAMGRE','RAKSAMGRE','S', 17, 275,'RAK','2 - Tura (ST) Parliamentary Constituency');
INSERT INTO MASTERS.DISTRICTS VALUES (18,'DADENGGRE','DADENGGRE','S', 17, 275,'DAD','2 - Tura (ST) Parliamentary Constituency');
INSERT INTO MASTERS.DISTRICTS VALUES (19,'MAWSHYNRUT','MAWSHYNRUT','S', 17, 275,'MRT','2 - Tura (ST) Parliamentary Constituency');

ALTER TABLE MASTERS.DISTRICTS ADD COLUMN REFERENCEDISTRICTCODE SMALLINT DEFAULT 1;
ALTER TABLE MASTERS.DISTRICTS ADD COLUMN ECIDISTRICTCODE CHARACTER VARYING(5) NOT NULL DEFAULT 'A';


UPDATE MASTERS.DISTRICTS SET REFERENCEDISTRICTCODE = DISTRICTCODE WHERE DISTRICTSDO = 'D';
UPDATE MASTERS.DISTRICTS SET REFERENCEDISTRICTCODE = 1 WHERE DISTRICTCODE = 13;
UPDATE MASTERS.DISTRICTS SET REFERENCEDISTRICTCODE = 3 WHERE DISTRICTCODE = 14;
UPDATE MASTERS.DISTRICTS SET REFERENCEDISTRICTCODE = 3 WHERE DISTRICTCODE = 15;
UPDATE MASTERS.DISTRICTS SET REFERENCEDISTRICTCODE = 7 WHERE DISTRICTCODE = 16;
UPDATE MASTERS.DISTRICTS SET REFERENCEDISTRICTCODE = 6 WHERE DISTRICTCODE = 17;
UPDATE MASTERS.DISTRICTS SET REFERENCEDISTRICTCODE = 6 WHERE DISTRICTCODE = 18;
UPDATE MASTERS.DISTRICTS SET REFERENCEDISTRICTCODE = 4 WHERE DISTRICTCODE = 19;


UPDATE MASTERS.DISTRICTS SET ECIDISTRICTCODE = 'S1501' WHERE DISTRICTCODE = 1;
UPDATE MASTERS.DISTRICTS SET ECIDISTRICTCODE = 'S1502' WHERE DISTRICTCODE = 2;
UPDATE MASTERS.DISTRICTS SET ECIDISTRICTCODE = 'S1503' WHERE DISTRICTCODE = 3;
UPDATE MASTERS.DISTRICTS SET ECIDISTRICTCODE = 'S1504' WHERE DISTRICTCODE = 4;
UPDATE MASTERS.DISTRICTS SET ECIDISTRICTCODE = 'S1508' WHERE DISTRICTCODE = 8;
UPDATE MASTERS.DISTRICTS SET ECIDISTRICTCODE = 'S1509' WHERE DISTRICTCODE = 9;
UPDATE MASTERS.DISTRICTS SET ECIDISTRICTCODE = 'S1512' WHERE DISTRICTCODE = 12;


ALTER TABLE SOURCES.SOURCEELECTORALROLLS ADD CONSTRAINT srcrolls UNIQUE (ASSEMBLY_CONSTITUENCY_NUMBER, PART_NUMBER, PART_SERIAL_NUMBER);


UPDATE MASTERS.ASSEMBLYCONSTITUENCIES SET ACTYPE='';


--DROP TABLE masters.blocks;
CREATE TABLE masters.blocks
(
  districtcode smallint NOT NULL,
  blockcode smallint NOT NULL,
  blockslno smallint ,
  blockname character varying(255) NOT NULL,
  userid smallint NOT NULL,
  entrydate timestamp without time zone NOT NULL DEFAULT now(),
  CONSTRAINT blockspkey PRIMARY KEY ( blockcode),
  CONSTRAINT blocksukey UNIQUE (blockname),  
  CONSTRAINT blocksfk1 FOREIGN KEY (districtcode)
        REFERENCES masters.districts (districtcode) MATCH SIMPLE
      ON UPDATE CASCADE ON DELETE RESTRICT
)
WITH (
  OIDS=FALSE
);
ALTER TABLE masters.blocks   OWNER TO elections;


INSERT INTO MASTERS.BLOCKS 
SELECT DISTINCT D.SLNO, B.SLNO, BLOCK_MUNICIPAL_NO, BLOCK_MUNICIPAL_NAME, 1, CURRENT_DATE FROM SOURCES.DIST_LIST D INNER JOIN SOURCES.BLOCKS B  ON D.DISTRICT_CD = B.DISTRICT_CD
WHERE B.SLNO NOT IN (25)
;
INSERT INTO MASTERS.BLOCKS  VALUES (1,60,5,'UMROI',1, CURRENT_TIMESTAMP);
INSERT INTO MASTERS.BLOCKS  VALUES (9,61,3,'LANGRIN',1, CURRENT_TIMESTAMP);


CREATE TABLE masters.policestations
(
  districtcode smallint NOT NULL,
  policestationno smallint NOT NULL,
  policestationcode character varying(5) NOT NULL,
  policestationname character varying(255) NOT NULL,
  userid smallint NOT NULL,
  entrydate timestamp without time zone NOT NULL DEFAULT now(),
  CONSTRAINT policestationspkey PRIMARY KEY (policestationcode),
  CONSTRAINT policestationupkey UNIQUE (districtcode, policestationno),
  CONSTRAINT policestationupkey2 UNIQUE (policestationname),
  CONSTRAINT policestationsfk1 FOREIGN KEY (districtcode)
      REFERENCES masters.districts (districtcode) MATCH SIMPLE
      ON UPDATE CASCADE ON DELETE RESTRICT
)
WITH (
  OIDS=FALSE
);
ALTER TABLE MASTERS.policestations   OWNER TO elections;

INSERT INTO MASTERS.POLICESTATIONS 
SELECT D.SLNO, POLICEST_NO, LPAD(PS_ID::TEXT,5,'0'), PSTATION_NAME, 1, CURRENT_TIMESTAMP  FROM SOURCES.DIST_LIST D INNER JOIN SOURCES.POLICE_STATIONS PS ON D.DISTRICT_CD = PS.DISTRICT_CD
WHERE  PS_ID NOT IN ('1002', '12002');

--SELECT * FROM SOURCES.POST_OFFICES;
--DROP TABLE masters.postoffices;

CREATE TABLE masters.postoffices
(
  districtcode smallint NOT NULL,
  postofficeno smallint NOT NULL,
  postofficecode character varying(5) NOT NULL,
  postofficename character varying(255) NOT NULL,
  pincode integer NOT NULL,
  userid smallint NOT NULL,
  entrydate timestamp without time zone NOT NULL DEFAULT now(),

  CONSTRAINT postofficepkey PRIMARY KEY (postofficecode),
  CONSTRAINT postofficeupkey UNIQUE (districtcode, postofficeno),
  CONSTRAINT postofficefk1 FOREIGN KEY (districtcode)
      REFERENCES masters.districts (districtcode) MATCH SIMPLE
      ON UPDATE CASCADE ON DELETE RESTRICT
)
WITH (  OIDS=FALSE
);


ALTER TABLE MASTERS.postoffices OWNER TO elections;
INSERT INTO MASTERS.POSTOFFICES SELECT D.SLNO, POSTOFF_NO, LEFT(POST_OFFICE_ID,5), POST_OFFICE_NAME, PO_PIN, 1, CURRENT_TIMESTAMP FROM SOURCES.DIST_LIST D INNER JOIN SOURCES.POST_OFFICES PO ON D.DISTRICT_CD = PO.DISTRICT_CD;




DROP TABLE IF EXISTS masters.villages;

CREATE TABLE masters.villages(
  vlocationcode character varying(255) NOT NULL,
  districtcode smallint NOT NULL,
  panchayatid character varying(255) ,
  villagename character varying(255) NOT NULL,
  urbanrural character varying(1) NOT NULL,
  userid smallint NOT NULL,
  entrydate timestamp without time zone NOT NULL DEFAULT now(),
  CONSTRAINT villagespkey PRIMARY KEY (vlocationcode),
  CONSTRAINT villagesfk1 FOREIGN KEY (districtcode)
      REFERENCES masters.districts (districtcode) MATCH SIMPLE
      ON UPDATE CASCADE ON DELETE RESTRICT
     
)
WITH (
  OIDS=FALSE
);
ALTER TABLE MASTERS.villages   OWNER TO elections;


INSERT INTO MASTERS.VILLAGES SELECT regexp_replace(VLOCATION, '\W', '', 'g'), D.SLNO, PANCHAYAT_ID, VILLAGE_NAME, VILLAGE_TYPE, 1, CURRENT_TIMESTAMP FROM SOURCES.DIST_LIST D INNER JOIN SOURCES.VILLAGES V ON D.DISTRICT_CD = V.DISTRICT_CD;

INSERT INTO MASTERS.VILLAGES 
SELECT TOWN_NAME|| 'U' AS VLOCATIONCODE, CASE WHEN TRIM(UPPER(TOWN_NAME)) = 'CHERRAPUNJEE' THEN 15 ELSE D.SLNO END AS SLNO, NULL AS PANCHAYATID, TOWN_NAME,'U',1,CURRENT_TIMESTAMP FROM SOURCES.DIST_LIST D INNER JOIN SOURCES.NNN  N ON D.DISTRICT_CD = N.DISTRICT_CD
ORDER BY D.DISTRICT_CD;

--INSERT INTO MASTERS.VILLAGES VALUES ('X',12,'X','NOT AVAILABLE','R',1,CURRENT_TIMESTAMP);
--INSERT INTO MASTERS.VILLAGES VALUES ('801890193',12,'X','NOT AVAILABLE','R',1,CURRENT_TIMESTAMP);


--------------------------------------------------------------------------------------------------

--INSERT INTO MASTERS.ASSEMBLYCONSTITUENCIES SELECT D.SLNO, ASMBLY_NO, ASMBLY_NAME, CATEGORY, 1 FROM SOURCES.DIST_LIST D INNER JOIN SOURCES.AC_LIST AC ON D.DISTRICT_CD = AC.DISTRICT_CD;

SELECT * FROM MASTERS.ASSEMBLYCONSTITUENCIES ;

CREATE TABLE SOURCES.officesacs
(
  officecode character varying(6) NOT NULL,
  acno smallint NOT NULL,
  CONSTRAINT officesacspkey PRIMARY KEY (officecode, acno),
  CONSTRAINT officesacsfkey1 FOREIGN KEY (officecode)
      REFERENCES masters.offices (officecode) MATCH SIMPLE
      ON UPDATE CASCADE ON DELETE RESTRICT,
  CONSTRAINT officesacsfkey2 FOREIGN KEY (acno)
      REFERENCES masters.assemblyconstituencies (acno) MATCH SIMPLE
      ON UPDATE CASCADE ON DELETE RESTRICT
)
WITH (
  OIDS=FALSE
);
ALTER TABLE SOURCES.officesacs
  OWNER TO elections;

INSERT INTO SOURCES.OFFICESACS SELECT * FROM MASTERS.OFFICESACS;


ALTER TABLE MASTERS.ACPARTS DROP COLUMN fvttype ;
ALTER TABLE MASTERS.ACPARTS DROP COLUMN psbuildingsid ;
ALTER TABLE MASTERS.ACPARTS DROP COLUMN partvotercapacity ;
ALTER TABLE MASTERS.ACPARTS DROP COLUMN villagesinpart ;
ALTER TABLE MASTERS.ACPARTS DROP COLUMN mainvillage ;
ALTER TABLE MASTERS.ACPARTS DROP COLUMN sensitivitycode ;
ALTER TABLE MASTERS.ACPARTS DROP COLUMN motorabledistance ;
ALTER TABLE MASTERS.ACPARTS DROP COLUMN nonmotorabledistance ;
ALTER TABLE MASTERS.ACPARTS DROP COLUMN patwarino ;
ALTER TABLE MASTERS.ACPARTS DROP COLUMN tahsilno ;
ALTER TABLE MASTERS.ACPARTS DROP COLUMN rino ;



ALTER TABLE MASTERS.ACPARTS DROP CONSTRAINT personnelfkacparts ;


ALTER TABLE MASTERS.ACPARTS  ADD COLUMN partlocationcategory character varying(1) NOT NULL DEFAULT 'R';
ALTER TABLE MASTERS.ACPARTS  ADD COLUMN latitude double precision ;
ALTER TABLE MASTERS.ACPARTS  ADD COLUMN longitude double precision ;
ALTER TABLE MASTERS.ACPARTS  ADD COLUMN blockcode smallint NOT NULL;
ALTER TABLE MASTERS.ACPARTS  ADD COLUMN pincodex integer NOT NULL ;
ALTER TABLE MASTERS.ACPARTS  ADD COLUMN postofficecode character varying(255) NOT NULL ;
ALTER TABLE MASTERS.ACPARTS  ADD COLUMN policestationcode character varying(255) NOT NULL ;
ALTER TABLE MASTERS.ACPARTS  ADD COLUMN psbuildingid CHARACTER VARYING(255) NOT NULL;
ALTER TABLE MASTERS.ACPARTS  ADD COLUMN mainvillagecode CHARACTER VARYING(255) NOT NULL  ;
ALTER TABLE MASTERS.ACPARTS  ADD COLUMN fvttype CHARACTER VARYING(1)   NOT NULL;
ALTER TABLE MASTERS.ACPARTS  ADD COLUMN partgendertype CHARACTER VARYING(7)   NOT NULL;
ALTER TABLE MASTERS.ACPARTS ADD COLUMN  userid smallint NOT NULL;
ALTER TABLE MASTERS.ACPARTS ADD COLUMN  entrydate timestamp without time zone NOT NULL DEFAULT now();


ALTER TABLE MASTERS.ACPARTS ADD CONSTRAINT acpartscheckfvt CHECK (fvttype::text = ANY (ARRAY['V'::character varying::text, 'T'::character varying::text]));
ALTER TABLE MASTERS.ACPARTS ADD CONSTRAINT acpartscheckpartgender CHECK (partgendertype::text = ANY (ARRAY['MALE'::character varying::text, 'FEMALE'::character varying::text,'GENERAL'::character varying::text]));
ALTER TABLE MASTERS.ACPARTS ADD CONSTRAINT acpartsfk4 FOREIGN KEY (postofficecode) REFERENCES masters.postoffices (postofficecode) MATCH SIMPLE ON UPDATE CASCADE ON DELETE RESTRICT;
ALTER TABLE MASTERS.ACPARTS ADD CONSTRAINT acpartsfk5 FOREIGN KEY (policestationcode) REFERENCES masters.policestations (policestationcode) MATCH SIMPLE ON UPDATE CASCADE ON DELETE RESTRICT;
ALTER TABLE MASTERS.ACPARTS ADD CONSTRAINT acpartsfk6 FOREIGN KEY (mainvillagecode) REFERENCES masters.villages (vlocationcode) MATCH SIMPLE ON UPDATE CASCADE ON DELETE RESTRICT;
ALTER TABLE MASTERS.ACPARTS ADD CONSTRAINT acpartsfk7 FOREIGN KEY (blockcode) REFERENCES masters.blocks (blockcode) MATCH SIMPLE ON UPDATE CASCADE ON DELETE RESTRICT;


ALTER TABLE MASTERS.POLLINGSTATIONS DROP COLUMN psslno;
ALTER TABLE MASTERS.POLLINGSTATIONS DROP COLUMN psloctype;
ALTER TABLE MASTERS.POLLINGSTATIONS DROP COLUMN PSGENDERTYPE ;
ALTER TABLE MASTERS.POLLINGSTATIONS DROP COLUMN pslocationsectionid ;
ALTER TABLE MASTERS.POLLINGSTATIONS ADD COLUMN  userid smallint NOT NULL;
ALTER TABLE MASTERS.POLLINGSTATIONS ADD COLUMN  entrydate timestamp without time zone NOT NULL DEFAULT now();
ALTER TABLE MASTERS.POLLINGSTATIONS ALTER COLUMN psbuildingid TYPE CHARACTER VARYING(255) ;


ALTER TABLE MASTERS.POLLINGSTATIONS DROP CONSTRAINT psfk1 ;
ALTER TABLE MASTERS.POLLINGSTATIONS DROP CONSTRAINT psfk2 ;

INSERT INTO MASTERS.POLLINGSTATIONS 
SELECT AC.ASMBLY_NO, AP.PART_NUMBER,PSBUILDING_NO,  PSB.PSBUILDING_NAME, BUILDING_ADDRESS, regexp_replace(PSB.PSBUILDING_ID, '\W', '', 'g'), PSB.PSBUILDING_NAME, 1,  1, CURRENT_TIMESTAMP
FROM SOURCES.AC_LIST  AC INNER JOIN SOURCES.PART_LIST AP ON AC.ASMBLY_NO = LEFT(AP.ASMBLY_NO, 2)::SMALLINT
INNER JOIN SOURCES.PS_BUILDINGS PSB ON (LEFT(AP.ASMBLY_NO, 2)::SMALLINT = LEFT(AP.ASMBLY_NO, 2)::SMALLINT AND AP.psbuilding_id = PSB.PSBUILDING_ID);

UPDATE MASTERS.POLLINGSTATIONS SET PSADDRESS = PSBUILDINGNAME;

CREATE TABLE masters.sections
(
  acno smallint NOT NULL,
  partno smallint NOT NULL,
  sectionno smallint NOT NULL,
  sectionname character varying(255) NOT NULL,
  vlocationcode character varying(255) ,
  pincodex integer NOT NULL ,
  userid smallint NOT NULL,
  entrydate timestamp without time zone NOT NULL DEFAULT now(),
  CONSTRAINT sectionspkey PRIMARY KEY (acno, partno, sectionno),
  CONSTRAINT sectionsfk1 FOREIGN KEY (acno)
      REFERENCES masters.assemblyconstituencies (acno) MATCH SIMPLE
      ON UPDATE CASCADE ON DELETE RESTRICT,
  CONSTRAINT sectionsfk2 FOREIGN KEY (acno, partno)
      REFERENCES masters.acparts (acno, partno) MATCH SIMPLE
      ON UPDATE CASCADE ON DELETE RESTRICT
)
WITH (
  OIDS=FALSE
);
ALTER TABLE masters.sections
  OWNER TO elections;


--INSERT INTO MASTERS.SECTIONS SELECT ASMBLY_NO, PART_NO, SECTION_NO, SECTION_NAME, regexp_replace(VLOCATION, '\W', '', 'g'), PIN_CODE, 1, CURRENT_TIMESTAMP FROM SOURCES.SECTION_LIST



CREATE TABLE masters.electoralrollrevisions
(
  revisionno smallint NOT NULL,
  revisiondescription character varying(255) NOT NULL,
  revisionyear smallint NOT NULL,
  qualifyingdate date NOT NULL,
  revisiontype character varying(50) NOT NULL,
  publicationdate date NOT NULL,
  userid smallint NOT NULL,
  entrydate timestamp without time zone NOT NULL DEFAULT now(),
  CONSTRAINT electoralrollrevisionspkey PRIMARY KEY (revisionno),
  CONSTRAINT electoralrollrevisionsukey1 UNIQUE (revisiondescription),  
  CONSTRAINT electoralrollrevisionsukey2 UNIQUE (qualifyingdate)  

)
WITH (
  OIDS=FALSE
);
ALTER TABLE masters.electoralrollrevisions   OWNER TO elections;
INSERT INTO masters.electoralrollrevisions VALUES (0, 'Basic Roll of Summary Revision', 2025, '2025-01-01', 'Summary Revision', '2025-01-13',1, CURRENT_TIMESTAMP);

