DELETE FROM MASTERS.OFFICESACS  WHERE ACNO >29;
DELETE FROM MASTERS.ASSEMBLYCONSTITUENCIES  WHERE ACNO >29;

 UPDATE MASTERS.ASSEMBLYCONSTITUENCIES SET ACNAME = 'War East' WHERE ACNO = 1;
 UPDATE MASTERS.ASSEMBLYCONSTITUENCIES SET ACNAME = 'War Central' WHERE ACNO = 2;
 UPDATE MASTERS.ASSEMBLYCONSTITUENCIES SET ACNAME = 'War West' WHERE ACNO = 3;
 UPDATE MASTERS.ASSEMBLYCONSTITUENCIES SET ACNAME = 'Sohmynting Khliehtyrshi' WHERE ACNO = 4;
 UPDATE MASTERS.ASSEMBLYCONSTITUENCIES SET ACNAME = 'Mukhla Wahiajer' WHERE ACNO = 5;
 UPDATE MASTERS.ASSEMBLYCONSTITUENCIES SET ACNAME = 'Ummulong Moodymmai' WHERE ACNO = 6;
 UPDATE MASTERS.ASSEMBLYCONSTITUENCIES SET ACNAME = 'Nongbah' WHERE ACNO = 7;
 UPDATE MASTERS.ASSEMBLYCONSTITUENCIES SET ACNAME = 'Nartiang Umladang' WHERE ACNO = 8;
 UPDATE MASTERS.ASSEMBLYCONSTITUENCIES SET ACNAME = 'Nongjngi' WHERE ACNO = 9;
 UPDATE MASTERS.ASSEMBLYCONSTITUENCIES SET ACNAME = 'Mynsngat Khanduli' WHERE ACNO = 10;
 UPDATE MASTERS.ASSEMBLYCONSTITUENCIES SET ACNAME = 'Shilliang Myntang' WHERE ACNO = 11;
 UPDATE MASTERS.ASSEMBLYCONSTITUENCIES SET ACNAME = 'Barato Mukroh' WHERE ACNO = 12;
 UPDATE MASTERS.ASSEMBLYCONSTITUENCIES SET ACNAME = 'Saphai' WHERE ACNO = 13;
 UPDATE MASTERS.ASSEMBLYCONSTITUENCIES SET ACNAME = 'Mowkaiaw' WHERE ACNO = 14;
 UPDATE MASTERS.ASSEMBLYCONSTITUENCIES SET ACNAME = 'Raliang' WHERE ACNO = 15;
 UPDATE MASTERS.ASSEMBLYCONSTITUENCIES SET ACNAME = 'Shangpung' WHERE ACNO = 16;
 UPDATE MASTERS.ASSEMBLYCONSTITUENCIES SET ACNAME = 'Jowai North' WHERE ACNO = 17;
 UPDATE MASTERS.ASSEMBLYCONSTITUENCIES SET ACNAME = 'Jowai Central' WHERE ACNO = 18;
 UPDATE MASTERS.ASSEMBLYCONSTITUENCIES SET ACNAME = 'Jowai South' WHERE ACNO = 19;
 UPDATE MASTERS.ASSEMBLYCONSTITUENCIES SET ACNAME = 'Muthlong Sohkymphor' WHERE ACNO = 20;
 UPDATE MASTERS.ASSEMBLYCONSTITUENCIES SET ACNAME = 'Tubber' WHERE ACNO = 21;
 UPDATE MASTERS.ASSEMBLYCONSTITUENCIES SET ACNAME = 'Musniang Rngat' WHERE ACNO = 22;
 UPDATE MASTERS.ASSEMBLYCONSTITUENCIES SET ACNAME = 'Rymbai Khliehriat' WHERE ACNO = 23;
 UPDATE MASTERS.ASSEMBLYCONSTITUENCIES SET ACNAME = 'Sutnga Narwan' WHERE ACNO = 24;
 UPDATE MASTERS.ASSEMBLYCONSTITUENCIES SET ACNAME = 'Sutnga Nongkhlieh' WHERE ACNO = 25;
 UPDATE MASTERS.ASSEMBLYCONSTITUENCIES SET ACNAME = 'Sumer' WHERE ACNO = 26;
 UPDATE MASTERS.ASSEMBLYCONSTITUENCIES SET ACNAME = 'Saipung' WHERE ACNO = 27;
 UPDATE MASTERS.ASSEMBLYCONSTITUENCIES SET ACNAME = 'Narpuh' WHERE ACNO = 28;
 UPDATE MASTERS.ASSEMBLYCONSTITUENCIES SET ACNAME = 'Bataw Lakadong' WHERE ACNO = 29;














