DELETE FROM MASTERS.OFFICESACS  WHERE ACNO >29;
DELETE FROM MASTERS.ASSEMBLYCONSTITUENCIES  WHERE ACNO >29;

UPDATE MASTERS.ASSEMBLYCONSTITUENCIES SET ACNAME = 'Jirang' WHERE ACNO = 1;
UPDATE MASTERS.ASSEMBLYCONSTITUENCIES SET ACNAME = 'Nongpoh' WHERE ACNO = 2;
UPDATE MASTERS.ASSEMBLYCONSTITUENCIES SET ACNAME = 'Mawhati' WHERE ACNO = 3;
UPDATE MASTERS.ASSEMBLYCONSTITUENCIES SET ACNAME = 'Umsning' WHERE ACNO = 4;
UPDATE MASTERS.ASSEMBLYCONSTITUENCIES SET ACNAME = 'Umroi' WHERE ACNO = 5;
UPDATE MASTERS.ASSEMBLYCONSTITUENCIES SET ACNAME = 'Sohryngkham' WHERE ACNO = 6;
UPDATE MASTERS.ASSEMBLYCONSTITUENCIES SET ACNAME = 'Mawkynrew' WHERE ACNO = 7;
UPDATE MASTERS.ASSEMBLYCONSTITUENCIES SET ACNAME = 'Nongkrem' WHERE ACNO = 8;
UPDATE MASTERS.ASSEMBLYCONSTITUENCIES SET ACNAME = 'Lyngkyrdem Laitkroh' WHERE ACNO = 9;
UPDATE MASTERS.ASSEMBLYCONSTITUENCIES SET ACNAME = 'Nongshken' WHERE ACNO = 10;
UPDATE MASTERS.ASSEMBLYCONSTITUENCIES SET ACNAME = 'Shella' WHERE ACNO = 11;
UPDATE MASTERS.ASSEMBLYCONSTITUENCIES SET ACNAME = 'Mawsynram' WHERE ACNO = 12;
UPDATE MASTERS.ASSEMBLYCONSTITUENCIES SET ACNAME = 'Sohra' WHERE ACNO = 13;
UPDATE MASTERS.ASSEMBLYCONSTITUENCIES SET ACNAME = 'Mylliem' WHERE ACNO = 14;
UPDATE MASTERS.ASSEMBLYCONSTITUENCIES SET ACNAME = 'Laban Mawprem' WHERE ACNO = 15;
UPDATE MASTERS.ASSEMBLYCONSTITUENCIES SET ACNAME = 'Nongthymmai' WHERE ACNO = 16;
UPDATE MASTERS.ASSEMBLYCONSTITUENCIES SET ACNAME = 'Laitumkhrah Malki' WHERE ACNO = 17;
UPDATE MASTERS.ASSEMBLYCONSTITUENCIES SET ACNAME = 'Mawkhar Pynthorumkhrah' WHERE ACNO = 18;
UPDATE MASTERS.ASSEMBLYCONSTITUENCIES SET ACNAME = 'Jaiaw' WHERE ACNO = 19;
UPDATE MASTERS.ASSEMBLYCONSTITUENCIES SET ACNAME = 'Mawlai' WHERE ACNO = 20;
UPDATE MASTERS.ASSEMBLYCONSTITUENCIES SET ACNAME = 'Mawphlang Diengiei' WHERE ACNO = 21;
UPDATE MASTERS.ASSEMBLYCONSTITUENCIES SET ACNAME = 'Nongspung Sohiong' WHERE ACNO = 22;
UPDATE MASTERS.ASSEMBLYCONSTITUENCIES SET ACNAME = 'Mairang Nongkhlaw' WHERE ACNO = 23;
UPDATE MASTERS.ASSEMBLYCONSTITUENCIES SET ACNAME = 'Pariong Mawthadraishan' WHERE ACNO = 24;
UPDATE MASTERS.ASSEMBLYCONSTITUENCIES SET ACNAME = 'Mawkyrwat' WHERE ACNO = 25;
UPDATE MASTERS.ASSEMBLYCONSTITUENCIES SET ACNAME = 'Langrin' WHERE ACNO = 26;
UPDATE MASTERS.ASSEMBLYCONSTITUENCIES SET ACNAME = 'Nongstoin' WHERE ACNO = 27;
UPDATE MASTERS.ASSEMBLYCONSTITUENCIES SET ACNAME = 'Rambrai Jyrngam' WHERE ACNO = 28;
UPDATE MASTERS.ASSEMBLYCONSTITUENCIES SET ACNAME = 'Mawshynrut' WHERE ACNO = 29;

UPDATE MASTERS.OFFICESACS SET OFFICECODE = '020001' WHERE ACNO IN (1, 2, 3, 4, 5);
UPDATE MASTERS.OFFICESACS SET OFFICECODE = '030001' WHERE ACNO IN (6,7,8,9,10,12,14,15,16,17,18,19,20,21,22);
UPDATE MASTERS.OFFICESACS SET OFFICECODE = '120001' WHERE ACNO IN (23,24);
UPDATE MASTERS.OFFICESACS SET OFFICECODE = '090001' WHERE ACNO IN (25,26);
UPDATE MASTERS.OFFICESACS SET OFFICECODE = '040001' WHERE ACNO IN (27, 28 , 29 );
UPDATE MASTERS.OFFICESACS SET OFFICECODE = '030003' WHERE ACNO IN (11,13 );








