--DELETE FROM MASTERS.SECTIONS;
--DELETE FROM MASTERS.ACPARTS;

ALTER TABLE ELECTIONS.AMLACPARTS SET SCHEMA IMPORTS;
ALTER TABLE ELECTIONS.AMLSECTIONS SET SCHEMA IMPORTS;
ALTER TABLE ELECTIONS.AMLBLOCKS SET SCHEMA IMPORTS;

ALTER TABLE IMPORTS.AMLACPARTS ADD COLUMN BLOCKCODE SMALLINT;


SELECT 'UPDATE IMPORTS.AMLACPARTS SET BLOCKCODE = ' || BLOCKCODE || ' WHERE ACNO = ' || ACNO || ' AND PARTNO = ' || PARTNO || ';' 
FROM MASTERS.BLOCKS B INNER JOIN IMPORTS.AMLBLOCKS D ON TRIM(UPPER(B.BLOCKNAME)) = TRIM(UPPER(D.BLOCKNAME)) 

INSERT INTO MASTERS.ACPARTS
SELECT ACNO, PARTNO, PARTNAME, PARTLOCATIONCATEGORY, LATITUDE, LONGITUDE, BLOCKCODE, PINCODEX, LEFT(POSTOFFICECODE,5) , LEFT(POLICESTATIONCODE,5), regexp_replace(PSBUILDINGID, '\W', '', 'g'), regexp_replace(MAINVILLAGECODE, '\W', '', 'g'), FVTTYPE, PARTGENDERTYPE, 1, CURRENT_TIMESTAMP FROM IMPORTS.AMLACPARTS
ORDER BY ACNO, PARTNO;


SELECT * FROM MASTERS.ACPARTS WHERE PSBUILDINGID NOT IN (SELECT PSBUILDINGID FROM MASTERS.POLLINGSTATIONS);

SELECT * FROM MASTERS.ACPARTS WHERE MAINVILLAGECODE NOT IN (SELECT VLOCATIONCODE FROM MASTERS.VILLAGES);

-- POPULATE THE PS WHICH ARE NOT AVAILAABLE IN THE MASTER POLLING STATIONS
INSERT INTO MASTERS.POLLINGSTATIONS SELECT ACNO, PARTNO, 1, 'N.A.', 'N.A.', PSBUILDINGID, 'N.A.', 1,1,CURRENT_TIMESTAMP FROM MASTERS.ACPARTS WHERE PSBUILDINGID NOT IN (SELECT PSBUILDINGID FROM MASTERS.POLLINGSTATIONS);
UPDATE IMPORTS.AMLACPARTS SET MAINVILLAGECODE = (SELECT VLOCATIONCODE FROM MASTERS.VILLAGES WHERE VILLAGENAME = 'JOWAI' ) WHERE FVTTYPE = 'T';

INSERT INTO MASTERS.SECTIONS SELECT ACNO, PARTNO, SECTIONNO, SECTIONNAME, regexp_replace(VLOCATIONCODE, '\W', '', 'g'), PINCODEX, 1, CURRENT_TIMESTAMP FROM IMPORTS.AMLSECTIONS;

SELECT * FROM MASTERS.SECTIONS WHERE VLOCATIONCODE NOT IN (SELECT VLOCATIONCODE FROM MASTERS.VILLAGES);


