--DELETE FROM ELECTORALROLLS
--DELETE FROM ELECTORALROLLSTEMP
--DELETE FROM MASTERS.SECTIONS;
--DELETE FROM MASTERS.ACPARTS;

ALTER TABLE ELECTIONS.EJHACPARTS SET SCHEMA IMPORTS;
ALTER TABLE ELECTIONS.EJHSECTIONS SET SCHEMA IMPORTS;
ALTER TABLE ELECTIONS.EJHBLOCKS SET SCHEMA IMPORTS;

ALTER TABLE IMPORTS.EJHACPARTS ADD COLUMN BLOCKCODE SMALLINT;



SELECT 'UPDATE IMPORTS.EJHACPARTS SET BLOCKCODE = ' || BLOCKCODE || ' WHERE ACNO = ' || ACNO || ' AND PARTNO = ' || PARTNO || ';' 
FROM MASTERS.BLOCKS B INNER JOIN IMPORTS.EJHBLOCKS D ON TRIM(UPPER(B.BLOCKNAME)) = TRIM(UPPER(D.BLOCKNAME)) 



INSERT INTO MASTERS.ACPARTS
SELECT ACNO, PARTNO, PARTNAME, PARTLOCATIONCATEGORY, LATITUDE, LONGITUDE, BLOCKCODE, PINCODEX, LEFT(POSTOFFICECODE,5) , LEFT(POLICESTATIONCODE,5), regexp_replace(PSBUILDINGID, '\W', '', 'g'), regexp_replace(MAINVILLAGECODE, '\W', '', 'g'), FVTTYPE, PARTGENDERTYPE, 1, CURRENT_TIMESTAMP FROM IMPORTS.EJHACPARTS
ORDER BY ACNO, PARTNO;


SELECT * FROM MASTERS.ACPARTS WHERE PSBUILDINGID NOT IN (SELECT PSBUILDINGID FROM MASTERS.POLLINGSTATIONS);
SELECT * FROM MASTERS.ACPARTS WHERE MAINVILLAGECODE NOT IN (SELECT VLOCATIONCODE FROM MASTERS.VILLAGES);

INSERT INTO MASTERS.SECTIONS SELECT ACNO, PARTNO, SECTIONNO, SECTIONNAME, regexp_replace(VLOCATIONCODE, '\W', '', 'g'), PINCODEX, 1, CURRENT_TIMESTAMP FROM IMPORTS.EJHSECTIONS;

SELECT * FROM MASTERS.SECTIONS WHERE VLOCATIONCODE NOT IN (SELECT VLOCATIONCODE FROM MASTERS.VILLAGES);
