--DELETE FROM MASTERS.SECTIONS;
--DELETE FROM MASTERS.ACPARTS;

ALTER TABLE ELECTIONS.EWKHACPARTS SET SCHEMA IMPORTS;
ALTER TABLE ELECTIONS.EWKHSECTIONS SET SCHEMA IMPORTS;
ALTER TABLE ELECTIONS.EWKHBLOCKS SET SCHEMA IMPORTS;

ALTER TABLE IMPORTS.EWKHACPARTS ADD COLUMN BLOCKCODE SMALLINT;

SELECT 'UPDATE IMPORTS.EWKHACPARTS SET BLOCKCODE = ' || BLOCKCODE || ' WHERE ACNO = ' || ACNO || ' AND PARTNO = ' || PARTNO || ';' FROM MASTERS.BLOCKS B INNER JOIN IMPORTS.EWKHBLOCKS D ON TRIM(UPPER(B.BLOCKNAME)) = TRIM(UPPER(D.BLOCKNAME)) ;


INSERT INTO MASTERS.ACPARTS
SELECT ACNO, PARTNO, PARTNAME, PARTLOCATIONCATEGORY, LATITUDE, LONGITUDE, BLOCKCODE, PINCODEX, LEFT(POSTOFFICECODE,5) , LEFT(POLICESTATIONCODE,5), regexp_replace(PSBUILDINGID, '\W', '', 'g'), regexp_replace(MAINVILLAGECODE, '\W', '', 'g'), FVTTYPE, PARTGENDERTYPE, 1, CURRENT_TIMESTAMP FROM IMPORTS.EWKHACPARTS;


INSERT INTO MASTERS.SECTIONS SELECT ACNO, PARTNO, SECTIONNO, SECTIONNAME, regexp_replace(VLOCATIONCODE, '\W', '', 'g'), PINCODEX, 1, CURRENT_TIMESTAMP FROM IMPORTS.EWKHSECTIONS;


SELECT * FROM IMPORTS.EWKHSECTIONS WHERE regexp_replace(VLOCATIONCODE, '\W', '', 'g') NOT IN (SELECT VLOCATIONCODE FROM MASTERS.VILLAGES);
SELECT * FROM MASTERS.SECTIONS WHERE VLOCATIONCODE NOT IN (SELECT VLOCATIONCODE FROM MASTERS.VILLAGES);










