--DELETE FROM ELECTORALROLLS
--DELETE FROM ELECTORALROLLSTEMP
--DELETE FROM MASTERS.SECTIONS;
--DELETE FROM MASTERS.ACPARTS;

ALTER TABLE ELECTIONS.EKHACPARTS SET SCHEMA IMPORTS;
ALTER TABLE ELECTIONS.EKHSECTIONS SET SCHEMA IMPORTS;
ALTER TABLE ELECTIONS.EKHBLOCKS SET SCHEMA IMPORTS;

ALTER TABLE IMPORTS.EKHACPARTS ADD COLUMN BLOCKCODE SMALLINT;



SELECT 'UPDATE IMPORTS.EKHACPARTS SET BLOCKCODE = ' || BLOCKCODE || ' WHERE ACNO = ' || ACNO || ' AND PARTNO = ' || PARTNO || ';' 
FROM MASTERS.BLOCKS B INNER JOIN IMPORTS.EKHBLOCKS D ON TRIM(UPPER(B.BLOCKNAME)) = TRIM(UPPER(D.BLOCKNAME)) ;


UPDATE IMPORTS.EKHACPARTS SET MAINVILLAGECODE ='SHILLONGU' WHERE MAINVILLAGECODE = '0300000000000001U';
UPDATE IMPORTS.EKHSECTIONS SET VLOCATIONCODE ='SHILLONGU' WHERE VLOCATIONCODE  LIKE '%U%';


DELETE FROM IMPORTS.EKHACPARTS WHERE ACNO >30;

UPDATE IMPORTS.EKHACPARTS SET POSTOFFICECODE = REPLACE(POSTOFFICECODE, '`', '');

SELECT * FROM IMPORTS.EKHACPARTS WHERE LEFT(REPLACE(POSTOFFICECODE, '`', ''),5) NOT IN (SELECT POSTOFFICECODE FROM MASTERS.POSTOFFICES);
SELECT * FROM IMPORTS.EKHACPARTS WHERE LEFT(POLICESTATIONCODE,5) NOT IN (SELECT POLICESTATIONCODE FROM MASTERS.POLICESTATIONS);
SELECT * FROM IMPORTS.EKHACPARTS WHERE regexp_replace(MAINVILLAGECODE, '\W', '', 'g') NOT IN (SELECT VLOCATIONCODE FROM MASTERS.VILLAGES);

INSERT INTO MASTERS.ACPARTS
SELECT ACNO, PARTNO, PARTNAME, PARTLOCATIONCATEGORY, LATITUDE, LONGITUDE, BLOCKCODE, PINCODEX, LEFT(POSTOFFICECODE,5) , LEFT(POLICESTATIONCODE,5), regexp_replace(PSBUILDINGID, '\W', '', 'g'), regexp_replace(MAINVILLAGECODE, '\W', '', 'g'), FVTTYPE, PARTGENDERTYPE, 1, CURRENT_TIMESTAMP FROM IMPORTS.EKHACPARTS
ORDER BY ACNO, PARTNO;


SELECT * FROM MASTERS.ACPARTS WHERE PSBUILDINGID NOT IN (SELECT PSBUILDINGID FROM MASTERS.POLLINGSTATIONS);
SELECT * FROM MASTERS.ACPARTS WHERE MAINVILLAGECODE NOT IN (SELECT VLOCATIONCODE FROM MASTERS.VILLAGES);

INSERT INTO MASTERS.SECTIONS SELECT ACNO, PARTNO, SECTIONNO, SECTIONNAME, regexp_replace(VLOCATIONCODE, '\W', '', 'g'), PINCODEX, 1, CURRENT_TIMESTAMP FROM IMPORTS.EKHSECTIONS;

SELECT * FROM MASTERS.SECTIONS WHERE VLOCATIONCODE NOT IN (SELECT VLOCATIONCODE FROM MASTERS.VILLAGES);
