--DELETE FROM ELECTORALROLLS
--DELETE FROM ELECTORALROLLSTEMP
--DELETE FROM MASTERS.SECTIONS;
--DELETE FROM MASTERS.ACPARTS;

ALTER TABLE ELECTIONS.MKTACPARTS SET SCHEMA IMPORTS;
ALTER TABLE ELECTIONS.MKTSECTIONS SET SCHEMA IMPORTS;
ALTER TABLE ELECTIONS.MKTBLOCKS SET SCHEMA IMPORTS;

ALTER TABLE IMPORTS.MKTACPARTS ADD COLUMN BLOCKCODE SMALLINT;

UPDATE IMPORTS.MKTACPARTS SET BLOCKCODE = (SELECT BLOCKCODE FROM MASTERS.BLOCKS WHERE TRIM(UPPER(BLOCKNAME)) ='MAWKYRWAT') WHERE ACNO = 25;
UPDATE IMPORTS.MKTACPARTS  SET BLOCKCODE = (SELECT BLOCKCODE FROM MASTERS.BLOCKS WHERE TRIM(UPPER(BLOCKNAME)) ='LANGRIN') WHERE ACNO = 26;

DELETE FROM IMPORTS.MKTACPARTS WHERE ACNO IS NULL;


INSERT INTO MASTERS.ACPARTS
SELECT ACNO, PARTNO, PARTNAME, PARTLOCATIONCATEGORY, LATITUDE, LONGITUDE, BLOCKCODE, PINCODEX, LEFT(POSTOFFICECODE,5) , LEFT(POLICESTATIONCODE,5), regexp_replace(PSBUILDINGID, '\W', '', 'g'), regexp_replace(MAINVILLAGECODE, '\W', '', 'g'), FVTTYPE, PARTGENDERTYPE, 1, CURRENT_TIMESTAMP FROM IMPORTS.MKTACPARTS
ORDER BY ACNO, PARTNO;


SELECT * FROM MASTERS.ACPARTS WHERE PSBUILDINGID NOT IN (SELECT PSBUILDINGID FROM MASTERS.POLLINGSTATIONS);

SELECT * FROM MASTERS.ACPARTS WHERE MAINVILLAGECODE NOT IN (SELECT VLOCATIONCODE FROM MASTERS.VILLAGES);

SELECT ACNO, PARTNO, SECTIONNO, COUNT(*) FROM IMPORTS.MKTSECTIONS GROUP BY ACNO, PARTNO, SECTIONNO HAVING COUNT(*) > 1;

INSERT INTO MASTERS.SECTIONS SELECT ACNO, PARTNO, SECTIONNO, SECTIONNAME, regexp_replace(VLOCATIONCODE, '\W', '', 'g'), PINCODEX, 1, CURRENT_TIMESTAMP FROM IMPORTS.MKTSECTIONS;

SELECT * FROM MASTERS.SECTIONS WHERE VLOCATIONCODE NOT IN (SELECT VLOCATIONCODE FROM MASTERS.VILLAGES);
