-- DROP CONSTRAINTS
ALTER TABLE MASTERS.ACPARTS  ALTER COLUMN BLOCKCODE DROP NOT NULL;
ALTER TABLE MASTERS.ACPARTS  ALTER COLUMN MAINVILLAGECODE DROP NOT  NULL;
ALTER TABLE MASTERS.ACPARTS DROP CONSTRAINT acpartsfk6 ;
ALTER TABLE MASTERS.ACPARTS DROP CONSTRAINT acpartsfk7 ;


ALTER TABLE MASTERS.POLLINGSTATIONS DROP CONSTRAINT psfk1 ;
ALTER TABLE MASTERS.POLLINGSTATIONS DROP CONSTRAINT psfk2 ;



---ADD CONSTRAINTS

ALTER TABLE MASTERS.ACPARTS  ALTER COLUMN BLOCKCODE SET NOT NULL;
ALTER TABLE MASTERS.ACPARTS ADD CONSTRAINT acpartsfk7 FOREIGN KEY (blockcode) REFERENCES masters.blocks (blockcode) MATCH SIMPLE ON UPDATE CASCADE ON DELETE RESTRICT;


ALTER TABLE MASTERS.ACPARTS  ALTER COLUMN MAINVILLAGECODE SET NOT NULL;
ALTER TABLE MASTERS.ACPARTS ADD CONSTRAINT acpartsfk6 FOREIGN KEY (mainvillagecode) REFERENCES masters.villages (vlocationcode) MATCH SIMPLE ON UPDATE CASCADE ON DELETE RESTRICT;




ALTER TABLE MASTERS.SECTIONS  ADD CONSTRAINT sectionsfk3 FOREIGN KEY (vlocationcode) REFERENCES masters.villages (vlocationcode) MATCH SIMPLE ON UPDATE CASCADE ON DELETE RESTRICT;



ALTER TABLE MASTERS.POLLINGSTATIONS ADD CONSTRAINT psfk1 FOREIGN KEY (acno)     REFERENCES masters.assemblyconstituencies (acno) MATCH SIMPLE       ON UPDATE CASCADE ON DELETE RESTRICT;
ALTER TABLE MASTERS.POLLINGSTATIONS ADD CONSTRAINT psfk2 FOREIGN KEY (acno, partno)  REFERENCES masters.acparts (acno, partno) MATCH SIMPLE     ON UPDATE CASCADE ON DELETE RESTRICT;

*/


SELECT * FROM IMPORTS.WJHBLOCKS WHERE TRIM(UPPER(BLOCKNAME))  IN (SELECT TRIM(UPPER(BLOCKNAME)) FROM MASTERS.BLOCKS);


SELECT * FROM MASTERS.BLOCKS B INNER JOIN IMPORTS.WJHBLOCKS D ON TRIM(UPPER(B.BLOCKNAME)) = TRIM(UPPER(D.BLOCKNAME))
ORDER BY ACNO, PARTNO
;