DELETE FROM MASTERS.SECTIONS;
DELETE FROM MASTERS.ACPARTS;

ALTER TABLE ELECTIONS.SOHRAACPARTS SET SCHEMA IMPORTS;
ALTER TABLE ELECTIONS.SOHRASECTIONS SET SCHEMA IMPORTS;
ALTER TABLE ELECTIONS.SOHRABLOCKS SET SCHEMA IMPORTS;

ALTER TABLE IMPORTS.SOHRAACPARTS ADD COLUMN BLOCKCODE SMALLINT;

SELECT 'UPDATE IMPORTS.SOHRAACPARTS SET BLOCKCODE = ' || BLOCKCODE || ' WHERE ACNO = ' || ACNO || ' AND PARTNO = ' || PARTNO || ';' FROM MASTERS.BLOCKS B INNER JOIN IMPORTS.SOHRABLOCKS D ON TRIM(UPPER(B.BLOCKNAME)) = TRIM(UPPER(D.BLOCKNAME)) ;

SELECT * FROM IMPORTS.SOHRAACPARTS WHERE (ACNO, PARTNO) NOT IN (SELECT ACNO, PARTNO FROM IMPORTS.SOHRABLOCKS);


UPDATE IMPORTS.SOHRAACPARTS SET BLOCKCODE = 15 WHERE ACNO = 13 AND PARTNO IN (8, 9, 10);
UPDATE IMPORTS.SOHRAACPARTS SET MAINVILLAGECODE = 'CHERRAPUNJEEU' WHERE FVTTYPE = 'T';

INSERT INTO MASTERS.ACPARTS
SELECT ACNO, PARTNO, PARTNAME, PARTLOCATIONCATEGORY, LATITUDE, LONGITUDE, BLOCKCODE, PINCODEX, LEFT(POSTOFFICECODE,5) , LEFT(POLICESTATIONCODE,5), regexp_replace(PSBUILDINGID, '\W', '', 'g'), regexp_replace(MAINVILLAGECODE, '\W', '', 'g'), FVTTYPE, PARTGENDERTYPE, 1, CURRENT_TIMESTAMP FROM IMPORTS.SOHRAACPARTS;


UPDATE IMPORTS.SOHRASECTIONS SET VLOCATIONCODE = 'CHERRAPUNJEEU' WHERE VLOCATIONCODE LIKE '%U';

INSERT INTO MASTERS.SECTIONS SELECT ACNO, PARTNO, SECTIONNO, SECTIONNAME, regexp_replace(VLOCATIONCODE, '\W', '', 'g'), PINCODEX, 1, CURRENT_TIMESTAMP FROM IMPORTS.SOHRASECTIONS;


SELECT * FROM IMPORTS.SOHRASECTIONS WHERE regexp_replace(VLOCATIONCODE, '\W', '', 'g') NOT IN (SELECT VLOCATIONCODE FROM MASTERS.VILLAGES);
SELECT * FROM MASTERS.SECTIONS WHERE VLOCATIONCODE NOT IN (SELECT VLOCATIONCODE FROM MASTERS.VILLAGES);










