
SELECT *  FROM MASTERS.ACPARTS;

ALTER TABLE ELECTIONS.RBDACPARTS SET SCHEMA IMPORTS;
ALTER TABLE ELECTIONS.RBDSECTIONS SET SCHEMA IMPORTS;
ALTER TABLE ELECTIONS.RBDBLOCKS SET SCHEMA IMPORTS;

ALTER TABLE IMPORTS.RBDACPARTS ADD COLUMN BLOCKCODE SMALLINT;


UPDATE IMPORTS.RBDACPARTS SET BLOCKCODE = (SELECT BLOCKCODE FROM MASTERS.BLOCKS WHERE TRIM(UPPER(BLOCKNAME)) ='JIRANG') WHERE ACNO = 1;
UPDATE IMPORTS.RBDACPARTS  SET BLOCKCODE = (SELECT BLOCKCODE FROM MASTERS.BLOCKS WHERE TRIM(UPPER(BLOCKNAME)) ='UMLING') WHERE ACNO = 2;
UPDATE IMPORTS.RBDACPARTS  SET BLOCKCODE = (SELECT BLOCKCODE FROM MASTERS.BLOCKS WHERE TRIM(UPPER(BLOCKNAME)) ='UMSNING') WHERE ACNO = 3;
UPDATE IMPORTS.RBDACPARTS  SET BLOCKCODE = (SELECT BLOCKCODE FROM MASTERS.BLOCKS WHERE TRIM(UPPER(BLOCKNAME)) ='UMSNING') WHERE ACNO = 4;
UPDATE IMPORTS.RBDACPARTS  SET BLOCKCODE = (SELECT BLOCKCODE FROM MASTERS.BLOCKS WHERE TRIM(UPPER(BLOCKNAME)) ='UMROI') WHERE ACNO = 5;

UPDATE IMPORTS.RBDACPARTS SET MAINVILLAGECODE = (SELECT VLOCATIONCODE FROM MASTERS.VILLAGES WHERE VILLAGENAME = 'NONGPOH' )
WHERE 1 = 1 
--AND DISTRICTCODE = 2 
AND ACNO IN (SELECT ACNO FROM MASTERS.ASSEMBLYCONSTITUENCIES WHERE TRIM(UPPER(ACNAME)) = 'NONGPOH' )
AND FVTTYPE = 'T';


UPDATE IMPORTS.RBDACPARTS SET POSTOFFICECODE = '02007' WHERE POSTOFFICECODE = '`02007';
UPDATE IMPORTS.RBDACPARTS SET POSTOFFICECODE = '02008' WHERE POSTOFFICECODE = '`02008';
UPDATE IMPORTS.RBDACPARTS SET POSTOFFICECODE = '02008' WHERE POSTOFFICECODE = '2008';

INSERT INTO MASTERS.ACPARTS
SELECT ACNO, PARTNO, PARTNAME, PARTLOCATIONCATEGORY, LATITUDE, LONGITUDE, BLOCKCODE, PINCODEX, LEFT(POSTOFFICECODE,5) , LEFT(POLICESTATIONCODE,5), regexp_replace(PSBUILDINGID, '\W', '', 'g'), regexp_replace(MAINVILLAGECODE, '\W', '', 'g'), FVTTYPE, PARTGENDERTYPE, 1, CURRENT_TIMESTAMP FROM IMPORTS.RBDACPARTS;

UPDATE IMPORTS.RBDSECTIONS SET VLOCATIONCODE = (SELECT VLOCATIONCODE FROM MASTERS.VILLAGES WHERE VILLAGENAME = 'NONGPOH' )
WHERE ACNO = 2 AND VLOCATIONCODE LIKE '%U';


INSERT INTO MASTERS.SECTIONS SELECT ACNO, PARTNO, SECTIONNO, SECTIONNAME, VLOCATIONCODE, PINCODEX, 1, CURRENT_TIMESTAMP FROM IMPORTS.RBDSECTIONS;

SELECT * FROM MASTERS.SECTIONS WHERE VLOCATIONCODE NOT IN (SELECT VLOCATIONCODE FROM MASTERS.VILLAGES);










