--CHANGING SCHEMA
ALTER TABLE ELECTIONS."ECI_EJH" SET SCHEMA IMPORTS;
ALTER TABLE ELECTIONS."ECI_WJH" SET SCHEMA IMPORTS;

--ALTER TABLE ELECTIONS."ECI_EKH" SET SCHEMA IMPORTS;
ALTER TABLE ELECTIONS."ECI_EKWH" SET SCHEMA IMPORTS;
ALTER TABLE ELECTIONS."ECI_RB" SET SCHEMA IMPORTS;
ALTER TABLE ELECTIONS."ECI_SOHRA" SET SCHEMA IMPORTS;
ALTER TABLE ELECTIONS."ECI_SWKH" SET SCHEMA IMPORTS;
ALTER TABLE ELECTIONS."ECI_WKH" SET SCHEMA IMPORTS;



--RENAMING TABLES
SELECT 'ALTER TABLE ' || TABLE_SCHEMA || '."' || TABLE_NAME || '" RENAME TO  ' || TABLE_NAME  || ';'  FROM INFORMATION_SCHEMA.TABLES WHERE TABLE_SCHEMA ='imports' AND TABLE_NAME LIKE '%ECI%';

ALTER TABLE imports."ECI_RB" RENAME TO  ECI_RB;
ALTER TABLE imports."ECI_SOHRA" RENAME TO  ECI_SOHRA;
ALTER TABLE imports."ECI_SWKH" RENAME TO  ECI_SWKH;
ALTER TABLE imports."ECI_WKH" RENAME TO  ECI_WKH;
ALTER TABLE imports."ECI_EJH" RENAME TO  ECI_EJH;
ALTER TABLE imports."ECI_WJH" RENAME TO  ECI_WJH;
ALTER TABLE imports."ECI_EKWH" RENAME TO  ECI_EKWH;



--RENAMING COLUMNS
SELECT 'ALTER TABLE ' || TABLE_SCHEMA || '."' || TABLE_NAME || '"  RENAME COLUMN  "' || COLUMN_NAME || '"  TO ' || COLUMN_NAME || ';'
, S.* 
FROM INFORMATION_SCHEMA.COLUMNS S WHERE TABLE_SCHEMA = 'imports'  AND TABLE_NAME LIKE '%eci%' ORDER BY TABLE_NAME, ORDINAL_POSITION ;


ALTER TABLE imports."eci_ejh"  RENAME COLUMN  "ID"  TO ID;
ALTER TABLE imports."eci_ejh"  RENAME COLUMN  "EPIC_ID"  TO EPIC_ID;
ALTER TABLE imports."eci_ejh"  RENAME COLUMN  "APPROVAL_DATE"  TO APPROVAL_DATE;
ALTER TABLE imports."eci_ejh"  RENAME COLUMN  "EPIC_NUMBER"  TO EPIC_NUMBER;
ALTER TABLE imports."eci_ejh"  RENAME COLUMN  "APPLICANT_FIRST_NAME"  TO APPLICANT_FIRST_NAME;
ALTER TABLE imports."eci_ejh"  RENAME COLUMN  "APPLICANT_FIRST_NAME_L1"  TO APPLICANT_FIRST_NAME_L1;
ALTER TABLE imports."eci_ejh"  RENAME COLUMN  "APPLICANT_FIRST_NAME_L2"  TO APPLICANT_FIRST_NAME_L2;
ALTER TABLE imports."eci_ejh"  RENAME COLUMN  "APPLICANT_LAST_NAME"  TO APPLICANT_LAST_NAME;
ALTER TABLE imports."eci_ejh"  RENAME COLUMN  "APPLICANT_LAST_NAME_L1"  TO APPLICANT_LAST_NAME_L1;
ALTER TABLE imports."eci_ejh"  RENAME COLUMN  "APPLICANT_LAST_NAME_L2"  TO APPLICANT_LAST_NAME_L2;
ALTER TABLE imports."eci_ejh"  RENAME COLUMN  "STATE_CD"  TO STATE_CD;
ALTER TABLE imports."eci_ejh"  RENAME COLUMN  "STATE_NAME"  TO STATE_NAME;
ALTER TABLE imports."eci_ejh"  RENAME COLUMN  "DISTRICT_CD"  TO DISTRICT_CD;
ALTER TABLE imports."eci_ejh"  RENAME COLUMN  "PIN_CODE"  TO PIN_CODE;
ALTER TABLE imports."eci_ejh"  RENAME COLUMN  "ASSEMBLY_CONSTITUENCY_NUMBER"  TO ASSEMBLY_CONSTITUENCY_NUMBER;
ALTER TABLE imports."eci_ejh"  RENAME COLUMN  "PART_NUMBER"  TO PART_NUMBER;
ALTER TABLE imports."eci_ejh"  RENAME COLUMN  "PART_SERIAL_NUMBER"  TO PART_SERIAL_NUMBER;
ALTER TABLE imports."eci_ejh"  RENAME COLUMN  "SECTION_NO"  TO SECTION_NO;
ALTER TABLE imports."eci_ejh"  RENAME COLUMN  "AGE"  TO AGE;
ALTER TABLE imports."eci_ejh"  RENAME COLUMN  "GENDER"  TO GENDER;
ALTER TABLE imports."eci_ejh"  RENAME COLUMN  "GENDER_L1"  TO GENDER_L1;
ALTER TABLE imports."eci_ejh"  RENAME COLUMN  "GENDER_L2"  TO GENDER_L2;
ALTER TABLE imports."eci_ejh"  RENAME COLUMN  "RELATION_TYPE"  TO RELATION_TYPE;
ALTER TABLE imports."eci_ejh"  RENAME COLUMN  "RELATION_TYPE_L1"  TO RELATION_TYPE_L1;
ALTER TABLE imports."eci_ejh"  RENAME COLUMN  "RELATION_TYPE_L2"  TO RELATION_TYPE_L2;
ALTER TABLE imports."eci_ejh"  RENAME COLUMN  "RELATION_NAME"  TO RELATION_NAME;
ALTER TABLE imports."eci_ejh"  RENAME COLUMN  "RELATION_NAME_L1"  TO RELATION_NAME_L1;
ALTER TABLE imports."eci_ejh"  RENAME COLUMN  "RELATION_NAME_L2"  TO RELATION_NAME_L2;
ALTER TABLE imports."eci_ejh"  RENAME COLUMN  "HOUSE_NUMBER"  TO HOUSE_NUMBER;
ALTER TABLE imports."eci_ejh"  RENAME COLUMN  "HOUSE_NUMBER_L1"  TO HOUSE_NUMBER_L1;
ALTER TABLE imports."eci_ejh"  RENAME COLUMN  "HOUSE_NUMBER_L2"  TO HOUSE_NUMBER_L2;
ALTER TABLE imports."eci_ejh"  RENAME COLUMN  "LOCALITY_STREET"  TO LOCALITY_STREET;
ALTER TABLE imports."eci_ejh"  RENAME COLUMN  "LOCALITY_STREET_L1"  TO LOCALITY_STREET_L1;
ALTER TABLE imports."eci_ejh"  RENAME COLUMN  "LOCALITY_STREET_L2"  TO LOCALITY_STREET_L2;
ALTER TABLE imports."eci_ejh"  RENAME COLUMN  "DOB"  TO DOB;
ALTER TABLE imports."eci_ejh"  RENAME COLUMN  "POLICE_STATION"  TO POLICE_STATION;
ALTER TABLE imports."eci_ejh"  RENAME COLUMN  "POST_OFFICE"  TO POST_OFFICE;
ALTER TABLE imports."eci_ejh"  RENAME COLUMN  "DISABILITY_ANY"  TO DISABILITY_ANY;
ALTER TABLE imports."eci_ejh"  RENAME COLUMN  "DISABILITY_TYPE"  TO DISABILITY_TYPE;
ALTER TABLE imports."eci_ejh"  RENAME COLUMN  "BIRTH_DISTRICT"  TO BIRTH_DISTRICT;
ALTER TABLE imports."eci_ejh"  RENAME COLUMN  "BIRTH_STATE"  TO BIRTH_STATE;
ALTER TABLE imports."eci_ejh"  RENAME COLUMN  "BIRTH_TOWN"  TO BIRTH_TOWN;
ALTER TABLE imports."eci_ejh"  RENAME COLUMN  "WARD_NO_OLD"  TO WARD_NO_OLD;
ALTER TABLE imports."eci_ejh"  RENAME COLUMN  "CREATED_DTTM"  TO CREATED_DTTM;
ALTER TABLE imports."eci_ejh"  RENAME COLUMN  "RELATION_L_NAME"  TO RELATION_L_NAME;
ALTER TABLE imports."eci_ejh"  RENAME COLUMN  "ELECTOR_TYPE"  TO ELECTOR_TYPE;
ALTER TABLE imports."eci_ejh"  RENAME COLUMN  "RLN_L_NM_V2"  TO RLN_L_NM_V2;
ALTER TABLE imports."eci_ejh"  RENAME COLUMN  "RLN_L_NM_V1"  TO RLN_L_NM_V1;
ALTER TABLE imports."eci_ejh"  RENAME COLUMN  "C_POST_OFFICE_V1"  TO C_POST_OFFICE_V1;
ALTER TABLE imports."eci_ejh"  RENAME COLUMN  "C_DISTRICT_NO_V1"  TO C_DISTRICT_NO_V1;
ALTER TABLE imports."eci_ejh"  RENAME COLUMN  "C_PIN_CODE_V1"  TO C_PIN_CODE_V1;
ALTER TABLE imports."eci_ejh"  RENAME COLUMN  "IS_ACTIVE"  TO IS_ACTIVE;
ALTER TABLE imports."eci_ejh"  RENAME COLUMN  "TOWN_VILLAGE"  TO TOWN_VILLAGE;
ALTER TABLE imports."eci_ejh"  RENAME COLUMN  "TEHSIL_TALUKA_MANDAL"  TO TEHSIL_TALUKA_MANDAL;
ALTER TABLE imports."eci_ejh"  RENAME COLUMN  "TOWN_VILLAGE1"  TO TOWN_VILLAGE1;
ALTER TABLE imports."eci_ejh"  RENAME COLUMN  "DISABILITY_PERCENT"  TO DISABILITY_PERCENT;
ALTER TABLE imports."eci_ejh"  RENAME COLUMN  "OLD_EPIC_NO"  TO OLD_EPIC_NO;
ALTER TABLE imports."eci_ejh"  RENAME COLUMN  "TEHSIL_TALUKA_MANDAL_L1"  TO TEHSIL_TALUKA_MANDAL_L1;
ALTER TABLE imports."eci_ejh"  RENAME COLUMN  "PWD"  TO PWD;
ALTER TABLE imports."eci_ekwh"  RENAME COLUMN  "ID"  TO ID;
ALTER TABLE imports."eci_ekwh"  RENAME COLUMN  "EPIC_ID"  TO EPIC_ID;
ALTER TABLE imports."eci_ekwh"  RENAME COLUMN  "APPROVAL_DATE"  TO APPROVAL_DATE;
ALTER TABLE imports."eci_ekwh"  RENAME COLUMN  "EPIC_NUMBER"  TO EPIC_NUMBER;
ALTER TABLE imports."eci_ekwh"  RENAME COLUMN  "APPLICANT_FIRST_NAME"  TO APPLICANT_FIRST_NAME;
ALTER TABLE imports."eci_ekwh"  RENAME COLUMN  "APPLICANT_FIRST_NAME_L1"  TO APPLICANT_FIRST_NAME_L1;
ALTER TABLE imports."eci_ekwh"  RENAME COLUMN  "APPLICANT_FIRST_NAME_L2"  TO APPLICANT_FIRST_NAME_L2;
ALTER TABLE imports."eci_ekwh"  RENAME COLUMN  "APPLICANT_LAST_NAME"  TO APPLICANT_LAST_NAME;
ALTER TABLE imports."eci_ekwh"  RENAME COLUMN  "APPLICANT_LAST_NAME_L1"  TO APPLICANT_LAST_NAME_L1;
ALTER TABLE imports."eci_ekwh"  RENAME COLUMN  "APPLICANT_LAST_NAME_L2"  TO APPLICANT_LAST_NAME_L2;
ALTER TABLE imports."eci_ekwh"  RENAME COLUMN  "STATE_CD"  TO STATE_CD;
ALTER TABLE imports."eci_ekwh"  RENAME COLUMN  "STATE_NAME"  TO STATE_NAME;
ALTER TABLE imports."eci_ekwh"  RENAME COLUMN  "DISTRICT_CD"  TO DISTRICT_CD;
ALTER TABLE imports."eci_ekwh"  RENAME COLUMN  "PIN_CODE"  TO PIN_CODE;
ALTER TABLE imports."eci_ekwh"  RENAME COLUMN  "ASSEMBLY_CONSTITUENCY_NUMBER"  TO ASSEMBLY_CONSTITUENCY_NUMBER;
ALTER TABLE imports."eci_ekwh"  RENAME COLUMN  "PART_NUMBER"  TO PART_NUMBER;
ALTER TABLE imports."eci_ekwh"  RENAME COLUMN  "PART_SERIAL_NUMBER"  TO PART_SERIAL_NUMBER;
ALTER TABLE imports."eci_ekwh"  RENAME COLUMN  "SECTION_NO"  TO SECTION_NO;
ALTER TABLE imports."eci_ekwh"  RENAME COLUMN  "AGE"  TO AGE;
ALTER TABLE imports."eci_ekwh"  RENAME COLUMN  "GENDER"  TO GENDER;
ALTER TABLE imports."eci_ekwh"  RENAME COLUMN  "GENDER_L1"  TO GENDER_L1;
ALTER TABLE imports."eci_ekwh"  RENAME COLUMN  "GENDER_L2"  TO GENDER_L2;
ALTER TABLE imports."eci_ekwh"  RENAME COLUMN  "RELATION_TYPE"  TO RELATION_TYPE;
ALTER TABLE imports."eci_ekwh"  RENAME COLUMN  "RELATION_TYPE_L1"  TO RELATION_TYPE_L1;
ALTER TABLE imports."eci_ekwh"  RENAME COLUMN  "RELATION_TYPE_L2"  TO RELATION_TYPE_L2;
ALTER TABLE imports."eci_ekwh"  RENAME COLUMN  "RELATION_NAME"  TO RELATION_NAME;
ALTER TABLE imports."eci_ekwh"  RENAME COLUMN  "RELATION_NAME_L1"  TO RELATION_NAME_L1;
ALTER TABLE imports."eci_ekwh"  RENAME COLUMN  "RELATION_NAME_L2"  TO RELATION_NAME_L2;
ALTER TABLE imports."eci_ekwh"  RENAME COLUMN  "HOUSE_NUMBER"  TO HOUSE_NUMBER;
ALTER TABLE imports."eci_ekwh"  RENAME COLUMN  "HOUSE_NUMBER_L1"  TO HOUSE_NUMBER_L1;
ALTER TABLE imports."eci_ekwh"  RENAME COLUMN  "HOUSE_NUMBER_L2"  TO HOUSE_NUMBER_L2;
ALTER TABLE imports."eci_ekwh"  RENAME COLUMN  "LOCALITY_STREET"  TO LOCALITY_STREET;
ALTER TABLE imports."eci_ekwh"  RENAME COLUMN  "LOCALITY_STREET_L1"  TO LOCALITY_STREET_L1;
ALTER TABLE imports."eci_ekwh"  RENAME COLUMN  "LOCALITY_STREET_L2"  TO LOCALITY_STREET_L2;
ALTER TABLE imports."eci_ekwh"  RENAME COLUMN  "DOB"  TO DOB;
ALTER TABLE imports."eci_ekwh"  RENAME COLUMN  "POLICE_STATION"  TO POLICE_STATION;
ALTER TABLE imports."eci_ekwh"  RENAME COLUMN  "POST_OFFICE"  TO POST_OFFICE;
ALTER TABLE imports."eci_ekwh"  RENAME COLUMN  "DISABILITY_ANY"  TO DISABILITY_ANY;
ALTER TABLE imports."eci_ekwh"  RENAME COLUMN  "DISABILITY_TYPE"  TO DISABILITY_TYPE;
ALTER TABLE imports."eci_ekwh"  RENAME COLUMN  "BIRTH_DISTRICT"  TO BIRTH_DISTRICT;
ALTER TABLE imports."eci_ekwh"  RENAME COLUMN  "BIRTH_STATE"  TO BIRTH_STATE;
ALTER TABLE imports."eci_ekwh"  RENAME COLUMN  "BIRTH_TOWN"  TO BIRTH_TOWN;
ALTER TABLE imports."eci_ekwh"  RENAME COLUMN  "WARD_NO_OLD"  TO WARD_NO_OLD;
ALTER TABLE imports."eci_ekwh"  RENAME COLUMN  "CREATED_DTTM"  TO CREATED_DTTM;
ALTER TABLE imports."eci_ekwh"  RENAME COLUMN  "RELATION_L_NAME"  TO RELATION_L_NAME;
ALTER TABLE imports."eci_ekwh"  RENAME COLUMN  "ELECTOR_TYPE"  TO ELECTOR_TYPE;
ALTER TABLE imports."eci_ekwh"  RENAME COLUMN  "RLN_L_NM_V2"  TO RLN_L_NM_V2;
ALTER TABLE imports."eci_ekwh"  RENAME COLUMN  "RLN_L_NM_V1"  TO RLN_L_NM_V1;
ALTER TABLE imports."eci_ekwh"  RENAME COLUMN  "C_POST_OFFICE_V1"  TO C_POST_OFFICE_V1;
ALTER TABLE imports."eci_ekwh"  RENAME COLUMN  "C_DISTRICT_NO_V1"  TO C_DISTRICT_NO_V1;
ALTER TABLE imports."eci_ekwh"  RENAME COLUMN  "C_PIN_CODE_V1"  TO C_PIN_CODE_V1;
ALTER TABLE imports."eci_ekwh"  RENAME COLUMN  "IS_ACTIVE"  TO IS_ACTIVE;
ALTER TABLE imports."eci_ekwh"  RENAME COLUMN  "TOWN_VILLAGE"  TO TOWN_VILLAGE;
ALTER TABLE imports."eci_ekwh"  RENAME COLUMN  "TEHSIL_TALUKA_MANDAL"  TO TEHSIL_TALUKA_MANDAL;
ALTER TABLE imports."eci_ekwh"  RENAME COLUMN  "TOWN_VILLAGE1"  TO TOWN_VILLAGE1;
ALTER TABLE imports."eci_ekwh"  RENAME COLUMN  "DISABILITY_PERCENT"  TO DISABILITY_PERCENT;
ALTER TABLE imports."eci_ekwh"  RENAME COLUMN  "OLD_EPIC_NO"  TO OLD_EPIC_NO;
ALTER TABLE imports."eci_ekwh"  RENAME COLUMN  "TEHSIL_TALUKA_MANDAL_L1"  TO TEHSIL_TALUKA_MANDAL_L1;
ALTER TABLE imports."eci_ekwh"  RENAME COLUMN  "PWD"  TO PWD;
ALTER TABLE imports."eci_rb"  RENAME COLUMN  "ID"  TO ID;
ALTER TABLE imports."eci_rb"  RENAME COLUMN  "EPIC_ID"  TO EPIC_ID;
ALTER TABLE imports."eci_rb"  RENAME COLUMN  "APPROVAL_DATE"  TO APPROVAL_DATE;
ALTER TABLE imports."eci_rb"  RENAME COLUMN  "EPIC_NUMBER"  TO EPIC_NUMBER;
ALTER TABLE imports."eci_rb"  RENAME COLUMN  "APPLICANT_FIRST_NAME"  TO APPLICANT_FIRST_NAME;
ALTER TABLE imports."eci_rb"  RENAME COLUMN  "APPLICANT_FIRST_NAME_L1"  TO APPLICANT_FIRST_NAME_L1;
ALTER TABLE imports."eci_rb"  RENAME COLUMN  "APPLICANT_FIRST_NAME_L2"  TO APPLICANT_FIRST_NAME_L2;
ALTER TABLE imports."eci_rb"  RENAME COLUMN  "APPLICANT_LAST_NAME"  TO APPLICANT_LAST_NAME;
ALTER TABLE imports."eci_rb"  RENAME COLUMN  "APPLICANT_LAST_NAME_L1"  TO APPLICANT_LAST_NAME_L1;
ALTER TABLE imports."eci_rb"  RENAME COLUMN  "APPLICANT_LAST_NAME_L2"  TO APPLICANT_LAST_NAME_L2;
ALTER TABLE imports."eci_rb"  RENAME COLUMN  "STATE_CD"  TO STATE_CD;
ALTER TABLE imports."eci_rb"  RENAME COLUMN  "STATE_NAME"  TO STATE_NAME;
ALTER TABLE imports."eci_rb"  RENAME COLUMN  "DISTRICT_CD"  TO DISTRICT_CD;
ALTER TABLE imports."eci_rb"  RENAME COLUMN  "PIN_CODE"  TO PIN_CODE;
ALTER TABLE imports."eci_rb"  RENAME COLUMN  "ASSEMBLY_CONSTITUENCY_NUMBER"  TO ASSEMBLY_CONSTITUENCY_NUMBER;
ALTER TABLE imports."eci_rb"  RENAME COLUMN  "PART_NUMBER"  TO PART_NUMBER;
ALTER TABLE imports."eci_rb"  RENAME COLUMN  "PART_SERIAL_NUMBER"  TO PART_SERIAL_NUMBER;
ALTER TABLE imports."eci_rb"  RENAME COLUMN  "SECTION_NO"  TO SECTION_NO;
ALTER TABLE imports."eci_rb"  RENAME COLUMN  "AGE"  TO AGE;
ALTER TABLE imports."eci_rb"  RENAME COLUMN  "GENDER"  TO GENDER;
ALTER TABLE imports."eci_rb"  RENAME COLUMN  "GENDER_L1"  TO GENDER_L1;
ALTER TABLE imports."eci_rb"  RENAME COLUMN  "GENDER_L2"  TO GENDER_L2;
ALTER TABLE imports."eci_rb"  RENAME COLUMN  "RELATION_TYPE"  TO RELATION_TYPE;
ALTER TABLE imports."eci_rb"  RENAME COLUMN  "RELATION_TYPE_L1"  TO RELATION_TYPE_L1;
ALTER TABLE imports."eci_rb"  RENAME COLUMN  "RELATION_TYPE_L2"  TO RELATION_TYPE_L2;
ALTER TABLE imports."eci_rb"  RENAME COLUMN  "RELATION_NAME"  TO RELATION_NAME;
ALTER TABLE imports."eci_rb"  RENAME COLUMN  "RELATION_NAME_L1"  TO RELATION_NAME_L1;
ALTER TABLE imports."eci_rb"  RENAME COLUMN  "RELATION_NAME_L2"  TO RELATION_NAME_L2;
ALTER TABLE imports."eci_rb"  RENAME COLUMN  "HOUSE_NUMBER"  TO HOUSE_NUMBER;
ALTER TABLE imports."eci_rb"  RENAME COLUMN  "HOUSE_NUMBER_L1"  TO HOUSE_NUMBER_L1;
ALTER TABLE imports."eci_rb"  RENAME COLUMN  "HOUSE_NUMBER_L2"  TO HOUSE_NUMBER_L2;
ALTER TABLE imports."eci_rb"  RENAME COLUMN  "LOCALITY_STREET"  TO LOCALITY_STREET;
ALTER TABLE imports."eci_rb"  RENAME COLUMN  "LOCALITY_STREET_L1"  TO LOCALITY_STREET_L1;
ALTER TABLE imports."eci_rb"  RENAME COLUMN  "LOCALITY_STREET_L2"  TO LOCALITY_STREET_L2;
ALTER TABLE imports."eci_rb"  RENAME COLUMN  "DOB"  TO DOB;
ALTER TABLE imports."eci_rb"  RENAME COLUMN  "POLICE_STATION"  TO POLICE_STATION;
ALTER TABLE imports."eci_rb"  RENAME COLUMN  "POST_OFFICE"  TO POST_OFFICE;
ALTER TABLE imports."eci_rb"  RENAME COLUMN  "DISABILITY_ANY"  TO DISABILITY_ANY;
ALTER TABLE imports."eci_rb"  RENAME COLUMN  "DISABILITY_TYPE"  TO DISABILITY_TYPE;
ALTER TABLE imports."eci_rb"  RENAME COLUMN  "BIRTH_DISTRICT"  TO BIRTH_DISTRICT;
ALTER TABLE imports."eci_rb"  RENAME COLUMN  "BIRTH_STATE"  TO BIRTH_STATE;
ALTER TABLE imports."eci_rb"  RENAME COLUMN  "BIRTH_TOWN"  TO BIRTH_TOWN;
ALTER TABLE imports."eci_rb"  RENAME COLUMN  "WARD_NO_OLD"  TO WARD_NO_OLD;
ALTER TABLE imports."eci_rb"  RENAME COLUMN  "CREATED_DTTM"  TO CREATED_DTTM;
ALTER TABLE imports."eci_rb"  RENAME COLUMN  "RELATION_L_NAME"  TO RELATION_L_NAME;
ALTER TABLE imports."eci_rb"  RENAME COLUMN  "ELECTOR_TYPE"  TO ELECTOR_TYPE;
ALTER TABLE imports."eci_rb"  RENAME COLUMN  "RLN_L_NM_V2"  TO RLN_L_NM_V2;
ALTER TABLE imports."eci_rb"  RENAME COLUMN  "RLN_L_NM_V1"  TO RLN_L_NM_V1;
ALTER TABLE imports."eci_rb"  RENAME COLUMN  "C_POST_OFFICE_V1"  TO C_POST_OFFICE_V1;
ALTER TABLE imports."eci_rb"  RENAME COLUMN  "C_DISTRICT_NO_V1"  TO C_DISTRICT_NO_V1;
ALTER TABLE imports."eci_rb"  RENAME COLUMN  "C_PIN_CODE_V1"  TO C_PIN_CODE_V1;
ALTER TABLE imports."eci_rb"  RENAME COLUMN  "IS_ACTIVE"  TO IS_ACTIVE;
ALTER TABLE imports."eci_rb"  RENAME COLUMN  "TOWN_VILLAGE"  TO TOWN_VILLAGE;
ALTER TABLE imports."eci_rb"  RENAME COLUMN  "TEHSIL_TALUKA_MANDAL"  TO TEHSIL_TALUKA_MANDAL;
ALTER TABLE imports."eci_rb"  RENAME COLUMN  "TOWN_VILLAGE1"  TO TOWN_VILLAGE1;
ALTER TABLE imports."eci_rb"  RENAME COLUMN  "DISABILITY_PERCENT"  TO DISABILITY_PERCENT;
ALTER TABLE imports."eci_rb"  RENAME COLUMN  "OLD_EPIC_NO"  TO OLD_EPIC_NO;
ALTER TABLE imports."eci_rb"  RENAME COLUMN  "TEHSIL_TALUKA_MANDAL_L1"  TO TEHSIL_TALUKA_MANDAL_L1;
ALTER TABLE imports."eci_rb"  RENAME COLUMN  "PWD"  TO PWD;
ALTER TABLE imports."eci_sohra"  RENAME COLUMN  "ID"  TO ID;
ALTER TABLE imports."eci_sohra"  RENAME COLUMN  "EPIC_ID"  TO EPIC_ID;
ALTER TABLE imports."eci_sohra"  RENAME COLUMN  "APPROVAL_DATE"  TO APPROVAL_DATE;
ALTER TABLE imports."eci_sohra"  RENAME COLUMN  "EPIC_NUMBER"  TO EPIC_NUMBER;
ALTER TABLE imports."eci_sohra"  RENAME COLUMN  "APPLICANT_FIRST_NAME"  TO APPLICANT_FIRST_NAME;
ALTER TABLE imports."eci_sohra"  RENAME COLUMN  "APPLICANT_FIRST_NAME_L1"  TO APPLICANT_FIRST_NAME_L1;
ALTER TABLE imports."eci_sohra"  RENAME COLUMN  "APPLICANT_FIRST_NAME_L2"  TO APPLICANT_FIRST_NAME_L2;
ALTER TABLE imports."eci_sohra"  RENAME COLUMN  "APPLICANT_LAST_NAME"  TO APPLICANT_LAST_NAME;
ALTER TABLE imports."eci_sohra"  RENAME COLUMN  "APPLICANT_LAST_NAME_L1"  TO APPLICANT_LAST_NAME_L1;
ALTER TABLE imports."eci_sohra"  RENAME COLUMN  "APPLICANT_LAST_NAME_L2"  TO APPLICANT_LAST_NAME_L2;
ALTER TABLE imports."eci_sohra"  RENAME COLUMN  "STATE_CD"  TO STATE_CD;
ALTER TABLE imports."eci_sohra"  RENAME COLUMN  "STATE_NAME"  TO STATE_NAME;
ALTER TABLE imports."eci_sohra"  RENAME COLUMN  "DISTRICT_CD"  TO DISTRICT_CD;
ALTER TABLE imports."eci_sohra"  RENAME COLUMN  "PIN_CODE"  TO PIN_CODE;
ALTER TABLE imports."eci_sohra"  RENAME COLUMN  "ASSEMBLY_CONSTITUENCY_NUMBER"  TO ASSEMBLY_CONSTITUENCY_NUMBER;
ALTER TABLE imports."eci_sohra"  RENAME COLUMN  "PART_NUMBER"  TO PART_NUMBER;
ALTER TABLE imports."eci_sohra"  RENAME COLUMN  "PART_SERIAL_NUMBER"  TO PART_SERIAL_NUMBER;
ALTER TABLE imports."eci_sohra"  RENAME COLUMN  "SECTION_NO"  TO SECTION_NO;
ALTER TABLE imports."eci_sohra"  RENAME COLUMN  "AGE"  TO AGE;
ALTER TABLE imports."eci_sohra"  RENAME COLUMN  "GENDER"  TO GENDER;
ALTER TABLE imports."eci_sohra"  RENAME COLUMN  "GENDER_L1"  TO GENDER_L1;
ALTER TABLE imports."eci_sohra"  RENAME COLUMN  "GENDER_L2"  TO GENDER_L2;
ALTER TABLE imports."eci_sohra"  RENAME COLUMN  "RELATION_TYPE"  TO RELATION_TYPE;
ALTER TABLE imports."eci_sohra"  RENAME COLUMN  "RELATION_TYPE_L1"  TO RELATION_TYPE_L1;
ALTER TABLE imports."eci_sohra"  RENAME COLUMN  "RELATION_TYPE_L2"  TO RELATION_TYPE_L2;
ALTER TABLE imports."eci_sohra"  RENAME COLUMN  "RELATION_NAME"  TO RELATION_NAME;
ALTER TABLE imports."eci_sohra"  RENAME COLUMN  "RELATION_NAME_L1"  TO RELATION_NAME_L1;
ALTER TABLE imports."eci_sohra"  RENAME COLUMN  "RELATION_NAME_L2"  TO RELATION_NAME_L2;
ALTER TABLE imports."eci_sohra"  RENAME COLUMN  "HOUSE_NUMBER"  TO HOUSE_NUMBER;
ALTER TABLE imports."eci_sohra"  RENAME COLUMN  "HOUSE_NUMBER_L1"  TO HOUSE_NUMBER_L1;
ALTER TABLE imports."eci_sohra"  RENAME COLUMN  "HOUSE_NUMBER_L2"  TO HOUSE_NUMBER_L2;
ALTER TABLE imports."eci_sohra"  RENAME COLUMN  "LOCALITY_STREET"  TO LOCALITY_STREET;
ALTER TABLE imports."eci_sohra"  RENAME COLUMN  "LOCALITY_STREET_L1"  TO LOCALITY_STREET_L1;
ALTER TABLE imports."eci_sohra"  RENAME COLUMN  "LOCALITY_STREET_L2"  TO LOCALITY_STREET_L2;
ALTER TABLE imports."eci_sohra"  RENAME COLUMN  "DOB"  TO DOB;
ALTER TABLE imports."eci_sohra"  RENAME COLUMN  "POLICE_STATION"  TO POLICE_STATION;
ALTER TABLE imports."eci_sohra"  RENAME COLUMN  "POST_OFFICE"  TO POST_OFFICE;
ALTER TABLE imports."eci_sohra"  RENAME COLUMN  "DISABILITY_ANY"  TO DISABILITY_ANY;
ALTER TABLE imports."eci_sohra"  RENAME COLUMN  "DISABILITY_TYPE"  TO DISABILITY_TYPE;
ALTER TABLE imports."eci_sohra"  RENAME COLUMN  "BIRTH_DISTRICT"  TO BIRTH_DISTRICT;
ALTER TABLE imports."eci_sohra"  RENAME COLUMN  "BIRTH_STATE"  TO BIRTH_STATE;
ALTER TABLE imports."eci_sohra"  RENAME COLUMN  "BIRTH_TOWN"  TO BIRTH_TOWN;
ALTER TABLE imports."eci_sohra"  RENAME COLUMN  "WARD_NO_OLD"  TO WARD_NO_OLD;
ALTER TABLE imports."eci_sohra"  RENAME COLUMN  "CREATED_DTTM"  TO CREATED_DTTM;
ALTER TABLE imports."eci_sohra"  RENAME COLUMN  "RELATION_L_NAME"  TO RELATION_L_NAME;
ALTER TABLE imports."eci_sohra"  RENAME COLUMN  "ELECTOR_TYPE"  TO ELECTOR_TYPE;
ALTER TABLE imports."eci_sohra"  RENAME COLUMN  "RLN_L_NM_V2"  TO RLN_L_NM_V2;
ALTER TABLE imports."eci_sohra"  RENAME COLUMN  "RLN_L_NM_V1"  TO RLN_L_NM_V1;
ALTER TABLE imports."eci_sohra"  RENAME COLUMN  "C_POST_OFFICE_V1"  TO C_POST_OFFICE_V1;
ALTER TABLE imports."eci_sohra"  RENAME COLUMN  "C_DISTRICT_NO_V1"  TO C_DISTRICT_NO_V1;
ALTER TABLE imports."eci_sohra"  RENAME COLUMN  "C_PIN_CODE_V1"  TO C_PIN_CODE_V1;
ALTER TABLE imports."eci_sohra"  RENAME COLUMN  "IS_ACTIVE"  TO IS_ACTIVE;
ALTER TABLE imports."eci_sohra"  RENAME COLUMN  "TOWN_VILLAGE"  TO TOWN_VILLAGE;
ALTER TABLE imports."eci_sohra"  RENAME COLUMN  "TEHSIL_TALUKA_MANDAL"  TO TEHSIL_TALUKA_MANDAL;
ALTER TABLE imports."eci_sohra"  RENAME COLUMN  "TOWN_VILLAGE1"  TO TOWN_VILLAGE1;
ALTER TABLE imports."eci_sohra"  RENAME COLUMN  "DISABILITY_PERCENT"  TO DISABILITY_PERCENT;
ALTER TABLE imports."eci_sohra"  RENAME COLUMN  "OLD_EPIC_NO"  TO OLD_EPIC_NO;
ALTER TABLE imports."eci_sohra"  RENAME COLUMN  "TEHSIL_TALUKA_MANDAL_L1"  TO TEHSIL_TALUKA_MANDAL_L1;
ALTER TABLE imports."eci_sohra"  RENAME COLUMN  "PWD"  TO PWD;
ALTER TABLE imports."eci_swkh"  RENAME COLUMN  "ID"  TO ID;
ALTER TABLE imports."eci_swkh"  RENAME COLUMN  "EPIC_ID"  TO EPIC_ID;
ALTER TABLE imports."eci_swkh"  RENAME COLUMN  "APPROVAL_DATE"  TO APPROVAL_DATE;
ALTER TABLE imports."eci_swkh"  RENAME COLUMN  "EPIC_NUMBER"  TO EPIC_NUMBER;
ALTER TABLE imports."eci_swkh"  RENAME COLUMN  "APPLICANT_FIRST_NAME"  TO APPLICANT_FIRST_NAME;
ALTER TABLE imports."eci_swkh"  RENAME COLUMN  "APPLICANT_FIRST_NAME_L1"  TO APPLICANT_FIRST_NAME_L1;
ALTER TABLE imports."eci_swkh"  RENAME COLUMN  "APPLICANT_FIRST_NAME_L2"  TO APPLICANT_FIRST_NAME_L2;
ALTER TABLE imports."eci_swkh"  RENAME COLUMN  "APPLICANT_LAST_NAME"  TO APPLICANT_LAST_NAME;
ALTER TABLE imports."eci_swkh"  RENAME COLUMN  "APPLICANT_LAST_NAME_L1"  TO APPLICANT_LAST_NAME_L1;
ALTER TABLE imports."eci_swkh"  RENAME COLUMN  "APPLICANT_LAST_NAME_L2"  TO APPLICANT_LAST_NAME_L2;
ALTER TABLE imports."eci_swkh"  RENAME COLUMN  "STATE_CD"  TO STATE_CD;
ALTER TABLE imports."eci_swkh"  RENAME COLUMN  "STATE_NAME"  TO STATE_NAME;
ALTER TABLE imports."eci_swkh"  RENAME COLUMN  "DISTRICT_CD"  TO DISTRICT_CD;
ALTER TABLE imports."eci_swkh"  RENAME COLUMN  "PIN_CODE"  TO PIN_CODE;
ALTER TABLE imports."eci_swkh"  RENAME COLUMN  "ASSEMBLY_CONSTITUENCY_NUMBER"  TO ASSEMBLY_CONSTITUENCY_NUMBER;
ALTER TABLE imports."eci_swkh"  RENAME COLUMN  "PART_NUMBER"  TO PART_NUMBER;
ALTER TABLE imports."eci_swkh"  RENAME COLUMN  "PART_SERIAL_NUMBER"  TO PART_SERIAL_NUMBER;
ALTER TABLE imports."eci_swkh"  RENAME COLUMN  "SECTION_NO"  TO SECTION_NO;
ALTER TABLE imports."eci_swkh"  RENAME COLUMN  "AGE"  TO AGE;
ALTER TABLE imports."eci_swkh"  RENAME COLUMN  "GENDER"  TO GENDER;
ALTER TABLE imports."eci_swkh"  RENAME COLUMN  "GENDER_L1"  TO GENDER_L1;
ALTER TABLE imports."eci_swkh"  RENAME COLUMN  "GENDER_L2"  TO GENDER_L2;
ALTER TABLE imports."eci_swkh"  RENAME COLUMN  "RELATION_TYPE"  TO RELATION_TYPE;
ALTER TABLE imports."eci_swkh"  RENAME COLUMN  "RELATION_TYPE_L1"  TO RELATION_TYPE_L1;
ALTER TABLE imports."eci_swkh"  RENAME COLUMN  "RELATION_TYPE_L2"  TO RELATION_TYPE_L2;
ALTER TABLE imports."eci_swkh"  RENAME COLUMN  "RELATION_NAME"  TO RELATION_NAME;
ALTER TABLE imports."eci_swkh"  RENAME COLUMN  "RELATION_NAME_L1"  TO RELATION_NAME_L1;
ALTER TABLE imports."eci_swkh"  RENAME COLUMN  "RELATION_NAME_L2"  TO RELATION_NAME_L2;
ALTER TABLE imports."eci_swkh"  RENAME COLUMN  "HOUSE_NUMBER"  TO HOUSE_NUMBER;
ALTER TABLE imports."eci_swkh"  RENAME COLUMN  "HOUSE_NUMBER_L1"  TO HOUSE_NUMBER_L1;
ALTER TABLE imports."eci_swkh"  RENAME COLUMN  "HOUSE_NUMBER_L2"  TO HOUSE_NUMBER_L2;
ALTER TABLE imports."eci_swkh"  RENAME COLUMN  "LOCALITY_STREET"  TO LOCALITY_STREET;
ALTER TABLE imports."eci_swkh"  RENAME COLUMN  "LOCALITY_STREET_L1"  TO LOCALITY_STREET_L1;
ALTER TABLE imports."eci_swkh"  RENAME COLUMN  "LOCALITY_STREET_L2"  TO LOCALITY_STREET_L2;
ALTER TABLE imports."eci_swkh"  RENAME COLUMN  "DOB"  TO DOB;
ALTER TABLE imports."eci_swkh"  RENAME COLUMN  "POLICE_STATION"  TO POLICE_STATION;
ALTER TABLE imports."eci_swkh"  RENAME COLUMN  "POST_OFFICE"  TO POST_OFFICE;
ALTER TABLE imports."eci_swkh"  RENAME COLUMN  "DISABILITY_ANY"  TO DISABILITY_ANY;
ALTER TABLE imports."eci_swkh"  RENAME COLUMN  "DISABILITY_TYPE"  TO DISABILITY_TYPE;
ALTER TABLE imports."eci_swkh"  RENAME COLUMN  "BIRTH_DISTRICT"  TO BIRTH_DISTRICT;
ALTER TABLE imports."eci_swkh"  RENAME COLUMN  "BIRTH_STATE"  TO BIRTH_STATE;
ALTER TABLE imports."eci_swkh"  RENAME COLUMN  "BIRTH_TOWN"  TO BIRTH_TOWN;
ALTER TABLE imports."eci_swkh"  RENAME COLUMN  "WARD_NO_OLD"  TO WARD_NO_OLD;
ALTER TABLE imports."eci_swkh"  RENAME COLUMN  "CREATED_DTTM"  TO CREATED_DTTM;
ALTER TABLE imports."eci_swkh"  RENAME COLUMN  "RELATION_L_NAME"  TO RELATION_L_NAME;
ALTER TABLE imports."eci_swkh"  RENAME COLUMN  "ELECTOR_TYPE"  TO ELECTOR_TYPE;
ALTER TABLE imports."eci_swkh"  RENAME COLUMN  "RLN_L_NM_V2"  TO RLN_L_NM_V2;
ALTER TABLE imports."eci_swkh"  RENAME COLUMN  "RLN_L_NM_V1"  TO RLN_L_NM_V1;
ALTER TABLE imports."eci_swkh"  RENAME COLUMN  "C_POST_OFFICE_V1"  TO C_POST_OFFICE_V1;
ALTER TABLE imports."eci_swkh"  RENAME COLUMN  "C_DISTRICT_NO_V1"  TO C_DISTRICT_NO_V1;
ALTER TABLE imports."eci_swkh"  RENAME COLUMN  "C_PIN_CODE_V1"  TO C_PIN_CODE_V1;
ALTER TABLE imports."eci_swkh"  RENAME COLUMN  "IS_ACTIVE"  TO IS_ACTIVE;
ALTER TABLE imports."eci_swkh"  RENAME COLUMN  "TOWN_VILLAGE"  TO TOWN_VILLAGE;
ALTER TABLE imports."eci_swkh"  RENAME COLUMN  "TEHSIL_TALUKA_MANDAL"  TO TEHSIL_TALUKA_MANDAL;
ALTER TABLE imports."eci_swkh"  RENAME COLUMN  "TOWN_VILLAGE1"  TO TOWN_VILLAGE1;
ALTER TABLE imports."eci_swkh"  RENAME COLUMN  "DISABILITY_PERCENT"  TO DISABILITY_PERCENT;
ALTER TABLE imports."eci_swkh"  RENAME COLUMN  "OLD_EPIC_NO"  TO OLD_EPIC_NO;
ALTER TABLE imports."eci_swkh"  RENAME COLUMN  "TEHSIL_TALUKA_MANDAL_L1"  TO TEHSIL_TALUKA_MANDAL_L1;
ALTER TABLE imports."eci_swkh"  RENAME COLUMN  "PWD"  TO PWD;
ALTER TABLE imports."eci_wjh"  RENAME COLUMN  "ID"  TO ID;
ALTER TABLE imports."eci_wjh"  RENAME COLUMN  "EPIC_ID"  TO EPIC_ID;
ALTER TABLE imports."eci_wjh"  RENAME COLUMN  "APPROVAL_DATE"  TO APPROVAL_DATE;
ALTER TABLE imports."eci_wjh"  RENAME COLUMN  "EPIC_NUMBER"  TO EPIC_NUMBER;
ALTER TABLE imports."eci_wjh"  RENAME COLUMN  "APPLICANT_FIRST_NAME"  TO APPLICANT_FIRST_NAME;
ALTER TABLE imports."eci_wjh"  RENAME COLUMN  "APPLICANT_FIRST_NAME_L1"  TO APPLICANT_FIRST_NAME_L1;
ALTER TABLE imports."eci_wjh"  RENAME COLUMN  "APPLICANT_FIRST_NAME_L2"  TO APPLICANT_FIRST_NAME_L2;
ALTER TABLE imports."eci_wjh"  RENAME COLUMN  "APPLICANT_LAST_NAME"  TO APPLICANT_LAST_NAME;
ALTER TABLE imports."eci_wjh"  RENAME COLUMN  "APPLICANT_LAST_NAME_L1"  TO APPLICANT_LAST_NAME_L1;
ALTER TABLE imports."eci_wjh"  RENAME COLUMN  "APPLICANT_LAST_NAME_L2"  TO APPLICANT_LAST_NAME_L2;
ALTER TABLE imports."eci_wjh"  RENAME COLUMN  "STATE_CD"  TO STATE_CD;
ALTER TABLE imports."eci_wjh"  RENAME COLUMN  "STATE_NAME"  TO STATE_NAME;
ALTER TABLE imports."eci_wjh"  RENAME COLUMN  "DISTRICT_CD"  TO DISTRICT_CD;
ALTER TABLE imports."eci_wjh"  RENAME COLUMN  "PIN_CODE"  TO PIN_CODE;
ALTER TABLE imports."eci_wjh"  RENAME COLUMN  "ASSEMBLY_CONSTITUENCY_NUMBER"  TO ASSEMBLY_CONSTITUENCY_NUMBER;
ALTER TABLE imports."eci_wjh"  RENAME COLUMN  "PART_NUMBER"  TO PART_NUMBER;
ALTER TABLE imports."eci_wjh"  RENAME COLUMN  "PART_SERIAL_NUMBER"  TO PART_SERIAL_NUMBER;
ALTER TABLE imports."eci_wjh"  RENAME COLUMN  "SECTION_NO"  TO SECTION_NO;
ALTER TABLE imports."eci_wjh"  RENAME COLUMN  "AGE"  TO AGE;
ALTER TABLE imports."eci_wjh"  RENAME COLUMN  "GENDER"  TO GENDER;
ALTER TABLE imports."eci_wjh"  RENAME COLUMN  "GENDER_L1"  TO GENDER_L1;
ALTER TABLE imports."eci_wjh"  RENAME COLUMN  "GENDER_L2"  TO GENDER_L2;
ALTER TABLE imports."eci_wjh"  RENAME COLUMN  "RELATION_TYPE"  TO RELATION_TYPE;
ALTER TABLE imports."eci_wjh"  RENAME COLUMN  "RELATION_TYPE_L1"  TO RELATION_TYPE_L1;
ALTER TABLE imports."eci_wjh"  RENAME COLUMN  "RELATION_TYPE_L2"  TO RELATION_TYPE_L2;
ALTER TABLE imports."eci_wjh"  RENAME COLUMN  "RELATION_NAME"  TO RELATION_NAME;
ALTER TABLE imports."eci_wjh"  RENAME COLUMN  "RELATION_NAME_L1"  TO RELATION_NAME_L1;
ALTER TABLE imports."eci_wjh"  RENAME COLUMN  "RELATION_NAME_L2"  TO RELATION_NAME_L2;
ALTER TABLE imports."eci_wjh"  RENAME COLUMN  "HOUSE_NUMBER"  TO HOUSE_NUMBER;
ALTER TABLE imports."eci_wjh"  RENAME COLUMN  "HOUSE_NUMBER_L1"  TO HOUSE_NUMBER_L1;
ALTER TABLE imports."eci_wjh"  RENAME COLUMN  "HOUSE_NUMBER_L2"  TO HOUSE_NUMBER_L2;
ALTER TABLE imports."eci_wjh"  RENAME COLUMN  "LOCALITY_STREET"  TO LOCALITY_STREET;
ALTER TABLE imports."eci_wjh"  RENAME COLUMN  "LOCALITY_STREET_L1"  TO LOCALITY_STREET_L1;
ALTER TABLE imports."eci_wjh"  RENAME COLUMN  "LOCALITY_STREET_L2"  TO LOCALITY_STREET_L2;
ALTER TABLE imports."eci_wjh"  RENAME COLUMN  "DOB"  TO DOB;
ALTER TABLE imports."eci_wjh"  RENAME COLUMN  "POLICE_STATION"  TO POLICE_STATION;
ALTER TABLE imports."eci_wjh"  RENAME COLUMN  "POST_OFFICE"  TO POST_OFFICE;
ALTER TABLE imports."eci_wjh"  RENAME COLUMN  "DISABILITY_ANY"  TO DISABILITY_ANY;
ALTER TABLE imports."eci_wjh"  RENAME COLUMN  "DISABILITY_TYPE"  TO DISABILITY_TYPE;
ALTER TABLE imports."eci_wjh"  RENAME COLUMN  "BIRTH_DISTRICT"  TO BIRTH_DISTRICT;
ALTER TABLE imports."eci_wjh"  RENAME COLUMN  "BIRTH_STATE"  TO BIRTH_STATE;
ALTER TABLE imports."eci_wjh"  RENAME COLUMN  "BIRTH_TOWN"  TO BIRTH_TOWN;
ALTER TABLE imports."eci_wjh"  RENAME COLUMN  "WARD_NO_OLD"  TO WARD_NO_OLD;
ALTER TABLE imports."eci_wjh"  RENAME COLUMN  "CREATED_DTTM"  TO CREATED_DTTM;
ALTER TABLE imports."eci_wjh"  RENAME COLUMN  "RELATION_L_NAME"  TO RELATION_L_NAME;
ALTER TABLE imports."eci_wjh"  RENAME COLUMN  "ELECTOR_TYPE"  TO ELECTOR_TYPE;
ALTER TABLE imports."eci_wjh"  RENAME COLUMN  "RLN_L_NM_V2"  TO RLN_L_NM_V2;
ALTER TABLE imports."eci_wjh"  RENAME COLUMN  "RLN_L_NM_V1"  TO RLN_L_NM_V1;
ALTER TABLE imports."eci_wjh"  RENAME COLUMN  "C_POST_OFFICE_V1"  TO C_POST_OFFICE_V1;
ALTER TABLE imports."eci_wjh"  RENAME COLUMN  "C_DISTRICT_NO_V1"  TO C_DISTRICT_NO_V1;
ALTER TABLE imports."eci_wjh"  RENAME COLUMN  "C_PIN_CODE_V1"  TO C_PIN_CODE_V1;
ALTER TABLE imports."eci_wjh"  RENAME COLUMN  "IS_ACTIVE"  TO IS_ACTIVE;
ALTER TABLE imports."eci_wjh"  RENAME COLUMN  "TOWN_VILLAGE"  TO TOWN_VILLAGE;
ALTER TABLE imports."eci_wjh"  RENAME COLUMN  "TEHSIL_TALUKA_MANDAL"  TO TEHSIL_TALUKA_MANDAL;
ALTER TABLE imports."eci_wjh"  RENAME COLUMN  "TOWN_VILLAGE1"  TO TOWN_VILLAGE1;
ALTER TABLE imports."eci_wjh"  RENAME COLUMN  "DISABILITY_PERCENT"  TO DISABILITY_PERCENT;
ALTER TABLE imports."eci_wjh"  RENAME COLUMN  "OLD_EPIC_NO"  TO OLD_EPIC_NO;
ALTER TABLE imports."eci_wjh"  RENAME COLUMN  "TEHSIL_TALUKA_MANDAL_L1"  TO TEHSIL_TALUKA_MANDAL_L1;
ALTER TABLE imports."eci_wjh"  RENAME COLUMN  "PWD"  TO PWD;
ALTER TABLE imports."eci_wkh"  RENAME COLUMN  "ID"  TO ID;
ALTER TABLE imports."eci_wkh"  RENAME COLUMN  "EPIC_ID"  TO EPIC_ID;
ALTER TABLE imports."eci_wkh"  RENAME COLUMN  "APPROVAL_DATE"  TO APPROVAL_DATE;
ALTER TABLE imports."eci_wkh"  RENAME COLUMN  "EPIC_NUMBER"  TO EPIC_NUMBER;
ALTER TABLE imports."eci_wkh"  RENAME COLUMN  "APPLICANT_FIRST_NAME"  TO APPLICANT_FIRST_NAME;
ALTER TABLE imports."eci_wkh"  RENAME COLUMN  "APPLICANT_FIRST_NAME_L1"  TO APPLICANT_FIRST_NAME_L1;
ALTER TABLE imports."eci_wkh"  RENAME COLUMN  "APPLICANT_FIRST_NAME_L2"  TO APPLICANT_FIRST_NAME_L2;
ALTER TABLE imports."eci_wkh"  RENAME COLUMN  "APPLICANT_LAST_NAME"  TO APPLICANT_LAST_NAME;
ALTER TABLE imports."eci_wkh"  RENAME COLUMN  "APPLICANT_LAST_NAME_L1"  TO APPLICANT_LAST_NAME_L1;
ALTER TABLE imports."eci_wkh"  RENAME COLUMN  "APPLICANT_LAST_NAME_L2"  TO APPLICANT_LAST_NAME_L2;
ALTER TABLE imports."eci_wkh"  RENAME COLUMN  "STATE_CD"  TO STATE_CD;
ALTER TABLE imports."eci_wkh"  RENAME COLUMN  "STATE_NAME"  TO STATE_NAME;
ALTER TABLE imports."eci_wkh"  RENAME COLUMN  "DISTRICT_CD"  TO DISTRICT_CD;
ALTER TABLE imports."eci_wkh"  RENAME COLUMN  "PIN_CODE"  TO PIN_CODE;
ALTER TABLE imports."eci_wkh"  RENAME COLUMN  "ASSEMBLY_CONSTITUENCY_NUMBER"  TO ASSEMBLY_CONSTITUENCY_NUMBER;
ALTER TABLE imports."eci_wkh"  RENAME COLUMN  "PART_NUMBER"  TO PART_NUMBER;
ALTER TABLE imports."eci_wkh"  RENAME COLUMN  "PART_SERIAL_NUMBER"  TO PART_SERIAL_NUMBER;
ALTER TABLE imports."eci_wkh"  RENAME COLUMN  "SECTION_NO"  TO SECTION_NO;
ALTER TABLE imports."eci_wkh"  RENAME COLUMN  "AGE"  TO AGE;
ALTER TABLE imports."eci_wkh"  RENAME COLUMN  "GENDER"  TO GENDER;
ALTER TABLE imports."eci_wkh"  RENAME COLUMN  "GENDER_L1"  TO GENDER_L1;
ALTER TABLE imports."eci_wkh"  RENAME COLUMN  "GENDER_L2"  TO GENDER_L2;
ALTER TABLE imports."eci_wkh"  RENAME COLUMN  "RELATION_TYPE"  TO RELATION_TYPE;
ALTER TABLE imports."eci_wkh"  RENAME COLUMN  "RELATION_TYPE_L1"  TO RELATION_TYPE_L1;
ALTER TABLE imports."eci_wkh"  RENAME COLUMN  "RELATION_TYPE_L2"  TO RELATION_TYPE_L2;
ALTER TABLE imports."eci_wkh"  RENAME COLUMN  "RELATION_NAME"  TO RELATION_NAME;
ALTER TABLE imports."eci_wkh"  RENAME COLUMN  "RELATION_NAME_L1"  TO RELATION_NAME_L1;
ALTER TABLE imports."eci_wkh"  RENAME COLUMN  "RELATION_NAME_L2"  TO RELATION_NAME_L2;
ALTER TABLE imports."eci_wkh"  RENAME COLUMN  "HOUSE_NUMBER"  TO HOUSE_NUMBER;
ALTER TABLE imports."eci_wkh"  RENAME COLUMN  "HOUSE_NUMBER_L1"  TO HOUSE_NUMBER_L1;
ALTER TABLE imports."eci_wkh"  RENAME COLUMN  "HOUSE_NUMBER_L2"  TO HOUSE_NUMBER_L2;
ALTER TABLE imports."eci_wkh"  RENAME COLUMN  "LOCALITY_STREET"  TO LOCALITY_STREET;
ALTER TABLE imports."eci_wkh"  RENAME COLUMN  "LOCALITY_STREET_L1"  TO LOCALITY_STREET_L1;
ALTER TABLE imports."eci_wkh"  RENAME COLUMN  "LOCALITY_STREET_L2"  TO LOCALITY_STREET_L2;
ALTER TABLE imports."eci_wkh"  RENAME COLUMN  "DOB"  TO DOB;
ALTER TABLE imports."eci_wkh"  RENAME COLUMN  "POLICE_STATION"  TO POLICE_STATION;
ALTER TABLE imports."eci_wkh"  RENAME COLUMN  "POST_OFFICE"  TO POST_OFFICE;
ALTER TABLE imports."eci_wkh"  RENAME COLUMN  "DISABILITY_ANY"  TO DISABILITY_ANY;
ALTER TABLE imports."eci_wkh"  RENAME COLUMN  "DISABILITY_TYPE"  TO DISABILITY_TYPE;
ALTER TABLE imports."eci_wkh"  RENAME COLUMN  "BIRTH_DISTRICT"  TO BIRTH_DISTRICT;
ALTER TABLE imports."eci_wkh"  RENAME COLUMN  "BIRTH_STATE"  TO BIRTH_STATE;
ALTER TABLE imports."eci_wkh"  RENAME COLUMN  "BIRTH_TOWN"  TO BIRTH_TOWN;
ALTER TABLE imports."eci_wkh"  RENAME COLUMN  "WARD_NO_OLD"  TO WARD_NO_OLD;
ALTER TABLE imports."eci_wkh"  RENAME COLUMN  "CREATED_DTTM"  TO CREATED_DTTM;
ALTER TABLE imports."eci_wkh"  RENAME COLUMN  "RELATION_L_NAME"  TO RELATION_L_NAME;
ALTER TABLE imports."eci_wkh"  RENAME COLUMN  "ELECTOR_TYPE"  TO ELECTOR_TYPE;
ALTER TABLE imports."eci_wkh"  RENAME COLUMN  "RLN_L_NM_V2"  TO RLN_L_NM_V2;
ALTER TABLE imports."eci_wkh"  RENAME COLUMN  "RLN_L_NM_V1"  TO RLN_L_NM_V1;
ALTER TABLE imports."eci_wkh"  RENAME COLUMN  "C_POST_OFFICE_V1"  TO C_POST_OFFICE_V1;
ALTER TABLE imports."eci_wkh"  RENAME COLUMN  "C_DISTRICT_NO_V1"  TO C_DISTRICT_NO_V1;
ALTER TABLE imports."eci_wkh"  RENAME COLUMN  "C_PIN_CODE_V1"  TO C_PIN_CODE_V1;
ALTER TABLE imports."eci_wkh"  RENAME COLUMN  "IS_ACTIVE"  TO IS_ACTIVE;
ALTER TABLE imports."eci_wkh"  RENAME COLUMN  "TOWN_VILLAGE"  TO TOWN_VILLAGE;
ALTER TABLE imports."eci_wkh"  RENAME COLUMN  "TEHSIL_TALUKA_MANDAL"  TO TEHSIL_TALUKA_MANDAL;
ALTER TABLE imports."eci_wkh"  RENAME COLUMN  "TOWN_VILLAGE1"  TO TOWN_VILLAGE1;
ALTER TABLE imports."eci_wkh"  RENAME COLUMN  "DISABILITY_PERCENT"  TO DISABILITY_PERCENT;
ALTER TABLE imports."eci_wkh"  RENAME COLUMN  "OLD_EPIC_NO"  TO OLD_EPIC_NO;
ALTER TABLE imports."eci_wkh"  RENAME COLUMN  "TEHSIL_TALUKA_MANDAL_L1"  TO TEHSIL_TALUKA_MANDAL_L1;
ALTER TABLE imports."eci_wkh"  RENAME COLUMN  "PWD"  TO PWD;


INSERT INTO SOURCES.SOURCEELECTORALROLLS SELECT 
epic_id,	null, epic_number,	applicant_first_name,	applicant_first_name_l1,	applicant_last_name,	applicant_last_name_l1,	assembly_constituency_number,	part_number,	part_serial_number,	section_no,	age,	gender,	relation_type,	relation_name,	relation_name_l1,	house_number,	
TO_CHAR(dob,'yyyy-mm-dd'),	
null,	'N',	relation_l_name,	rln_l_nm_v1,	is_active,	0,	NULL,	house_number_l1,	'N'
FROM IMPORTS.ECI_EJH ;

INSERT INTO SOURCES.SOURCEELECTORALROLLS SELECT 
epic_id,	null, epic_number,	applicant_first_name,	applicant_first_name_l1,	applicant_last_name,	applicant_last_name_l1,	assembly_constituency_number,	part_number,	part_serial_number,	section_no,	age,	gender,	relation_type,	relation_name,	relation_name_l1,	house_number,	
DOB,	
null,	'N',	relation_l_name,	rln_l_nm_v1,	LEFT(is_active,1),	0,	NULL,	house_number_l1,	'N'
FROM IMPORTS.ECI_WJH ;


INSERT INTO SOURCES.SOURCEELECTORALROLLS SELECT 
epic_id,	null, epic_number,	applicant_first_name,	applicant_first_name_l1,	applicant_last_name,	applicant_last_name_l1,	assembly_constituency_number,	part_number,	part_serial_number,	section_no,	age,	gender,	relation_type,	relation_name,	relation_name_l1,	house_number,	
TO_CHAR(dob,'yyyy-mm-dd'),	
null,	'N',	relation_l_name,	rln_l_nm_v1,	LEFT(is_active,1),	0,	NULL,	house_number_l1,	'N'
FROM IMPORTS.ECI_EKWH ;


INSERT INTO SOURCES.SOURCEELECTORALROLLS SELECT 
epic_id,	null, epic_number,	applicant_first_name,	applicant_first_name_l1,	applicant_last_name,	applicant_last_name_l1,	assembly_constituency_number,	part_number,	part_serial_number,	section_no,	age,	gender,	relation_type,	relation_name,	relation_name_l1,	house_number,	
TO_CHAR(dob,'yyyy-mm-dd'),	
null,	'N',	relation_l_name,	rln_l_nm_v1,	LEFT(is_active,1),	0,	NULL,	house_number_l1,	'N'
FROM IMPORTS.ECI_RB ;

INSERT INTO SOURCES.SOURCEELECTORALROLLS SELECT 
epic_id,	null, epic_number,	applicant_first_name,	applicant_first_name_l1,	applicant_last_name,	applicant_last_name_l1,	assembly_constituency_number,	part_number,	part_serial_number,	section_no,	age,	gender,	relation_type,	relation_name,	relation_name_l1,	house_number,	
DOB,
null,	'N',	relation_l_name,	rln_l_nm_v1,	LEFT(is_active,1),	0,	NULL,	house_number_l1,	'N'
FROM IMPORTS.ECI_SWKH ;


INSERT INTO SOURCES.SOURCEELECTORALROLLS SELECT 
epic_id,	null, epic_number,	applicant_first_name,	applicant_first_name_l1,	applicant_last_name,	applicant_last_name_l1,	assembly_constituency_number,	part_number,	part_serial_number,	section_no,	age,	gender,	relation_type,	relation_name,	relation_name_l1,	house_number,	
TO_CHAR(dob,'yyyy-mm-dd'),	
null,	'N',	relation_l_name,	rln_l_nm_v1,	LEFT(is_active,1),	0,	NULL,	house_number_l1,	'N'
FROM IMPORTS.ECI_WKH ;

