/*
--UPDATE SOURCES.SOURCEELECTORALROLLS   SET GENDER = TRIM(UPPER(GENDER));






DELETE FROM ELECTIONS.ELECTORALROLLSTEMP ;
UPDATE SOURCES.SOURCEELECTORALROLLS SET MOVED ='N' WHERE ASSEMBLY_CONSTITUENCY_NUMBER = 13 AND  PART_NUMBER = 1;
UPDATE SOURCES.SOURCEELECTORALROLLS SET MOVED ='N' WHERE MOVED='Y';

SELECT COUNT(*) FROM SOURCES.SOURCEELECTORALROLLS WHERE MOVED='Y';


-- DETAILS
SELECT    ASSEMBLY_CONSTITUENCY_NUMBER ,AP.PART_NUMBER ,SECTION_NO, PART_SERIAL_NUMBER FROM SOURCES.AC_LIST AC INNER JOIN SOURCES.PART_LIST AP
ON AC.ASMBLY_NO = REGEXP_REPLACE(AP.ASMBLY_NO, '\D', '', 'g')::SMALLINT 
INNER JOIN SOURCES.SOURCEELECTORALROLLS  E ON (REGEXP_REPLACE(AP.ASMBLY_NO, '\D', '', 'g')::SMALLINT = E.ASSEMBLY_CONSTITUENCY_NUMBER AND AP.PART_NUMBER = E.PART_NUMBER)
WHERE ASSEMBLY_CONSTITUENCY_NUMBER = 17 AND  AP.PART_NUMBER = 4
--AND E.SECTION_NO = 4
AND PART_SERIAL_NUMBER BETWEEN 100 AND 200
--AND GENDER ='F'
ORDER BY ASSEMBLY_CONSTITUENCY_NUMBER ,AP.PART_NUMBER ,PART_SERIAL_NUMBER

SELECT * FROM ELECTIONS.ELECTORALROLLSTEMP  WHERE ACNO = 5 AND PARTNO = 10 ORDER BY ACNO, PARTNO, SLNOINPART, SECTIONNO;

SELECT  AC.ACNO , ACNAME , AP.PARTNO, PARTNAME, S.SECTIONNO, S.SECTIONNAME  , 
SUM(CASE WHEN GENDER='M' THEN 1 ELSE 0 END) AS MALE, SUM(CASE WHEN GENDER='F' THEN 1 ELSE 0 END) AS FEMALE, 
SUM(CASE WHEN GENDER='T' THEN 1 ELSE 0 END) AS THIRD, COUNT(*) AS TOTAL
FROM MASTERS.ASSEMBLYCONSTITUENCIES AC INNER JOIN MASTERS.ACPARTS AP ON (AC.ACNO = AP.ACNO)
INNER JOIN MASTERS.SECTIONS S ON (AP.ACNO = S.ACNO AND AP.PARTNO = S.PARTNO)
INNER JOIN ELECTIONS.ELECTORALROLLSTEMP E ON (S.ACNO = E.ACNO AND S.PARTNO = E.PARTNO AND S.SECTIONNO = E.SECTIONNO)
GROUP BY AC.ACNO , ACNAME , AP.PARTNO, PARTNAME, S.SECTIONNO, S.SECTIONNAME  
ORDER BY AC.ACNO , ACNAME , AP.PARTNO, PARTNAME, S.SECTIONNO, S.SECTIONNAME  


