/*
--ASSEMBLY CONSTS
SELECT O.OFFICECODE, OFFICENAME, AC.ACNO, ACNAME FROM MASTERS.OFFICES O INNER JOIN MASTERS.OFFICESACS OAC ON O.OFFICECODE = OAC.OFFICECODE
INNER JOIN MASTERS.ASSEMBLYCONSTITUENCIES AC ON AC.ACNO = OAC.ACNO ORDER BY AC.ACNO;


-- AC PARTS & POLLING STATIONS
SELECT  O.OFFICENAME, AC.ACNO , ACNAME , AP.PARTNO, PARTNAME, V.VILLAGENAME AS MAINTOWNVILLAGE, POSTOFFICENAME, 
POLICESTATIONNAME, BLOCKNAME, CASE WHEN DISTRICTSDO = 'S' THEN (SELECT DISTRICTNAME FROM MASTERS.DISTRICTS SDOS WHERE SDOS.DISTRICTCODE = D.REFERENCEDISTRICTCODE) ELSE '' END AS SUBDIVISION,
D.DISTRICTNAME,PO.PINCODE, PSNAME, PSADDRESS
FROM MASTERS.DISTRICTS D INNER JOIN MASTERS.OFFICES O ON D.DISTRICTCODE = O.DISTRICTCODE INNER JOIN MASTERS.OFFICESACS OAC ON O.OFFICECODE = OAC.OFFICECODE
INNER JOIN MASTERS.ASSEMBLYCONSTITUENCIES AC ON AC.ACNO = OAC.ACNO INNER JOIN MASTERS.ACPARTS AP ON (AC.ACNO = AP.ACNO)
INNER JOIN MASTERS.BLOCKS B  ON B.BLOCKCODE = AP.BLOCKCODE
INNER JOIN MASTERS.POLLINGSTATIONS PS ON PS.PSBUILDINGID = AP.PSBUILDINGID
INNER JOIN MASTERS.POSTOFFICES PO ON PO.POSTOFFICECODE = AP.POSTOFFICECODE 
INNER JOIN MASTERS.POLICESTATIONS PST ON PST.POLICESTATIONCODE = AP.POLICESTATIONCODE 
INNER JOIN MASTERS.VILLAGES V ON V.VLOCATIONCODE = MAINVILLAGECODE
--WHERE AC.ACNO = 1 AND AP.PARTNO = 1
ORDER BY AC.ACNO, AP.PARTNO;


-- SECTIONS
SELECT  
O.OFFICENAME, AC.ACNO , ACNAME , AP.PARTNO, PARTNAME, S.SECTIONNO, S.SECTIONNAME
FROM MASTERS.DISTRICTS D INNER JOIN MASTERS.OFFICES O ON D.DISTRICTCODE = O.DISTRICTCODE INNER JOIN MASTERS.OFFICESACS OAC ON O.OFFICECODE = OAC.OFFICECODE
INNER JOIN MASTERS.ASSEMBLYCONSTITUENCIES AC ON AC.ACNO = OAC.ACNO INNER JOIN MASTERS.ACPARTS AP ON (AC.ACNO = AP.ACNO)
INNER JOIN MASTERS.BLOCKS B  ON B.BLOCKCODE = AP.BLOCKCODE
INNER JOIN MASTERS.POLLINGSTATIONS PS ON PS.PSBUILDINGID = AP.PSBUILDINGID
INNER JOIN MASTERS.POSTOFFICES PO ON PO.POSTOFFICECODE = AP.POSTOFFICECODE 
INNER JOIN MASTERS.POLICESTATIONS PST ON PST.POLICESTATIONCODE = AP.POLICESTATIONCODE 
INNER JOIN MASTERS.VILLAGES V ON V.VLOCATIONCODE = MAINVILLAGECODE
INNER JOIN MASTERS.SECTIONS S ON (AP.ACNO = S.ACNO AND AP.PARTNO = S.PARTNO)
ORDER BY AC.ACNO, AP.PARTNO, S.SECTIONNO;

*/

SELECT  O.OFFICENAME, 
REVISIONDESCRIPTION, REVISIONYEAR, QUALIFYINGDATE,REVISIONTYPE,  TO_CHAR(PUBLICATIONDATE,'dd-mm-yyyy') AS PUBLICATIONDATE, TO_CHAR(QUALIFYINGDATE,'dd-mm-yyyy') AS QUALIFYINGDATE,
AC.ACNO , ACNAME , ACTYPE, AP.PARTNO, PARTNAME, PARTGENDERTYPE, S.SECTIONNO, S.SECTIONNAME, GETSECTIONSNONAME(E.ACNO, E.PARTNO) AS SECTIONS, PO.PINCODE, 
'0' AS NOOFAUXYPS,
(SELECT COUNT(*) FROM MASTERS.POLLINGSTATIONS PSC WHERE PSC.ACNO = E.ACNO AND PSC.PARTNO = E.PARTNO) - 1 AS NOOFAUXYPS, 
(SELECT MIN(SLNOINPART) FROM ELECTORALROLLS ESL WHERE ESL.ACNO = E.ACNO AND ESL.PARTNO = E.PARTNO) AS MINSLNO, 
(SELECT MAX(SLNOINPART) FROM ELECTORALROLLS ESL WHERE ESL.ACNO = E.ACNO AND ESL.PARTNO = E.PARTNO) AS MAXSLNO, 
(SELECT COUNT(*) FROM ELECTORALROLLS ESL WHERE ESL.ACNO = E.ACNO AND ESL.PARTNO = E.PARTNO AND GENDER ='M') AS MALES, 
(SELECT COUNT(*) FROM ELECTORALROLLS ESL WHERE ESL.ACNO = E.ACNO AND ESL.PARTNO = E.PARTNO AND GENDER ='F') AS FEMALES, 
(SELECT COUNT(*) FROM ELECTORALROLLS ESL WHERE ESL.ACNO = E.ACNO AND ESL.PARTNO = E.PARTNO AND GENDER ='T') AS THIRDGENDER, 
(SELECT COUNT(*) FROM ELECTORALROLLS ESL WHERE ESL.ACNO = E.ACNO AND ESL.PARTNO = E.PARTNO ) AS TOTALVOTERS, 
E.SLNOINPART, GETVOTERSNAME(E.ACNO, E.PARTNO, E.SLNOINPART) AS VOTERSNAME, EPICCARDNO, GETRELATIONTYPE(E.ACNO, E.PARTNO, E.SLNOINPART) AS RELATIONTYPE, GETRELATIONNAME(E.ACNO, E.PARTNO, E.SLNOINPART) || ' ['  || RELATIONTYPE || ']' AS RELATIONNAME,
HOUSENO, AGE, GENDER, EPICCARDNO, V.VILLAGENAME, POSTOFFICENAME, POLICESTATIONNAME, CASE WHEN AP.FVTTYPE ='V' THEN B.BLOCKNAME ELSE '' END AS BLOCKNAME, 
CASE WHEN DISTRICTSDO ='S' THEN (SELECT DISTRICTNAME FROM MASTERS.DISTRICTS S WHERE S.DISTRICTCODE = D.REFERENCEDISTRICTCODE) ELSE '' END AS SDONAME, 
D.DISTRICTNAME, PSNAME, PSBUILDINGNAME, PSADDRESS
FROM MASTERS.DISTRICTS D INNER JOIN MASTERS.OFFICES O ON D.DISTRICTCODE = O.DISTRICTCODE INNER JOIN MASTERS.OFFICESACS OAC ON O.OFFICECODE = OAC.OFFICECODE
INNER JOIN MASTERS.ASSEMBLYCONSTITUENCIES AC ON AC.ACNO = OAC.ACNO INNER JOIN MASTERS.ACPARTS AP ON (AC.ACNO = AP.ACNO)
INNER JOIN MASTERS.BLOCKS B  ON B.BLOCKCODE = AP.BLOCKCODE
INNER JOIN MASTERS.POLLINGSTATIONS PS ON PS.PSBUILDINGID = AP.PSBUILDINGID
INNER JOIN MASTERS.POSTOFFICES PO ON PO.POSTOFFICECODE = AP.POSTOFFICECODE 
INNER JOIN MASTERS.POLICESTATIONS PST ON PST.POLICESTATIONCODE = AP.POLICESTATIONCODE 
INNER JOIN MASTERS.VILLAGES V ON V.VLOCATIONCODE = MAINVILLAGECODE
INNER JOIN MASTERS.SECTIONS S ON (AP.ACNO = S.ACNO AND AP.PARTNO = S.PARTNO)
INNER JOIN ELECTIONS.ELECTORALROLLS E ON (S.ACNO = E.ACNO AND S.PARTNO = E.PARTNO AND S.SECTIONNO = E.SECTIONNO)
INNER JOIN MASTERS.ELECTORALROLLREVISIONS RV ON RV.REVISIONNO = E.REVISIONNO
ORDER BY AC.ACNO, AP.PARTNO, S.SECTIONNO, SLNOINPART;

