/*
UPDATE SOURCES.AC_LIST SET ASMBLY_NAME = ASMBLY_NAME || '_SRC';
UPDATE SOURCES.PART_LIST SET PART_NAME = PART_NAME|| '_SRC';
*/
/*
--ACs
SELECT ASMBLY_NO AS ACNO, ASMBLY_NAME AS ACNAME FROM SOURCES.AC_LIST ORDER BY ASMBLY_NO;

SELECT AC.* FROM SOURCES.AC_LIST AC INNER JOIN SOURCES.OFFICESACS O ON AC.ASMBLY_NO = O.ACNO WHERE O.OFFICECODE = '030001' ORDER BY ASMBLY_NO;

--AC PARTs
SELECT REGEXP_REPLACE(	ASMBLY_NO, '\D', '', 'g')::SMALLINT AS ACNO, PART_NUMBER AS PARTNO, PART_NAME AS PARTNAME FROM SOURCES.PART_LIST ORDER BY ASMBLY_NO, PART_NUMBER;

SELECT AC.ASMBLY_NO AS ACNO, ASMBLY_NAME, PART_NUMBER AS PARTNO, PART_NAME AS PARTNAME FROM SOURCES.AC_LIST AC INNER JOIN SOURCES.PART_LIST AP
ON AC.ASMBLY_NO = REGEXP_REPLACE(AP.ASMBLY_NO, '\D', '', 'g')::SMALLINT 
ORDER BY AC.ASMBLY_NO, PART_NUMBER;



select * from sources.part_list LIMIT 10;

--PARTS AND POLLING STATIONs
SELECT 
AC.ASMBLY_NO AS ACNO, ASMBLY_NAME, PART_NUMBER AS PARTNO, PART_NAME AS PARTNAME , PSB.PSBUILDING_ID, PSBUILDING_NAME
FROM SOURCES.AC_LIST AC INNER JOIN SOURCES.PART_LIST AP ON AC.ASMBLY_NO = REGEXP_REPLACE(AP.ASMBLY_NO, '\D', '', 'g')::SMALLINT 
INNER JOIN SOURCES.PS_BUILDINGS PSB ON AP.PSBUILDING_ID =PSB.PSBUILDING_ID 
--WHERE TRIM(UPPER(PART_NAME)) LIKE 'MOOKAS%' Z
ORDER BY AC.ASMBLY_NO, PART_NUMBER;


--SECTIONS
SELECT AC.ASMBLY_NO AS ACNO, ASMBLY_NAME, PART_NUMBER AS PARTNO, PART_NAME AS PARTNAME  , S.SECTION_NO, S.SECTION_NAME
FROM SOURCES.AC_LIST AC INNER JOIN SOURCES.PART_LIST AP ON AC.ASMBLY_NO = REGEXP_REPLACE(AP.ASMBLY_NO, '\D', '', 'g')::SMALLINT 
INNER JOIN SOURCES.SECTION_LIST S ON REGEXP_REPLACE(AP.ASMBLY_NO, '\D', '', 'g')::SMALLINT  = S.ASMBLY_NO AND AP.PART_NUMBER = S.PART_NO
ORDER BY AC.ASMBLY_NO, PART_NUMBER, S.SECTION_NO;

*/
------------------------------------------------------------------------------------
------------------------------------------------------------------------------------
-----------ANOMALIES
------------------------------------------------------------------------------------
------------------------------------------------------------------------------------

SELECT * FROM SOURCES.BLOCKS;

--SELECT * FROM SOURCES.PART_LIST

SELECT 
AP.*,B.*,
AC.ASMBLY_NO AS ACNO, ASMBLY_NAME, PART_NUMBER AS PARTNO, PART_NAME AS PARTNAME FROM SOURCES.AC_LIST AC INNER JOIN SOURCES.PART_LIST AP
ON AC.ASMBLY_NO = REGEXP_REPLACE(AP.ASMBLY_NO, '\D', '', 'g')::SMALLINT 
ORDER BY AC.ASMBLY_NO, PART_NUMBER;

