-- RUN THIS IN ORACLE
DROP TABLE OFFICEPERSONNEL ;


CREATE TABLE OFFICEPERSONNEL  AS (
SELECT O.OFFICE_NO AS OFFICENO ,O.OFFICE_NAME, 
O.ADDRESS, O.OFFICE_HEAD, CASE WHEN O.OFFICE_TYPE = 3 THEN 7 ELSE O.OFFICE_TYPE END AS OFFICE_TYPE, 
P.EMPLOYEENO, P.OFFICE_NO AS officecode ,
P.NAME AS fullname ,gender ,
dob , DESIGNATION AS designation ,GAZZETTED AS ISGAZETTEDOFFICER,
BASIC_PAY AS basicpay ,
P.AC_NO AS acno ,
P.PART_NO AS partno, 
TOBEAPPOINTED AS personnelcategorycode ,
FITFOR AS SENSITIVITYCODE ,
ACCOUNTNO
FROM OFFICE O INNER JOIN  PERSONNEL P ON O.OFFICE_NO = P.OFFICE_NO 
LEFT OUTER JOIN PERSONNELACCOUNTDETAILS PAD ON P.EMPLOYEENO = PAD.EMPLOYEE_NO
) ;
SELECT * FROM PERSONNEL WHERE TRIM(UPPER(NAME)) = 'SENGKET J SANGMA';
/*

--POSTGRESQL

 ALTER TABLE "RANDOMIZE_OFFICEPERSONNEL" RENAME COLUMN  "OFFICENO" TO officeno;
 ALTER TABLE "RANDOMIZE_OFFICEPERSONNEL" RENAME COLUMN  "OFFICE_NAME" TO office_name;
 ALTER TABLE "RANDOMIZE_OFFICEPERSONNEL" RENAME COLUMN  "ADDRESS" TO address;
 ALTER TABLE "RANDOMIZE_OFFICEPERSONNEL" RENAME COLUMN  "OFFICE_HEAD" TO office_head;
 ALTER TABLE "RANDOMIZE_OFFICEPERSONNEL" RENAME COLUMN  "OFFICE_TYPE" TO office_type;
 ALTER TABLE "RANDOMIZE_OFFICEPERSONNEL" RENAME COLUMN  "EMPLOYEENO" TO employeeno;
 ALTER TABLE "RANDOMIZE_OFFICEPERSONNEL" RENAME COLUMN  "OFFICECODE" TO officecode;
 ALTER TABLE "RANDOMIZE_OFFICEPERSONNEL" RENAME COLUMN  "FULLNAME" TO fullname;
 ALTER TABLE "RANDOMIZE_OFFICEPERSONNEL" RENAME COLUMN  "GENDER" TO gender;
 ALTER TABLE "RANDOMIZE_OFFICEPERSONNEL" RENAME COLUMN  "DOB" TO dob;
 ALTER TABLE "RANDOMIZE_OFFICEPERSONNEL" RENAME COLUMN  "DESIGNATION" TO designation;
 ALTER TABLE "RANDOMIZE_OFFICEPERSONNEL" RENAME COLUMN  "BASICPAY" TO basicpay;
 ALTER TABLE "RANDOMIZE_OFFICEPERSONNEL" RENAME COLUMN  "ACNO" TO acno;
 ALTER TABLE "RANDOMIZE_OFFICEPERSONNEL" RENAME COLUMN  "PARTNO" TO partno;
 ALTER TABLE "RANDOMIZE_OFFICEPERSONNEL" RENAME COLUMN  "PERSONNELCATEGORYCODE" TO personnelcategorycode;
 ALTER TABLE "RANDOMIZE_OFFICEPERSONNEL" RENAME COLUMN  "SENSITIVITYCODE" TO sensitivitycode;

ALTER TABLE "RANDOMIZE_OFFICEPERSONNEL" RENAME TO OFFICEPERSONNEL;
*/