-- ECI DB

INSERT INTO MASTERS.POLLINGSTATIONS
SELECT 
--* 
P."AC_NO" ,  P."PART_NO" ,  "PS_SR_NO",  1,    "PS_TYPE_ENG" ,  "PS_LOC_TYPE" ,  "NAME" ,  "ADDRESS" ,  "PSBUILDING_ID" ,  "PSLOCN_NO_SECTION_ID" 
FROM IMPORTS."PART_LIST" P, IMPORTS."PS_DETAILS" PSD, IMPORTS."PS_BUILDING" PSB 
WHERE P."AC_NO" = PSD."AC_NO" AND P."PART_NO" = PSD."PART_NO"
AND PSD."AC_NO" = PSB."AC_NO" AND PSD."PS_SR_NO" = PSB."PSBUILDING_NO"
LIMIT 10 ;


-- ECI DB 

--SELECT * FROM MASTERS.ACPARTS WHERE PARTNAME LIKE '%''%'

UPDATE MASTERS.ACPARTS SET PARTNAME =  REPLACE(PARTNAME, '''', '`')  WHERE PARTNAME LIKE '%''';
UPDATE MASTERS.POLLINGSTATIONS SET PSNAME =  REPLACE(PSNAME, '''', '`')  WHERE PSNAME LIKE '%''';
UPDATE MASTERS.POLLINGSTATIONS SET PSADDRESS =  REPLACE(PSADDRESS, '''', '`')  WHERE PSADDRESS LIKE '%''';
UPDATE MASTERS.ACPARTS SET PARTNAME =  REPLACE(PARTNAME, '''', '`')  WHERE PARTNAME LIKE '%''%'
UPDATE MASTERS.POLLINGSTATIONS SET PSNAME =  REPLACE(PSNAME, '''', '`')  WHERE PSNAME LIKE '%''%';
UPDATE MASTERS.POLLINGSTATIONS SET PSADDRESS =  REPLACE(PSADDRESS, '''', '`')  WHERE PSADDRESS LIKE '%''%';
