/*
	CREATE TABLE MASTERS.ACPARTS2023 AS SELECT * FROM MASTERS.ACPARTS;
	CREATE TABLE MASTERS.POLLINGSTATIONS2023 AS SELECT * FROM MASTERS.POLLINGSTATIONS;
	CREATE TABLE MASTERS.psparameters2023 AS SELECT * FROM MASTERS.psparameters;



ALTER TABLE ELECTIONS.PERSONNEL DROP CONSTRAINT personnelfkacparts ;
ALTER TABLE MASTERS.PSPARAMETERS DROP CONSTRAINT psfkey3 ;
ALTER TABLE MASTERS.SECTORSPS DROP CONSTRAINT sectorsfk2 ;
DELETE FROM MASTERS.POLLINGSTATIONS;
DELETE FROM MASTERS.ACPARTS WHERE ACNO < 99;



ALTER TABLE elections."PART_LIST" set schema imports;
ALTER TABLE elections."PS_BUILDING" set schema imports;
ALTER TABLE elections."PS_DETAILS" set schema imports;


INSERT INTO MASTERS.ACPARTS
SELECT "AC_NO", "PART_NO", "PART_NAME_EN", "FVT_TYPE", "PS_BUILDINGS_ID", "PART_VOTER_CAPACITY",
"VILLAGES_IN_PART","MAIN_VILLAGE","PATWARI_NO","TAHSIL_NO","RI_NO" 
FROM IMPORTS."PART_LIST";

INSERT INTO MASTERS.POLLINGSTATIONS
SELECT 
P."AC_NO" ,  P."PART_NO" ,  "PS_SR_NO",  1,    "PS_TYPE_ENG" ,  "PS_LOC_TYPE" ,  "NAME" ,  "ADDRESS" ,  "PSBUILDING_ID" ,  "PSLOCN_NO_SECTION_ID" 
FROM IMPORTS."PART_LIST" P, IMPORTS."PS_DETAILS" PSD, IMPORTS."PS_BUILDING" PSB 
WHERE P."AC_NO" = PSD."AC_NO" AND P."PART_NO" = PSD."PART_NO"
AND PSD."AC_NO" = PSB."AC_NO" AND PSD."PS_SR_NO" = PSB."PSBUILDING_NO"

ALTER TABLE MASTERS.ACPARTS ADD CONSTRAINT personnelfkacparts FOREIGN KEY (acno, partno)
      REFERENCES masters.acparts (acno, partno) MATCH SIMPLE
      ON UPDATE CASCADE ON DELETE RESTRICT;

ALTER TABLE MASTERS.PSPARAMETERS ADD CONSTRAINT psfkey3 FOREIGN KEY (acno, partno)
      REFERENCES masters.acparts (acno, partno) MATCH SIMPLE
      ON UPDATE CASCADE ON DELETE RESTRICT;

ALTER TABLE MASTERS.SECTORSPS ADD CONSTRAINT sectorsfk2 FOREIGN KEY (acno, partno)
      REFERENCES masters.acparts (acno, partno) MATCH SIMPLE
      ON UPDATE CASCADE ON DELETE RESTRICT;


UPDATE MASTERS.ACPARTS SET PARTNAME =  REPLACE(PARTNAME, '''', '`')  WHERE PARTNAME LIKE '%''';

UPDATE MASTERS.POLLINGSTATIONS SET PSNAME =  REPLACE(PSNAME, '''', '`')  WHERE PSNAME LIKE '%''';

UPDATE MASTERS.POLLINGSTATIONS SET PSADDRESS =  REPLACE(PSADDRESS, '''', '`')  WHERE PSADDRESS LIKE '%''';

UPDATE MASTERS.ACPARTS SET PARTNAME =  REPLACE(PARTNAME, '''', '`')  WHERE PARTNAME LIKE '%''%'

UPDATE MASTERS.POLLINGSTATIONS SET PSNAME =  REPLACE(PSNAME, '''', '`')  WHERE PSNAME LIKE '%''%';
UPDATE MASTERS.POLLINGSTATIONS SET PSADDRESS =  REPLACE(PSADDRESS, '''', '`')  WHERE PSADDRESS LIKE '%''%';
*/      

-- POLLING STATIONS
SELECT  AC.ACNO , ACNAME , AP.PARTNO, AP.PARTNAME, PS.PSNO, PS.PSNAME,
AP1.PARTNO, AP1.PARTNAME, PS1.PSNO, PS1.PSNAME, AP.MOTORABLEDISTANCE, AP.NONMOTORABLEDISTANCE
FROM MASTERS.DISTRICTS D INNER JOIN MASTERS.ASSEMBLYCONSTITUENCIES AC ON D.DISTRICTCODE = AC.DISTRICTCODE 
INNER JOIN MASTERS.ACPARTS AP ON (AC.ACNO = AP.ACNO)
INNER JOIN MASTERS.POLLINGSTATIONS PS ON (AP.ACNO = PS.ACNO AND AP.PARTNO = PS.PARTNO)
INNER JOIN MASTERS.PSPARAMETERS PSP ON (PS.ACNO = PSP.ACNO AND PS.PARTNO = PSP.PARTNO AND PS.PSNO = PSP.PSNO)
INNER JOIN MASTERS.ACPARTS2023 AP1 ON (AC.ACNO = AP1.ACNO)
INNER JOIN MASTERS.POLLINGSTATIONS2023 PS1 ON (AP1.ACNO = PS1.ACNO AND AP1.PARTNO = PS1.PARTNO)
INNER JOIN MASTERS.PSPARAMETERS2023 PSP1 ON (PS1.ACNO = PSP1.ACNO AND PS1.PARTNO = PSP1.PARTNO AND PS1.PSNO = PSP1.PSNO)
WHERE PS.ACNO = PSP1.ACNO AND PS.PARTNO = PSP1.PARTNO AND PS.PSNO = PSP1.PSNO
AND (AP.PARTNAME <> AP1.PARTNAME OR PS.PSNAME <> PS1.PSNAME)
--ORDER BY AC.ACNO, AP.PARTNO,PS.PSNO

