/*
 ALTER TABLE "RANDOMIZE_OFFICEPERSONNEL" RENAME COLUMN  "OFFICENO" TO officeno;
 ALTER TABLE "RANDOMIZE_OFFICEPERSONNEL" RENAME COLUMN  "OFFICE_NAME" TO office_name;
 ALTER TABLE "RANDOMIZE_OFFICEPERSONNEL" RENAME COLUMN  "ADDRESS" TO address;
 ALTER TABLE "RANDOMIZE_OFFICEPERSONNEL" RENAME COLUMN  "OFFICE_HEAD" TO office_head;
 ALTER TABLE "RANDOMIZE_OFFICEPERSONNEL" RENAME COLUMN  "OFFICE_TYPE" TO office_type;
 ALTER TABLE "RANDOMIZE_OFFICEPERSONNEL" RENAME COLUMN  "EMPLOYEENO" TO employeeno;
 ALTER TABLE "RANDOMIZE_OFFICEPERSONNEL" RENAME COLUMN  "OFFICECODE" TO officecode;
 ALTER TABLE "RANDOMIZE_OFFICEPERSONNEL" RENAME COLUMN  "FULLNAME" TO fullname;
 ALTER TABLE "RANDOMIZE_OFFICEPERSONNEL" RENAME COLUMN  "GENDER" TO gender;
 ALTER TABLE "RANDOMIZE_OFFICEPERSONNEL" RENAME COLUMN  "DOB" TO dob;
 ALTER TABLE "RANDOMIZE_OFFICEPERSONNEL" RENAME COLUMN  "DESIGNATION" TO designation;
 ALTER TABLE "RANDOMIZE_OFFICEPERSONNEL" RENAME COLUMN  "BASICPAY" TO basicpay;
 ALTER TABLE "RANDOMIZE_OFFICEPERSONNEL" RENAME COLUMN  "ACNO" TO acno;
 ALTER TABLE "RANDOMIZE_OFFICEPERSONNEL" RENAME COLUMN  "PARTNO" TO partno;
 ALTER TABLE "RANDOMIZE_OFFICEPERSONNEL" RENAME COLUMN  "PERSONNELCATEGORYCODE" TO personnelcategorycode;
 ALTER TABLE "RANDOMIZE_OFFICEPERSONNEL" RENAME COLUMN  "SENSITIVITYCODE" TO sensitivitycode;
 ALTER TABLE "RANDOMIZE_OFFICEPERSONNEL" RENAME COLUMN  "ISGAZETTEDOFFICER" TO isgazettedofficer;
 ALTER TABLE "RANDOMIZE_OFFICEPERSONNEL" RENAME COLUMN  "ACCOUNTNO" TO ACCOUNTNO;
 
 ALTER TABLE "RANDOMIZE_OFFICEPERSONNEL" RENAME TO OFFICEPERSONNEL;
*/

--SELECT * FROM INFORMATION_SCHEMA.COLUMNS WHERE TABLE_NAME = 'offices'; 
--SELECT * FROM INFORMATION_SCHEMA.COLUMNS WHERE TABLE_NAME = 'personnel'; 
--SELECT MAX(OFFICESLNO)+1 FROM MASTERS.OFFICES WHERE DISTRICTCODE = 4;
--SELECT * FROM MASTERS.OFFICES WHERE DISTRICTCODE = 4;

DROP TABLE IF EXISTS OFFICESORCL ;

CREATE TABLE OFFICESORCL  AS
SELECT 4 AS DISTRICTCODE, /*DISTRICTCODE*/
ROW_NUMBER() OVER() + (SELECT MAX(OFFICESLNO)   FROM MASTERS.OFFICES WHERE DISTRICTCODE = 4/*DISTRICTCODE*/)
AS OFFICESLNO,
LPAD(/*DISTRICTCODE*/4::TEXT,2,'0') || LPAD( (
ROW_NUMBER() OVER() + (SELECT MAX(OFFICESLNO)   FROM MASTERS.OFFICES WHERE DISTRICTCODE = 4/*DISTRICTCODE*/)
)::TEXT, 4,'0'      ) AS OFFICECODE,
TRIM(UPPER(office_name)) AS officename,
office_name || 4 /*DISTRICTCODE*/ AS header1,office_name AS header2,office_name AS header3,address AS OFFICEADDRESS,
OFFICE_TYPE AS officecategorycode,'-'::TEXT  AS signatoryname,OFFICE_HEAD AS signatorydesignation,'N'::TEXT AS iselectionoffice,
'040001'::TEXT /*REFERENCEOFFICECODE*/
AS referenceofficecode,'Y'::TEXT AS enabled, 
NULL::BYTEA AS signature,
'-'::TEXT AS officeabbreviation,1::SMALLINT,
CURRENT_TIMESTAMP AS entrydate
FROM (SELECT DISTINCT OFFICE_NAME,  ADDRESS, OFFICE_HEAD, OFFICE_TYPE FROM OFFICEPERSONNEL) OFFICES
ORDER BY TRIM(UPPER(OFFICE_NAME));

INSERT INTO MASTERS.OFFICES SELECT * FROM OFFICESORCL ORDER BY OFFICECODE;
--DELETE  FROM MASTERS.OFFICES WHERE DISTRICTCODE = 4 AND ISELECTIONOFFICE='N';
SELECT * FROM PERSONNEL LIMIT 10 ;


DROP TABLE IF EXISTS PERSONNELORCL ;

CREATE TABLE PERSONNELORCL  AS
SELECT 
O.OFFICECODE, 
ROW_NUMBER() OVER(ORDER BY TRIM(UPPER(O.OFFICENAME)) , TRIM(UPPER(FULLNAME))) AS SLNO,
O.OFFICECODE || 
LPAD( ROW_NUMBER() OVER(ORDER BY TRIM(UPPER(O.OFFICENAME)) , TRIM(UPPER(FULLNAME)))::TEXT, 5,'0') 
AS employeecode,
fullname,
CASE WHEN GENDER='F' THEN 'FEMALE' ELSE 'MALE' END AS GENDER,
DOB,DESIGNATION,BASICPAY, 
ACCOUNTNO AS ACCOUNTNO,
NULL::TEXT AS IFSCCODE,
ISGAZETTEDOFFICER,
''::TEXT AS epiccardno,
acno, partno,NULL::TEXT AS mobileno,
NULL::TEXT AS mobilenosm,
'N'::TEXT AS isblo,
'N'::TEXT AS ispwd,
NULL::TEXT AS pwddetails,
'N'::TEXT AS isexpectinglactating,
'N'::TEXT AS isailing,
personnelcategorycode,
sensitivitycode,
NULL::BYTEA AS photograph,
CURRENT_TIMESTAMP,
1
FROM ELECTIONS.OFFICESORCL O, ELECTIONS.OFFICEPERSONNEL P WHERE TRIM(UPPER(O.OFFICENAME)) = TRIM(UPPER(P.OFFICE_NAME)) 
ORDER BY TRIM(UPPER(O.OFFICENAME)) , TRIM(UPPER(FULLNAME));



UPDATE ELECTIONS.PERSONNELORCL SET ACNO = 99, PARTNO = 99 WHERE ACNO IN (111,999) ;
delete FROM PERSONNELORCL WHERE DOB <='1956-01-01'
INSERT INTO ELECTIONS.PERSONNEL SELECT * FROM PERSONNELORCL;

SELECT TRIM(UPPER(FULLNAME)), DOB  FROM PERSONNELORCL GROUP BY TRIM(UPPER(FULLNAME)), DOB HAVING COUNT(*) > 1;

SELECT * FROM PERSONNEL WHERE EMPLOYEECODE LIKE '04%' ;

