
/*
-- OFFICES 

INSERT INTO MASTERS.OFFICES
SELECT  DISTINCT DISTRICTCODE, 
ROW_NUMBER() OVER() + (SELECT MAX(OFFICESLNO) FROM MASTERS.OFFICES WHERE DISTRICTCODE = S.DISTRICTCODE) AS OFFICESLNO, 
LPAD(DISTRICTCODE::TEXT, 2, '0') ||  LPAD( (ROW_NUMBER() OVER() + (SELECT MAX(OFFICESLNO) FROM MASTERS.OFFICES WHERE DISTRICTCODE = S.DISTRICTCODE))::TEXT, 4, '0')
AS OFFICECODE, 
OFFICENAME, 
TRIM(UPPER(OFFICENAME)) AS HEADER1, TRIM(UPPER(DISTRICTNAME)) AS HEADER2, '-' AS HEADER3, '' AS OFFICEADDRESS, 1  AS OFFICECATEGORYCODE, 
'-' AS SIGNATORYNAME, '-' AS SIGNATORYDESIGNATION, 'N' AS ISELECTIONOFFICE, 
 LPAD(S.DISTRICTCODE::TEXT, 2, '0')  || '0001' AS REFERENCEOFFICECODE, 
'Y' AS ENDABLED 
FROM 
	(SELECT  DISTINCT DS.DISTRICTCODE, UPPER(TRIM(OFFICENAME)) AS OFFICENAME, UPPER(TRIM(E.DISTRICTNAME)) AS DISTRICTNAME
	FROM (SELECT DISTINCT D.DISTRICTLGDCODE, D.DISTRICTNAME, O.DISTRICTCODE FROM MASTERS.DISTRICTS D, MASTERS.OFFICES O WHERE D.DISTRICTCODE = O.DISTRICTCODE) DS
	INNER JOIN IMPORTS.EMPLOYEESDB E ON E.DISTRICTCODE = DS.DISTRICTLGDCODE::SMALLINT 
) S
WHERE (DISTRICTCODE, UPPER(TRIM(OFFICENAME)))  NOT IN (SELECT DISTRICTCODE, UPPER(TRIM(OFFICENAME)) FROM MASTERS.OFFICES)

--AND TRIM(UPPER(OFFICENAME)) <> 'MAWKYRWAT POLICE STATION'


*/

--
--SELECT * FROM MASTERS.OFFICES

--SELECT * FROM IMPORTS.EMPLOYEESDB ;
INSERT INTO PERSONNEL 
SELECT O.OFFICECODE,
ROW_NUMBER() OVER(PARTITION BY O.OFFICECODE  ORDER BY O.DISTRICTCODE, O.OFFICECODE ) , 
 O.OFFICECODE || ROW_NUMBER() OVER()   AS EMPLOYEECODE,
EMPLOYEENAME AS FULLNAME,
CASE WHEN GENDER='M' THEN 'MALE' WHEN GENDER='F' THEN 'FEMALE' END AS GENDER,
TO_DATE(DOB,'DD/MM/YYYY') AS DOB,
DESIGNATION,
TO_DATE(DOB,'DD/MM/YYYY') + 21170 AS DOS,
'N' AS ISGAZETTEDOFFICER,
BASICPAY::INTEGER,
99 AS ACNO,
99 AS PARTNO,
'N' AS ISPWD,
'N' AS ISPREGNANT,
'N' AS ISLACTATING,
'N' AS ISAILING,
0  AS EXPERIENCEPRESIDING,
0  AS EXPERIENCEPOLLING,
0  AS EXPERIENCECOUNTINGS,
0  AS EXPERIENCECOUNTINGA,
1 AS PERSONNELCATEGORYCODE,
1 AS SENSITIVITYCODE,
ROW_NUMBER() OVER() AS MOBILENO,
ROW_NUMBER() OVER() AS  MOBILENOSM,
ACCOUNTNO,
TRIM(IFSCCODE),
NULL AS PHOTOGRAPH
FROM IMPORTS.EMPLOYEESDB E INNER JOIN MASTERS.OFFICES O ON UPPER(TRIM(E.OFFICENAME)) = UPPER(TRIM(O.OFFICENAME))
WHERE 1 =1 

ORDER BY O.DISTRICTCODE, O.OFFICECODE




