/*
SELECT O.OFFICECODE, O.OFFICENAME, CV.VENUECODE, CV.VENUEDESCRIPTION, CH.HALLCODE, CH.HALLNO , TABLENO
FROM MASTERS.OFFICES O INNER JOIN COUNTINGVENUES CV ON O.OFFICECODE = CV.OFFICECODE 
INNER JOIN COUNTINGHALLS CH ON CV.VENUECODE = CH.VENUECODE
INNER JOIN COUNTINGTABLES CT ON CH.HALLCODE = CT.HALLCODE 
WHERE O.OFFICECODE = '030001'
ORDER BY O.OFFICECODE, CV.VENUECODE, CV.VENUEDESCRIPTION, HALLNO, TABLENO;



SELECT EO.OFFICENAME, PERSONNELCATEGORYDESCRIPTION, COUNT(*)
FROM MASTERS.DISTRICTS D INNER JOIN MASTERS.OFFICES EO ON D.DISTRICTCODE = EO.DISTRICTCODE
INNER JOIN MASTERS.OFFICES O ON EO.OFFICECODE = O.REFERENCEOFFICECODE
INNER JOIN MASTERS.MASTERTABLE M ON EO.OFFICECODE = M.OFFICECODE
INNER JOIN VWPERSONNEL P ON O.OFFICECODE  = P.OFFICECODE
INNER JOIN MASTERS.PERSONNELCATEGORIES PC ON PC.PERSONNELCATEGORYCODE = P.PERSONNELCATEGORYCODE
INNER JOIN COUNTINGALLOCATION2 PA2 ON (P.EMPLOYEECODE = PA2.EMPLOYEECODE AND P.PERSONNELCATEGORYCODE = PA2.PERSONNELCATEGORYCODE)
INNER JOIN COUNTINGTABLES CT ON (CT.HALLCODE = PA2.HALLCODE AND CT.TABLENO = PA2.PROVISIONALTABLENO)
INNER JOIN COUNTINGHALLS CH ON CH.HALLCODE = CT.HALLCODE
INNER JOIN COUNTINGVENUES CV ON (CV.VENUECODE = CH.VENUECODE AND EO.OFFICECODE = CV.OFFICECODE )
WHERE 1 = 1
--AND $X{IN, EO.OFFICECODE, electionoffice}
GROUP BY EO.OFFICENAME, PERSONNELCATEGORYDESCRIPTION
ORDER BY EO.OFFICENAME, PERSONNELCATEGORYDESCRIPTION;




SELECT EO.OFFICENAME, PERSONNELCATEGORYDESCRIPTION,COUNT(*)
FROM MASTERS.DISTRICTS D INNER JOIN MASTERS.OFFICES EO ON D.DISTRICTCODE = EO.DISTRICTCODE
INNER JOIN MASTERS.OFFICES O ON EO.OFFICECODE = O.REFERENCEOFFICECODE
INNER JOIN MASTERS.MASTERTABLE M ON EO.OFFICECODE = M.OFFICECODE
INNER JOIN VWPERSONNEL P ON O.OFFICECODE  = P.OFFICECODE
INNER JOIN MASTERS.PERSONNELCATEGORIES PC ON PC.PERSONNELCATEGORYCODE = P.PERSONNELCATEGORYCODE
INNER JOIN MASTERS.RNDCOUNTINGCATEGORIESMAP CM ON (EO.OFFICECODE = CM.OFFICECODE AND PC.PERSONNELCATEGORYCODE = CM.PERSONNELCATEGORYCODE)
WHERE CM.FLAGCODE = 'R'
GROUP BY EO.OFFICENAME, PERSONNELCATEGORYDESCRIPTION
ORDER BY EO.OFFICENAME, PERSONNELCATEGORYDESCRIPTION
*/



SELECT PERSONNELCATEGORYDESCRIPTION, P.EMPLOYEECODE, CASE WHEN GENDER='MALE' THEN 'Shri. ' || INITCAP(FULLNAME) WHEN GENDER='FEMALE' THEN 'Smt./Kum. ' || INITCAP(FULLNAME) END AS FULLNAME, DESIGNATION, O.OFFICENAME AS OFFICENAME, 
MOBILENO, VENUEDESCRIPTION, HALLNO::TEXT, HALLDESCRIPTION, CT.TABLENO::TEXT
FROM MASTERS.OFFICES EO 
INNER JOIN MASTERS.OFFICES O ON EO.OFFICECODE = O.REFERENCEOFFICECODE
INNER JOIN VWPERSONNEL P ON O.OFFICECODE  = P.OFFICECODE
INNER JOIN MASTERS.PERSONNELCATEGORIES PC ON PC.PERSONNELCATEGORYCODE = P.PERSONNELCATEGORYCODE
INNER JOIN COUNTINGALLOCATION3 PA2 ON (P.EMPLOYEECODE = PA2.EMPLOYEECODE AND P.PERSONNELCATEGORYCODE = PA2.PERSONNELCATEGORYCODE)
INNER JOIN COUNTINGTABLES CT ON (CT.HALLCODE = PA2.HALLCODE AND CT.TABLENO = PA2.TABLENO)
INNER JOIN COUNTINGHALLS CH ON CH.HALLCODE = CT.HALLCODE
INNER JOIN COUNTINGVENUES CV ON (CV.VENUECODE = CH.VENUECODE AND EO.OFFICECODE = CV.OFFICECODE )
WHERE 1 = 1 AND EO.OFFICECODE ='030001' 

UNION ALL 

SELECT 
PERSONNELCATEGORYDESCRIPTION, P.EMPLOYEECODE, CASE WHEN GENDER='MALE' THEN 'Shri. ' || INITCAP(FULLNAME) WHEN GENDER='FEMALE' THEN 'Smt./Kum. ' || INITCAP(FULLNAME) END AS FULLNAME, DESIGNATION, O.OFFICENAME AS OFFICENAME, 
MOBILENO, VENUEDESCRIPTION, 'RESERVE' HALLNO, 'RESERVE' HALLDESCRIPTION, 'RESERVE' AS TABLENO
FROM MASTERS.DISTRICTS D INNER JOIN MASTERS.OFFICES EO ON D.DISTRICTCODE = EO.DISTRICTCODE
INNER JOIN MASTERS.OFFICES O ON EO.OFFICECODE = O.REFERENCEOFFICECODE
INNER JOIN COUNTINGVENUES CV ON EO.OFFICECODE = CV.OFFICECODE
INNER JOIN VWPERSONNEL P ON O.OFFICECODE  = P.OFFICECODE
INNER JOIN MASTERS.PERSONNELCATEGORIES PC ON PC.PERSONNELCATEGORYCODE = P.PERSONNELCATEGORYCODE
INNER JOIN MASTERS.RNDCOUNTINGCATEGORIESMAP RM ON (EO.OFFICECODE = RM.OFFICECODE AND PC.PERSONNELCATEGORYCODE = RM.PERSONNELCATEGORYCODE)
INNER JOIN COUNTINGRESERVES R ON (P.EMPLOYEECODE = R.EMPLOYEECODE)
WHERE 1 = 1
AND EO.OFFICECODE = '030001' 
UNION ALL 
SELECT 
PERSONNELCATEGORYDESCRIPTION, P.EMPLOYEECODE, CASE WHEN GENDER='MALE' THEN 'Shri. ' || INITCAP(FULLNAME) WHEN GENDER='FEMALE' THEN 'Smt./Kum. ' || INITCAP(FULLNAME) END AS FULLNAME, DESIGNATION, O.OFFICENAME AS OFFICENAME, 
MOBILENO, VENUEDESCRIPTION, 'UNALLOCATED' HALLNO, 'UNALLOCATED' HALLDESCRIPTION, 'UNALLOCATED' AS TABLENO

FROM MASTERS.OFFICES EO INNER JOIN MASTERS.OFFICES O ON EO.OFFICECODE = O.REFERENCEOFFICECODE 
INNER JOIN COUNTINGVENUES CV ON EO.OFFICECODE = CV.OFFICECODE
INNER JOIN VWPERSONNEL P ON O.OFFICECODE  = P.OFFICECODE 
INNER JOIN MASTERS.PERSONNELCATEGORIES PC ON PC.PERSONNELCATEGORYCODE = P.PERSONNELCATEGORYCODE 
INNER JOIN MASTERS.RNDCOUNTINGCATEGORIESMAP M ON (EO.OFFICECODE = M.OFFICECODE  AND P.PERSONNELCATEGORYCODE = M.PERSONNELCATEGORYCODE) 
WHERE M.FLAGCODE ='R' AND EO.OFFICECODE = '030001'  
AND P.EMPLOYEECODE NOT IN (SELECT EMPLOYEECODE FROM COUNTINGALLOCATION3) 
AND P.EMPLOYEECODE NOT IN (SELECT EMPLOYEECODE FROM COUNTINGRESERVES) 


