/*
RAW INPUT FOR TESTING ONLY
DELETE FROM  ELECTIONS.TRAININGPERSONNEL;
INSERT INTO ELECTIONS.TRAININGPERSONNEL
SELECT '030001002P010002', EMPLOYEECODE , 'SQL Insert', 1, now() FROM 
MASTERS.OFFICES O, ELECTIONS.PERSONNEL P 
WHERE O.OFFICECODE = P.OFFICECODE 
AND O.OFFICECODE IN (SELECT OFFICECODE FROM MASTERS.OFFICES WHERE REFERENCEOFFICECODE = '030001')
AND PERSONNELCATEGORYCODE IN (1, 2, 3, 4)
ORDER BY O.OFFICENAME, FULLNAME
LIMIT 100 ;



SELECT COUNT(*) FROM ELECTIONS.PERSONNEL WHERE OFFICECODE IN (SELECT OFFICECODE FROM MASTERS.OFFICES WHERE REFERENCEOFFICECODE = '030001') 
AND PERSONNELCATEGORYCODE IN (1, 2, 3, 4);



SELECT PERSONNELCATEGORYCODE, COUNT(*) FROM ELECTIONS.PERSONNEL WHERE OFFICECODE IN (SELECT OFFICECODE FROM MASTERS.OFFICES WHERE REFERENCEOFFICECODE = '030001') 
AND PERSONNELCATEGORYCODE IN (1, 2, 3, 4)
AND EMPLOYEECODE NOT IN (SELECT EMPLOYEECODE FROM TRAININGPERSONNEL)
GROUP BY PERSONNELCATEGORYCODE
ORDER BY PERSONNELCATEGORYCODE ;
;

*/

/*
--SUMMARY
SELECT EO.OFFICENAME, TRAININGTYPEDESCRIPTION, TP.PHASENO, 
TS.SESSIONCODE,  
TO_CHAR(TS.TRAININGDATE,'DD-MM-YYYY') AS TRAININGDATE, 
TO_CHAR(STARTTIME,'HH:MM AM') || ' - '  || TO_CHAR(ENDTIME,'HH:MM AM') AS TIMINGS, 
VENUEDESCRIPTION, 
PERSONNELCATEGORYDESCRIPTION, 
COUNT(*) AS TOTAL 
FROM MASTERS.OFFICES EO INNER JOIN MASTERS.OFFICES O ON EO.OFFICECODE  = O.REFERENCEOFFICECODE 
INNER JOIN MASTERS.MASTERTABLE M ON EO.OFFICECODE = M.OFFICECODE
INNER JOIN ELECTIONS.PERSONNEL P ON O.OFFICECODE = P.OFFICECODE
INNER JOIN MASTERS.PERSONNELCATEGORIES C ON C.PERSONNELCATEGORYCODE = P.PERSONNELCATEGORYCODE
INNER JOIN TRAININGPHASES TP ON EO.OFFICECODE = TP.OFFICECODE 
INNER JOIN TRAININGTYPES TT ON TP.TRAININGTYPECODE = TT.TRAININGTYPECODE 
INNER JOIN TRAININGVENUES TV ON TP.OFFICECODE = TV.OFFICECODE 
INNER JOIN TRAININGSESSIONS TS ON (EO.OFFICECODE = TS.OFFICECODE AND TP.TRAININGTYPECODE = TS.TRAININGTYPECODE AND TP.PHASENO = TS.PHASENO  AND  TV.VENUECODE = TS.VENUECODE)
INNER JOIN TRAININGPERSONNEL TPER ON (TS.SESSIONCODE = TPER.SESSIONCODE AND P.EMPLOYEECODE = TPER.EMPLOYEECODE)
WHERE 1 = 1 
AND EO.OFFICECODE = '030001'
--AND TP.PHASENO = 1 
GROUP BY EO.OFFICENAME, TRAININGTYPEDESCRIPTION, TP.PHASENO, TS.SESSIONCODE, TS.TRAININGDATE , STARTTIME, ENDTIME, VENUEDESCRIPTION, PERSONNELCATEGORYDESCRIPTION
ORDER BY EO.OFFICENAME, TRAININGTYPEDESCRIPTION, TP.PHASENO, TS.TRAININGDATE , STARTTIME, ENDTIME, VENUEDESCRIPTION, PERSONNELCATEGORYDESCRIPTION
*/









SELECT COUNT(*) FROM ELECTIONS.PERSONNEL WHERE OFFICECODE IN (SELECT OFFICECODE FROM MASTERS.OFFICES WHERE REFERENCEOFFICECODE = '030001')  AND PERSONNELCATEGORYCODE IN (1, 2, 3, 4);

--QUERY TO INSERT IN THE CODE


INSERT INTO ELECTIONS.TRAININGPERSONNEL
SELECT '030001001P010001', P.EMPLOYEECODE , 'SQL Insert', 1, now() 
FROM MASTERS.OFFICES EO INNER JOIN MASTERS.OFFICES O ON EO.OFFICECODE  = O.REFERENCEOFFICECODE 
INNER JOIN ELECTIONS.PERSONNEL P ON O.OFFICECODE = P.OFFICECODE
WHERE 1 = 1 AND EO.OFFICECODE = '030001' AND PERSONNELCATEGORYCODE IN (1, 2, 3, 4)
AND P.EMPLOYEECODE NOT IN (
SELECT P.EMPLOYEECODE
FROM MASTERS.OFFICES EO INNER JOIN MASTERS.OFFICES O ON EO.OFFICECODE  = O.REFERENCEOFFICECODE 
INNER JOIN ELECTIONS.PERSONNEL P ON O.OFFICECODE = P.OFFICECODE
INNER JOIN TRAININGPHASES TP ON EO.OFFICECODE = TP.OFFICECODE 
INNER JOIN TRAININGTYPES TT ON TP.TRAININGTYPECODE = TT.TRAININGTYPECODE 
INNER JOIN TRAININGVENUES TV ON EO.OFFICECODE = TV.OFFICECODE 
INNER JOIN TRAININGSESSIONS TS ON (EO.OFFICECODE = TS.OFFICECODE AND TP.TRAININGTYPECODE = TS.TRAININGTYPECODE AND TP.PHASENO = TS.PHASENO  AND  TV.VENUECODE = TS.VENUECODE)
INNER JOIN TRAININGPERSONNEL TPER ON (TS.SESSIONCODE = TPER.SESSIONCODE AND P.EMPLOYEECODE = TPER.EMPLOYEECODE)
WHERE 1 = 1 AND EO.OFFICECODE = '030001' AND TT.TRAININGTYPECODE = 'P' AND TP.PHASENO = 1 
)
ORDER BY EO.OFFICENAME, O.OFFICENAME, P.FULLNAME 



--NOT ASSIGNED TRAINING
SELECT EO.OFFICECODE, EO.OFFICENAME , P.EMPLOYEECODE, FULLNAME, PERSONNELCATEGORYDESCRIPTION
FROM MASTERS.OFFICES EO INNER JOIN MASTERS.OFFICES O ON EO.OFFICECODE  = O.REFERENCEOFFICECODE  
INNER JOIN ELECTIONS.VWPERSONNEL P ON O.OFFICECODE = P.OFFICECODE  
INNER JOIN MASTERS.PERSONNELCATEGORIES PC ON PC.PERSONNELCATEGORYCODE = P.PERSONNELCATEGORYCODE 
WHERE EO.OFFICECODE = '030001' AND P.PERSONNELCATEGORYCODE IN (1, 2, 3, 4) 
AND P.EMPLOYEECODE NOT IN 
(
SELECT TPER.EMPLOYEECODE
FROM MASTERS.OFFICES EO INNER JOIN MASTERS.OFFICES O ON EO.OFFICECODE  = O.REFERENCEOFFICECODE  
INNER JOIN ELECTIONS.VWPERSONNEL P ON O.OFFICECODE = P.OFFICECODE  
INNER JOIN ELECTIONS.TRAININGPHASES TP ON EO.OFFICECODE = TP.OFFICECODE  
INNER JOIN ELECTIONS.TRAININGTYPES TT ON TP.TRAININGTYPECODE = TT.TRAININGTYPECODE  
INNER JOIN ELECTIONS.TRAININGVENUES TV ON TP.OFFICECODE = TV.OFFICECODE  
INNER JOIN ELECTIONS.TRAININGSESSIONS TS ON  
(EO.OFFICECODE = TS.OFFICECODE AND TP.TRAININGTYPECODE = TS.TRAININGTYPECODE AND TP.PHASENO = TS.PHASENO  AND  TV.VENUECODE = TS.VENUECODE)  
INNER JOIN ELECTIONS.TRAININGPERSONNEL TPER ON (TS.SESSIONCODE = TPER.SESSIONCODE AND P.EMPLOYEECODE = TPER.EMPLOYEECODE)  
WHERE 1 = 1 AND EO.OFFICECODE = '030001'  AND TP.PHASENO = 1 AND P.PERSONNELCATEGORYCODE IN (1, 2, 3, 4) 
) 
--ORDER BY P1.OFFICECODE, P1.OFFICENAME , P2.TRAININGTYPECODE, P2.TRAININGTYPEDESCRIPTION, P2.PHASENO





-- PERSONNEL ALLOCATED TRAINING BUT TOBEAPPOINTEDAS HAS CHANGED
SELECT TPER.ACTIONDATE, TP.PHASENO, TRAININGTYPEDESCRIPTION, 
TS.SESSIONCODE, 
TO_CHAR(TS.TRAININGDATE,'DD-MM-YYYY') AS TRAININGDATE, TO_CHAR(STARTTIME,'HH:MI AM') || ' - '  || TO_CHAR(ENDTIME,'HH:MI AM') AS TIMINGS, VENUEDESCRIPTION, PERSONNELCATEGORYDESCRIPTION, 
P.EMPLOYEECODE, UPPER(TRIM(FULLNAME)) AS FULLNAME, DESIGNATION, O.OFFICENAME
FROM MASTERS.DISTRICTS D INNER JOIN MASTERS.OFFICES EO ON D.DISTRICTCODE = EO.DISTRICTCODE INNER JOIN MASTERS.OFFICES O ON EO.OFFICECODE  = O.REFERENCEOFFICECODE
INNER JOIN MASTERS.MASTERTABLE M ON EO.OFFICECODE = M.OFFICECODE
INNER JOIN ELECTIONS.VWPERSONNEL P ON O.OFFICECODE = P.OFFICECODE
INNER JOIN MASTERS.PERSONNELCATEGORIES C ON C.PERSONNELCATEGORYCODE = P.PERSONNELCATEGORYCODE
INNER JOIN TRAININGPHASES TP ON EO.OFFICECODE = TP.OFFICECODE
INNER JOIN TRAININGTYPES TT ON TP.TRAININGTYPECODE = TT.TRAININGTYPECODE
INNER JOIN TRAININGVENUES TV ON TP.OFFICECODE = TV.OFFICECODE
INNER JOIN TRAININGLETTERNOFORMAT TF ON (EO.OFFICECODE = TF.OFFICECODE AND TP.TRAININGTYPECODE = TF.TRAININGTYPECODE AND TP.PHASENO = TF.PHASENO )
INNER JOIN TRAININGSESSIONS TS ON (EO.OFFICECODE = TS.OFFICECODE AND TP.TRAININGTYPECODE = TS.TRAININGTYPECODE AND TP.PHASENO = TS.PHASENO  AND  TV.VENUECODE = TS.VENUECODE)
INNER JOIN LOGS.TRAININGPERSONNEL TPER ON (TS.SESSIONCODE = TPER.SESSIONCODE AND P.EMPLOYEECODE = TPER.EMPLOYEECODE)
WHERE 1 = 1 
AND EO.OFFICECODE ='030001'
AND TP.PHASENO = 1
AND TT.TRAININGTYPECODE ='P'
AND P.EMPLOYEECODE IN (SELECT EMPLOYEECODE FROM LOGS.PERSONNEL)
--AND P.EMPLOYEECODE NOT IN (SELECT EMPLOYEECODE FROM TRAININGPERSONNEL)
AND P.PERSONNELCATEGORYCODE IN (1, 2, 3, 4)
--AND TO_CHAR(TPER.ACTIONDATE,'YYYY-MM-DD') = '2024-03-16'
ORDER BY TPER.ACTIONDATE DESC, EO.OFFICENAME, TRAININGTYPEDESCRIPTION, TP.PHASENO, TS.TRAININGDATE , VENUEDESCRIPTION, STARTTIME, ENDTIME, FULLNAME
