/*
SELECT ACNO, PARTNO, SECTIONNO, SLNOINPART,  FIRSTNAME, LASTNAME, EPICCARDNO, GENDER, HOUSENO, RELATIONTYPE, DOB, AGE, RELATIONFIRSTNAME, RELATIONLASTNAME FROM EROLLS.ELECTORALROLLS ER WHERE 1 = 1  
AND (ACNO, PARTNO, SLNOINPART) NOT IN (SELECT ACNO, PARTNO, SLNOINPART FROM EROLLS.ELECTORALROLLSSUP S WHERE REVISIONNO = 1 AND ACNO = 18 AND PARTNO = 16 AND STATUSTYPE IN ('D','M'))

UNION ALL 

SELECT ACNO, PARTNO, SECTIONNO, SLNOINPART,  FIRSTNAME, LASTNAME, EPICCARDNO, GENDER, HOUSENO, RELATIONTYPE, DOB, AGE, RELATIONFIRSTNAME, RELATIONLASTNAME FROM EROLLS.ELECTORALROLLSSUP S WHERE REVISIONNO = 1 AND ACNO = 18 AND PARTNO = 16 AND STATUSTYPE='N'

UNION ALL 

SELECT ACNO, PARTNO, SECTIONNO, SLNOINPART,  FIRSTNAME, LASTNAME, EPICCARDNO, GENDER, HOUSENO, RELATIONTYPE, DOB, AGE, RELATIONFIRSTNAME, RELATIONLASTNAME FROM EROLLS.ELECTORALROLLSSUP S WHERE REVISIONNO = 1 AND ACNO = 18 AND PARTNO = 16 AND STATUSTYPE='M'
*/

SELECT ACNO, PARTNO, SECTIONNO, SLNOINPART,  FIRSTNAME, LASTNAME, EPICCARDNO, GENDER, HOUSENO, RELATIONTYPE, DOB, AGE, RELATIONFIRSTNAME, RELATIONLASTNAME FROM EROLLS.ELECTORALROLLS ER WHERE ACNO = 18 AND PARTNO = 16 
AND (ACNO, PARTNO, SLNOINPART) NOT IN (SELECT ACNO, PARTNO, SLNOINPART FROM EROLLS.ELECTORALROLLSSUP S WHERE REVISIONNO = 1 AND ACNO = 18 AND PARTNO = 16 AND STATUSTYPE IN ('D','M'))

UNION ALL 

SELECT ACNO, PARTNO, SECTIONNO, SLNOINPART,  FIRSTNAME, LASTNAME, EPICCARDNO, GENDER, HOUSENO, RELATIONTYPE, DOB, AGE, RELATIONFIRSTNAME, RELATIONLASTNAME FROM EROLLS.ELECTORALROLLSSUP S WHERE REVISIONNO = 1 AND ACNO = 18 AND PARTNO = 16 AND STATUSTYPE='N'

UNION ALL 

SELECT ACNO, PARTNO, SECTIONNO, SLNOINPART,  FIRSTNAME, LASTNAME, EPICCARDNO, GENDER, HOUSENO, RELATIONTYPE, DOB, AGE, RELATIONFIRSTNAME, RELATIONLASTNAME FROM EROLLS.ELECTORALROLLSSUP S WHERE REVISIONNO = 1 AND ACNO = 18 AND PARTNO = 16 AND STATUSTYPE='M'
