-- MOTHER ROLL
SELECT EINR.ACNO, EINR.PARTNO, EINR.SECTIONNO, EINR.SLNOINPART, EINR.EPICCARDNO, EINR.HOUSENO, EINR.REVISIONNO, SRC.PHOTO 
FROM EROLLS.ELECTORALROLLS EINR
INNER JOIN SOURCES.SOURCEELECTORALROLLS SRC ON SRC.ASSEMBLY_CONSTITUENCY_NUMBER = EINR.SOURCEACNO AND SRC.PART_NUMBER = EINR.SOURCEPARTNO AND SRC.PART_SERIAL_NUMBER = EINR.SOURCESLNOINPART
WHERE EINR.ACNO = $P{acno} AND EINR.PARTNO = $P{partno}
-- MOTHER ROLL

UNION ALL 
-- FORM 6 
SELECT S.ACNO, S.PARTNO, S.SECTIONNO, S.SLNOINPART, S.EPICCARDNO, S.HOUSENO, S.REVISIONNO, PHOTO 
FROM EROLLS.ELECTORALROLLSSUP S 
INNER JOIN MASTERS.ELECTORALROLLREVISIONS RV ON RV.REVISIONNO = S.REVISIONNO 
WHERE S.STATUSTYPE='N' AND FORMTYPE='F6' AND S.ACNO = $P{acno} AND S.PARTNO = $P{partno}

UNION ALL


--SUP1 FORM 6E/8A STATUS ='N' AND ALREADY EXISTING IN MOTHER ROLL
SELECT S.ACNO, S.PARTNO, S.SECTIONNO, S.SLNOINPART, S.EPICCARDNO, S.HOUSENO, S.REVISIONNO, SRC.PHOTO
FROM EROLLS.ELECTORALROLLS ER 
INNER JOIN EROLLS.ELECTORALROLLSSUP S ON (ER.ACNO = S.SOURCEACNO AND ER.PARTNO = S.SOURCEPARTNO AND ER.SLNOINPART = S.SOURCESLNOINPART)
INNER JOIN SOURCES.SOURCEELECTORALROLLS SRC ON (SRC.ASSEMBLY_CONSTITUENCY_NUMBER = ER.SOURCEACNO AND SRC.PART_NUMBER = ER.SOURCEPARTNO AND SRC.PART_SERIAL_NUMBER = ER.SOURCESLNOINPART)
INNER JOIN MASTERS.ELECTORALROLLREVISIONS RV ON RV.REVISIONNO = S.REVISIONNO
WHERE S.STATUSTYPE='N' AND S.ACNO = $P{acno} AND S.PARTNO = $P{partno} AND S.REVISIONNO = 1
--SUP1 FORM 6E/8A STATUS ='N' AND ALREADY EXISTING IN MOTHER ROLL


UNION ALL

--SUP2  EXIST IN MOTHER ROLL AND NOT IN SUP1 FORM 6E/8A STATUS ='N' 
SELECT S.ACNO, S.PARTNO, S.SECTIONNO, S.SLNOINPART, S.EPICCARDNO, S.HOUSENO, S.REVISIONNO, SRC.PHOTO
FROM EROLLS.ELECTORALROLLS ER 
INNER JOIN EROLLS.ELECTORALROLLSSUP S ON (ER.ACNO = S.SOURCEACNO AND ER.PARTNO = S.SOURCEPARTNO AND ER.SLNOINPART = S.SOURCESLNOINPART)
INNER JOIN SOURCES.SOURCEELECTORALROLLS SRC ON (SRC.ASSEMBLY_CONSTITUENCY_NUMBER = ER.SOURCEACNO AND SRC.PART_NUMBER = ER.SOURCEPARTNO AND SRC.PART_SERIAL_NUMBER = ER.SOURCESLNOINPART)
INNER JOIN MASTERS.ELECTORALROLLREVISIONS RV ON RV.REVISIONNO = S.REVISIONNO
WHERE S.STATUSTYPE='N' AND S.ACNO = $P{acno} AND S.PARTNO = $P{partno} AND S.REVISIONNO = 2


UNION ALL

--SUP2 AND EXIST IN MOTHER ROLL AND SUP1 FORM 6E/8A STATUS ='N' 
SELECT S2.ACNO, S2.PARTNO, S2.SECTIONNO, S2.SLNOINPART, S2.EPICCARDNO, S2.HOUSENO, S2.REVISIONNO, SRC.PHOTO 
FROM EROLLS.ELECTORALROLLS ER
INNER JOIN EROLLS.ELECTORALROLLSSUP S1 ON (ER.ACNO = S1.SOURCEACNO AND ER.PARTNO = S1.SOURCEPARTNO AND ER.SLNOINPART = S1.SOURCESLNOINPART)
INNER JOIN EROLLS.ELECTORALROLLSSUP S2 ON (S1.ACNO = S2.SOURCEACNO AND S1.PARTNO = S2.SOURCEPARTNO AND S1.SLNOINPART = S2.SOURCESLNOINPART)
INNER JOIN SOURCES.SOURCEELECTORALROLLS SRC ON (SRC.ASSEMBLY_CONSTITUENCY_NUMBER = ER.SOURCEACNO AND SRC.PART_NUMBER = ER.SOURCEPARTNO AND SRC.PART_SERIAL_NUMBER = ER.SOURCESLNOINPART)
INNER JOIN MASTERS.ELECTORALROLLREVISIONS RV ON RV.REVISIONNO = S1.REVISIONNO
WHERE S2.ACNO = $P{acno} AND S2.PARTNO = $P{partno}
AND S1.REVISIONNO = 1 AND S2.REVISIONNO = 2 AND S2.STATUSTYPE='N'

UNION ALL

-- FORM 6 IN SUP 1 AND STATUSTYPE='N' IN SUP 2
SELECT S2.ACNO, S2.PARTNO, S2.SECTIONNO, S2.SLNOINPART, S2.EPICCARDNO, S2.HOUSENO, S2.REVISIONNO, S1.PHOTO 
FROM EROLLS.ELECTORALROLLSSUP S1
INNER JOIN EROLLS.ELECTORALROLLSSUP S2 ON (S1.ACNO = S2.SOURCEACNO AND S1.PARTNO = S2.SOURCEPARTNO AND S1.SLNOINPART = S2.SOURCESLNOINPART)
INNER JOIN MASTERS.ELECTORALROLLREVISIONS RV ON RV.REVISIONNO = S1.REVISIONNO
WHERE S1.STATUSTYPE='N' AND S1.FORMTYPE='F6' AND S1.REVISIONNO = 1 AND S2.REVISIONNO = 2 AND S2.STATUSTYPE = 'N'
AND S2.ACNO = $P{acno} AND S2.PARTNO =$P{partno}

