SELECT
AC.ACNO, ACNAME, AP.PARTNO, RV.REVISIONNO, STATUSTYPE,
CASE 	WHEN ROW_NUMBER() OVER(ORDER BY AC.ACNO, AP.PARTNO, RV.REVISIONNO,CASE WHEN STATUSTYPE ='N' THEN 1 WHEN STATUSTYPE ='D' THEN 2 WHEN STATUSTYPE ='M' THEN 3 END) = 1 THEN 'I' WHEN ROW_NUMBER() OVER(ORDER BY AC.ACNO, AP.PARTNO, RV.REVISIONNO,CASE WHEN STATUSTYPE ='N' THEN 1 WHEN STATUSTYPE ='D' THEN 2 WHEN STATUSTYPE ='M' THEN 3 END) = 2 THEN 'II'  WHEN ROW_NUMBER() OVER(ORDER BY AC.ACNO, AP.PARTNO, RV.REVISIONNO,CASE WHEN STATUSTYPE ='N' THEN 1 WHEN STATUSTYPE ='D' THEN 2 WHEN STATUSTYPE ='M' THEN 3 END) = 3 THEN 'III' WHEN ROW_NUMBER() OVER(ORDER BY AC.ACNO, AP.PARTNO, RV.REVISIONNO,CASE WHEN STATUSTYPE ='N' THEN 1 WHEN STATUSTYPE ='D' THEN 2 WHEN STATUSTYPE ='M' THEN 3 END) = 4 THEN 'IV'
	WHEN ROW_NUMBER() OVER(ORDER BY AC.ACNO, AP.PARTNO, RV.REVISIONNO,CASE WHEN STATUSTYPE ='N' THEN 1 WHEN STATUSTYPE ='D' THEN 2 WHEN STATUSTYPE ='M' THEN 3 END) = 5 THEN 'V'	WHEN ROW_NUMBER() OVER(ORDER BY AC.ACNO, AP.PARTNO, RV.REVISIONNO,CASE WHEN STATUSTYPE ='N' THEN 1 WHEN STATUSTYPE ='D' THEN 2 WHEN STATUSTYPE ='M' THEN 3 END) = 6 THEN 'VI' 	WHEN ROW_NUMBER() OVER(ORDER BY AC.ACNO, AP.PARTNO, RV.REVISIONNO,CASE WHEN STATUSTYPE ='N' THEN 1 WHEN STATUSTYPE ='D' THEN 2 WHEN STATUSTYPE ='M' THEN 3 END) = 7 THEN 'VII' 	WHEN ROW_NUMBER() OVER(ORDER BY AC.ACNO, AP.PARTNO, RV.REVISIONNO,CASE WHEN STATUSTYPE ='N' THEN 1 WHEN STATUSTYPE ='D' THEN 2 WHEN STATUSTYPE ='M' THEN 3 END) = 8 THEN 'VIII'
	WHEN ROW_NUMBER() OVER(ORDER BY AC.ACNO, AP.PARTNO, RV.REVISIONNO,CASE WHEN STATUSTYPE ='N' THEN 1 WHEN STATUSTYPE ='D' THEN 2 WHEN STATUSTYPE ='M' THEN 3 END) = 9 THEN 'IX' 	WHEN ROW_NUMBER() OVER(ORDER BY AC.ACNO, AP.PARTNO, RV.REVISIONNO,CASE WHEN STATUSTYPE ='N' THEN 1 WHEN STATUSTYPE ='D' THEN 2 WHEN STATUSTYPE ='M' THEN 3 END) = 10 THEN 'X' END AS REVISIONROMAN,CASE 	WHEN RV.REVISIONNO = 0 THEN 'Original'
	WHEN RV.REVISIONNO >= 1 AND STATUSTYPE ='N' THEN 'List of Additions'
	WHEN RV.REVISIONNO >= 1 AND STATUSTYPE ='D' THEN 'List of Deletions'
	WHEN RV.REVISIONNO >= 1 AND STATUSTYPE ='M' THEN 'Difference due to modification in Gender Field'
END AS REVISIONSHORTNAME,ROLLTYPE, REVISIONDESCRIPTION, STATUSTYPE,
MALES, FEMALES, THIRDGENDER, SUBTOTAL,
EROLLS.GETVOTERSCOUNT(AP.ACNO, AP.PARTNO, 99::smallint, 'M') AS TOTALMALES,
EROLLS.GETVOTERSCOUNT(AP.ACNO, AP.PARTNO, 99::smallint, 'F') AS TOTALFEMALES,
EROLLS.GETVOTERSCOUNT(AP.ACNO, AP.PARTNO, 99::smallint, 'O') AS TOTALTHIRDGENDER,
EROLLS.GETVOTERSCOUNT(AP.ACNO, AP.PARTNO, 99::smallint, 'X') AS TOTALVOTERS,
EROLLS.GETNOOFMODIFICATIONS(AP.ACNO,AP.PARTNO,RV.REVISIONNO) AS NOOFMODIFICATIONS
FROM MASTERS.ASSEMBLYCONSTITUENCIES AC INNER JOIN MASTERS.ACPARTS AP ON (AC.ACNO = AP.ACNO)

INNER JOIN (

SELECT 0 AS REVISIONNO, 'X' AS STATUSTYPE, AC.ACNO,  AP.PARTNO, 
EROLLS.GETVOTERSCOUNT(AP.ACNO,AP.PARTNO,0::smallint,'M') AS MALES,EROLLS.GETVOTERSCOUNT(AP.ACNO,AP.PARTNO,0::smallint,'F') AS FEMALES,
EROLLS.GETVOTERSCOUNT(AP.ACNO,AP.PARTNO,0::smallint,'O') AS THIRDGENDER,EROLLS.GETVOTERSCOUNT(AP.ACNO,AP.PARTNO,0::smallint,'X') AS SUBTOTAL
FROM MASTERS.ASSEMBLYCONSTITUENCIES AC INNER JOIN MASTERS.ACPARTS AP ON (AC.ACNO = AP.ACNO) WHERE 1 = 1 AND AC.ACNO = 18 AND PARTNO = 13

UNION ALL

--- REVISION 1

SELECT 1 AS REVISIONNO, 'N' AS STATUSTYPE, AC.ACNO,  AP.PARTNO, EROLLS.GETVOTERSCOUNTWITHSTATUSTYPE(AP.ACNO,AP.PARTNO,'M',1::smallint,'N') AS MALES,EROLLS.GETVOTERSCOUNTWITHSTATUSTYPE(AP.ACNO,AP.PARTNO,'F',1::smallint,'N') AS FEMALES,
EROLLS.GETVOTERSCOUNTWITHSTATUSTYPE(AP.ACNO,AP.PARTNO,'O',1::smallint,'N') AS THIRDGENDER, EROLLS.GETVOTERSCOUNTWITHSTATUSTYPE(AP.ACNO,AP.PARTNO,'X',1::smallint,'N') AS SUBTOTAL
FROM MASTERS.ASSEMBLYCONSTITUENCIES AC INNER JOIN MASTERS.ACPARTS AP ON (AC.ACNO = AP.ACNO) WHERE 1 = 1 AND AC.ACNO = 18 AND PARTNO = 13

UNION ALL

SELECT 1 AS REVISIONNO, 'D' AS STATUSTYPE, AC.ACNO,  AP.PARTNO, EROLLS.GETVOTERSCOUNTWITHSTATUSTYPE(AP.ACNO,AP.PARTNO,'M',1::smallint,'D') AS MALES,EROLLS.GETVOTERSCOUNTWITHSTATUSTYPE(AP.ACNO,AP.PARTNO,'F',1::smallint,'D') AS FEMALES,
EROLLS.GETVOTERSCOUNTWITHSTATUSTYPE(AP.ACNO,AP.PARTNO,'O',1::smallint,'D') AS THIRDGENDER, EROLLS.GETVOTERSCOUNTWITHSTATUSTYPE(AP.ACNO,AP.PARTNO,'X',1::smallint,'D') AS SUBTOTAL
FROM MASTERS.ASSEMBLYCONSTITUENCIES AC INNER JOIN MASTERS.ACPARTS AP ON (AC.ACNO = AP.ACNO) WHERE 1 = 1 AND AC.ACNO = 18 AND PARTNO = 13
UNION ALL
SELECT 1 AS REVISIONNO, 'M' AS STATUSTYPE, AC.ACNO,  AP.PARTNO,
EROLLS.getmodifiedgenders(1::smallint, AC.ACNO, AP.PARTNO, 'M') AS MALES, EROLLS.getmodifiedgenders(1::smallint, AC.ACNO, AP.PARTNO, 'F') AS FEMALES,
EROLLS.getmodifiedgenders(1::smallint, AC.ACNO, AP.PARTNO, 'O') AS THIRDGENDER,
EROLLS.getmodifiedgenders(1::smallint, AC.ACNO, AP.PARTNO, 'M')  + EROLLS.getmodifiedgenders(1::smallint, AC.ACNO, AP.PARTNO, 'F') +
EROLLS.getmodifiedgenders(1::smallint, AC.ACNO, AP.PARTNO, 'O') AS SUBTOTAL
FROM MASTERS.ASSEMBLYCONSTITUENCIES AC INNER JOIN MASTERS.ACPARTS AP ON (AC.ACNO = AP.ACNO) WHERE 1 = 1 AND AC.ACNO = 18 AND PARTNO = 13

--- REVISION 1

UNION ALL 

--- REVISION 2

SELECT 2 AS REVISIONNO, 'N' AS STATUSTYPE, AC.ACNO,  AP.PARTNO, EROLLS.GETVOTERSCOUNTWITHSTATUSTYPE(AP.ACNO,AP.PARTNO,'M',2::smallint,'N') AS MALES,EROLLS.GETVOTERSCOUNTWITHSTATUSTYPE(AP.ACNO,AP.PARTNO,'F',2::smallint,'N') AS FEMALES,
EROLLS.GETVOTERSCOUNTWITHSTATUSTYPE(AP.ACNO,AP.PARTNO,'O',2::smallint,'N') AS THIRDGENDER, EROLLS.GETVOTERSCOUNTWITHSTATUSTYPE(AP.ACNO,AP.PARTNO,'X',2::smallint,'N') AS SUBTOTAL
FROM MASTERS.ASSEMBLYCONSTITUENCIES AC INNER JOIN MASTERS.ACPARTS AP ON (AC.ACNO = AP.ACNO) WHERE 1 = 1 AND AC.ACNO = 18 AND PARTNO = 13

UNION ALL

SELECT 2 AS REVISIONNO, 'D' AS STATUSTYPE, AC.ACNO,  AP.PARTNO, EROLLS.GETVOTERSCOUNTWITHSTATUSTYPE(AP.ACNO,AP.PARTNO,'M',2::smallint,'D') AS MALES,EROLLS.GETVOTERSCOUNTWITHSTATUSTYPE(AP.ACNO,AP.PARTNO,'F',2::smallint,'D') AS FEMALES,
EROLLS.GETVOTERSCOUNTWITHSTATUSTYPE(AP.ACNO,AP.PARTNO,'O',2::smallint,'D') AS THIRDGENDER, EROLLS.GETVOTERSCOUNTWITHSTATUSTYPE(AP.ACNO,AP.PARTNO,'X',2::smallint,'D') AS SUBTOTAL
FROM MASTERS.ASSEMBLYCONSTITUENCIES AC INNER JOIN MASTERS.ACPARTS AP ON (AC.ACNO = AP.ACNO) WHERE 1 = 1 AND AC.ACNO = 18 AND PARTNO = 13
UNION ALL
SELECT 2 AS REVISIONNO, 'M' AS STATUSTYPE, AC.ACNO,  AP.PARTNO,
EROLLS.getmodifiedgenders(1::smallint, AC.ACNO, AP.PARTNO, 'M') AS MALES, EROLLS.getmodifiedgenders(2::smallint, AC.ACNO, AP.PARTNO, 'F') AS FEMALES,
EROLLS.getmodifiedgenders(1::smallint, AC.ACNO, AP.PARTNO, 'O') AS THIRDGENDER,
EROLLS.getmodifiedgenders(1::smallint, AC.ACNO, AP.PARTNO, 'M')  + EROLLS.getmodifiedgenders(2::smallint, AC.ACNO, AP.PARTNO, 'F') +
EROLLS.getmodifiedgenders(1::smallint, AC.ACNO, AP.PARTNO, 'O') AS SUBTOTAL
FROM MASTERS.ASSEMBLYCONSTITUENCIES AC INNER JOIN MASTERS.ACPARTS AP ON (AC.ACNO = AP.ACNO) WHERE 1 = 1 AND AC.ACNO = 18 AND PARTNO = 13

--- REVISION 2





)E ON (AP.ACNO = E.ACNO AND AP.PARTNO = E.PARTNO )
INNER JOIN MASTERS.ELECTORALROLLREVISIONS RV ON RV.REVISIONNO = E.REVISIONNO
WHERE 1 = 1 AND AC.ACNO= 18 AND AP.PARTNO = 13
ORDER BY AC.ACNO, AP.PARTNO, RV.REVISIONNO,
CASE WHEN STATUSTYPE ='N' THEN 1 WHEN STATUSTYPE ='D' THEN 2 WHEN STATUSTYPE ='M' THEN 3 END