SELECT X.* , ERSLNO - SSLNO FROM (

(SELECT ACNO AS ERACNO, PARTNO AS ERPARTNO, MAX(SLNOINPART) AS ERSLNO FROM EROLLS.ELECTORALROLLS GROUP BY ACNO, PARTNO) ER INNER JOIN 
(SELECT ACNO AS SACNO, PARTNO AS SPARTNO, MIN(SLNOINPART) AS SSLNO FROM EROLLS.ELECTORALROLLSSUP WHERE STATUSTYPE ='N' GROUP BY ACNO, PARTNO) S 
ON ERACNO = SACNO AND ERPARTNO = SPARTNO 
) X 
ORDER BY ERACNO, ERPARTNO
