/*
UPDATE MASTERS.ELECTORALROLLREVISIONS SET ENABLED ='N';
UPDATE MASTERS.ELECTORALROLLREVISIONS SET ENABLED ='Y' WHERE REVISIONNO = 2;
UPDATE MASTERS.ELECTORALROLLREVISIONS SET PUBLICATIONDATE ='2025-01-28' WHERE REVISIONNO = 2;
*/

DELETE FROM EROLLS.ELECTORALROLLSSUP WHERE ACNO = 18 ;
DELETE FROM EROLLS.SUPPLEMENTS WHERE USERID = 22 ;
DELETE FROM EROLLS.ELECTORALROLLSSUP WHERE USERID = 22;
DELETE FROM EROLLS.SUPPLEMENTS WHERE ACNO = 18 AND PARTNO IN (13, 14, 15, 16);

SELECT ACNO, PARTNO, GENDER, COUNT(*) FROM EROLLS.ELECTORALROLLS WHERE ACNO = 18 AND PARTNO IN (13, 14, 15,  16) GROUP BY ACNO, PARTNO , GENDER ORDER BY ACNO, PARTNO  ;

SELECT * FROM EROLLS.SUPPLEMENTS WHERE USERID = 22 ORDER BY REVISIONNO, ACNO, PARTNO ;

SELECT * FROM EROLLS.ELECTORALROLLSSUP WHERE USERID = 22 ORDER BY REVISIONNO, ACNO, PARTNO ;

	