/*
SELECT OFFICECATEGORYNAME, COUNT(*) FROM MASTERS.OFFICES EO 
INNER JOIN MASTERS.OFFICES O ON EO.OFFICECODE = O.REFERENCEOFFICECODE 
INNER JOIN MASTERS.OFFICECATEGORIES OC ON OC.OFFICECATEGORYCODE = O.OFFICECATEGORYCODE
INNER JOIN VWPERSONNEL P ON O.OFFICECODE = P.OFFICECODE 
GROUP BY OFFICECATEGORYNAME
ORDER BY OFFICECATEGORYNAME
*/

/*
SELECT AC.ACNO || '-' || ACNAME , COUNT(*) FROM MASTERS.OFFICES EO 
INNER JOIN MASTERS.OFFICES O ON EO.OFFICECODE = O.REFERENCEOFFICECODE 
INNER JOIN VWPERSONNEL P ON O.OFFICECODE = P.OFFICECODE 
INNER JOIN MASTERS.ASSEMBLYCONSTITUENCIES AC ON AC.ACNO = P.ACNO 
WHERE 1 = 1  AND EO.OFFICECODE = '030001'
AND AC.ACNO IN (SELECT ACNO FROM MASTERS.OFFICESACS WHERE OFFICECODE = '030001')
GROUP BY AC.ACNO
ORDER BY AC.ACNO
*/



-- SEARCH EMPLOYEE 


--EXEMPTED DO LEFT JOIN 

--TRAINING
SELECT TP.PHASENO AS PHASENO,  
TO_CHAR(TS.TRAININGDATE,'DD-MM-YYYY') AS TRAININGDATE,
VENUEDESCRIPTION FROM MASTERS.DISTRICTS D 
INNER JOIN MASTERS.OFFICES EO ON D.DISTRICTCODE = EO.DISTRICTCODE INNER JOIN MASTERS.OFFICES O ON EO.OFFICECODE  = O.REFERENCEOFFICECODE 
INNER JOIN ELECTIONS.VWPERSONNEL P ON O.OFFICECODE = P.OFFICECODE 
INNER JOIN MASTERS.PERSONNELCATEGORIES C ON C.PERSONNELCATEGORYCODE = P.PERSONNELCATEGORYCODE 
INNER JOIN ELECTIONS.TRAININGPHASES TP ON EO.OFFICECODE = TP.OFFICECODE 
INNER JOIN ELECTIONS.TRAININGTYPES TT ON TP.TRAININGTYPECODE = TT.TRAININGTYPECODE 
INNER JOIN ELECTIONS.TRAININGVENUES TV ON TP.OFFICECODE = TV.OFFICECODE 
INNER JOIN ELECTIONS.TRAININGLETTERNOFORMAT TF ON (EO.OFFICECODE = TF.OFFICECODE AND TP.TRAININGTYPECODE = TF.TRAININGTYPECODE AND TP.PHASENO = TF.PHASENO ) 
INNER JOIN ELECTIONS.TRAININGSESSIONS TS ON (EO.OFFICECODE = TS.OFFICECODE AND TP.TRAININGTYPECODE = TS.TRAININGTYPECODE AND TP.PHASENO = TS.PHASENO  AND  TV.VENUECODE = TS.VENUECODE) 
INNER JOIN ELECTIONS.TRAININGPERSONNEL TPER ON (TS.SESSIONCODE = TPER.SESSIONCODE AND P.EMPLOYEECODE = TPER.EMPLOYEECODE) 
--LEFT OUTER JOIN TRAININGATTENDANCE TA ON TA.SESSIONCODE = TS.SESSIONCODE AND TA.EMPLOYEECODE = TPER.EMPLOYEECODE   
WHERE 1 = 1 AND EO.OFFICECODE = '070001' 
ORDER BY P.EMPLOYEECODE 
LIMIT 30
	
--ALLOCATION 2

--ALLOCATION 3 
--ALSO ADD AC AND GROUP DETAILS 





