/*


ALTER TABLE IF EXISTS ELECTIONS.RNDPSPERSONNELCATEGORIESMAP SET SCHEMA  masters;

DROP VIEW IF EXISTS MASTERS.VWPOLLINGSTATIONS ;
CREATE OR REPLACE VIEW MASTERS.VWPOLLINGSTATIONS AS 
SELECT EO.OFFICECODE, AC.ACNO, ACNAME, AP.PARTNO, AP.PARTNAME, PS.PSNO, PSNAME, PS.SENSITIVITYCODE,  S.SENSITIVITYDESCRIPTION, PST.PSRTYPESCODE, 
PST.PSRTYPESDESCRIPTION, PSP.MOTORABLEDISTANCE, PSP.NONMOTORABLEDISTANCE, 
PC.PERSONNELCATEGORYCODE, PC.PERSONNELCATEGORYDESCRIPTION, NOOFPERSONNEL
FROM MASTERS.OFFICES EO INNER JOIN MASTERS.OFFICESACS OAC ON EO.OFFICECODE = OAC.OFFICECODE
INNER JOIN MASTERS.ASSEMBLYCONSTITUENCIES AC ON AC.ACNO = OAC.ACNO
INNER JOIN MASTERS.ACPARTS AP ON AC.ACNO = AP.ACNO
INNER JOIN MASTERS.POLLINGSTATIONS PS ON (AP.ACNO = PS.ACNO AND AP.PARTNO = PS.PARTNO)
INNER JOIN MASTERS.PSPARAMETERS PSP ON (PS.ACNO = PSP.ACNO AND PS.PARTNO= PSP.PARTNO AND PS.PSNO = PSP.PSNO)
INNER JOIN MASTERS.SENSITIVITIES S ON S.SENSITIVITYCODE  = PSP.SENSITIVITYCODE
INNER JOIN MASTERS.RNDPSPERSONNELCATEGORIESMAP PSPCM ON (PS.ACNO = PSPCM.ACNO AND PS.PARTNO= PSPCM.PARTNO AND PS.PSNO = PSPCM.PSNO)
INNER JOIN MASTERS.PERSONNELCATEGORIES PC ON PC.PERSONNELCATEGORYCODE = PSPCM.PERSONNELCATEGORYCODE
INNER JOIN MASTERS.PSRANDOMIZATIONTYPES PST ON PST.PSRTYPESCODE = PSP.PSRTYPESCODE;

SELECT * FROM MASTERS.VWPOLLINGSTATIONS ORDER BY NONMOTORABLEDISTANCE DESC, MOTORABLEDISTANCE DESC, SENSITIVITYCODE DESC, PERSONNELCATEGORYCODE;

*/



SELECT EMPLOYEECODE , FULLNAME , DOB, DATE_PART('YEAR',AGE(NOW(),DOB)),  FROM VWPERSONNEL P
WHERE GENDER ='MALE' 
AND ISPWD ='N' AND ISEXPECTINGLACTATING ='N' AND ISAILING ='N'
AND DATE_PART('YEAR',AGE(NOW(),DOB)) < 50
ORDER BY RANDOM()
LIMIT 10000000 
