DEALLOCATE PREPARE  ALL ;

PREPARE  PERSONNELQUERY (CHARACTER VARYING/*ELECTION OFFICE*/, SMALLINT /*ACNO*/,SMALLINT /*PARTNO*/,SMALLINT /*PSNO*/,SMALLINT /*PERSONNELCATEGORYCODE*/) AS


SELECT EMPLOYEECODE , O.OFFICENAME, FULLNAME , GENDER, DOB, DATE_PART('YEAR',AGE(NOW(),DOB)) , ACNO, PERSONNELCATEGORYCODE FROM MASTERS.OFFICES EO 
INNER JOIN MASTERS.OFFICES O ON EO.OFFICECODE = O.REFERENCEOFFICECODE 
INNER JOIN VWPERSONNEL P ON O.OFFICECODE = P.OFFICECODE 
WHERE 1 = 1 
AND EO.OFFICECODE = $1
AND ACNO <> $2 
AND PERSONNELCATEGORYCODE =$5
AND ISPWD ='N' AND ISEXPECTINGLACTATING ='N' AND ISAILING ='N'
AND P.SENSITIVITYCODE = (SELECT SENSITIVITYCODE FROM MASTERS.PSPARAMETERS WHERE ACNO=$2 AND PARTNO =$3) 
AND CASE WHEN (SELECT NONMOTORABLEDISTANCE FROM MASTERS.PSPARAMETERS WHERE ACNO=$2 AND PARTNO =$3) >=1 THEN GENDER ='MALE' ELSE GENDER IN ('MALE', 'FEMALE') END
AND CASE WHEN (SELECT NONMOTORABLEDISTANCE FROM MASTERS.PSPARAMETERS WHERE ACNO=$2 AND PARTNO =$3) >=1 THEN DATE_PART('YEAR',AGE(NOW(),DOB)) < 50  ELSE 1 = 1 END
	AND P.OFFICECODE NOT IN (
		SELECT OFFICECODE FROM VWPERSONNEL P INNER JOIN ELECTIONS.POLLINGALLOCATION3 A ON P.EMPLOYEECODE = A.EMPLOYEECODE WHERE A.ACNO = $2 AND A.PARTNO = $3 AND PSNO = $4
	)
AND EMPLOYEECODE NOT IN (
	SELECT P.EMPLOYEECODE FROM MASTERS.OFFICES EO INNER JOIN MASTERS.OFFICES O ON EO.OFFICECODE = O.REFERENCEOFFICECODE 
	INNER JOIN VWPERSONNEL P ON O.OFFICECODE = P.OFFICECODE INNER JOIN POLLINGALLOCATION3 A ON P.EMPLOYEECODE = A.EMPLOYEECODE
	)
	
ORDER BY DOB
;



EXECUTE PERSONNELQUERY('010001', 1, 2, 1,1);

