/*
DROP TABLE ELECTIONS.COUNTINGALLOCATION2HAPHI;
DROP TABLE ELECTIONS.COUNTINGALLOCATION3HAPHI;
DROP TABLE ELECTIONS.COUNTINGRESERVES2HAPHI;
DROP TABLE ELECTIONS.POLLINGALLOCATION2ORIGINAL;
DROP TABLE ELECTIONS.CREDITED;
DROP TABLE ELECTIONS.EKHRESERVES;
DROP TABLE logs.exemptedpersonnel_2024_03_08;
DROP TABLE logs.OFFICES_2024_03_08;
DROP TABLE logs.personnel_2024_03_08;
DROP TABLE MASTERS.ACPARTS2023;
DROP TABLE ELECTIONS.personnel20240419;
DROP TABLE ELECTIONS.personnel20240517;
*/


DELETE FROM ELECTIONS.COUNTINGRESERVES;
DELETE FROM ELECTIONS.COUNTINGALLOCATION3;
DELETE FROM ELECTIONS.COUNTINGALLOCATION2;
DELETE FROM ELECTIONS.COUNTINGALLOCATION1;

DELETE FROM ELECTIONS.COUNTINGHALLSACS;
DELETE FROM ELECTIONS.COUNTINGTABLES;
DELETE FROM ELECTIONS.COUNTINGHALLS;
DELETE FROM ELECTIONS.COUNTINGVENUES;
DELETE FROM ELECTIONS.EXEMPTEDPERSONNEL;
DELETE FROM ELECTIONS.OTHERPERSONNEL;


DELETE FROM ELECTIONS.PERSONNELAPPOINTMENT;
DELETE FROM ELECTIONS.PERSONNELAPPOINTMENTLETTERS;
DELETE FROM ELECTIONS.POLLINGALLOCATION3;
DELETE FROM ELECTIONS.POLLINGALLOCATION2;
DELETE FROM ELECTIONS.POLLINGALLOCATION1;
DELETE FROM ELECTIONS.POLLINGRESERVES;
DELETE FROM ELECTIONS.TRAININGATTENDANCE;


DELETE FROM ELECTIONS.TRAININGLETTERNOFORMAT;

DROP TRIGGER logtrainingpersonnel ON ELECTIONS.trainingpersonnel;


DELETE FROM ELECTIONS.TRAININGPERSONNEL;

CREATE TRIGGER logtrainingpersonnel  AFTER UPDATE OR DELETE   ON ELECTIONS.trainingpersonnel   FOR EACH ROW   EXECUTE PROCEDURE logs.logtrainingpersonnel();


DELETE FROM ELECTIONS.TRAININGSESSIONS;
DELETE FROM ELECTIONS.TRAININGVENUES;
DELETE FROM ELECTIONS.TRAININGPHASES;
DELETE FROM ELECTIONS.VEHICLES;

DELETE FROM MASTERS.MATERIALMOVEMENT;
DELETE FROM MASTERS.SECTOROFFICERS;
DELETE FROM MASTERS.SECTORSPS;
DELETE FROM MASTERS.SECTORS;

DELETE FROM ELECTIONS.PERSONNELEXPERIENCE;

DROP TRIGGER logpersonnel ON ELECTIONS.personnel;
DELETE FROM ELECTIONS.PERSONNEL;
CREATE TRIGGER logpersonnel  AFTER UPDATE OR DELETE  ON ELECTIONS.personnel  FOR EACH ROW  EXECUTE PROCEDURE logs.logpersonnel();

DELETE FROM MASTERS.RNDPSPERSONNELCATEGORIESMAP;


DELETE FROM MASTERS.RNDCOUNTINGCATEGORIESMAP;
DELETE FROM MASTERS.COUNTINGMASTERTABLE;
DELETE FROM MASTERS.PSPARAMETERS;
DELETE FROM MASTERS.RETURNINGOFFICERS;





--DELETE FROM MASTERS.SECTIONS;
--DELETE FROM MASTERS.POLLINGSTATIONS;
--DELETE FROM MASTERS.ACPARTS;
--DELETE FROM MASTERS.OFFICESACS;
--DELETE FROM MASTERS.ASSEMBLYCONSTITUENCIES;

DELETE FROM USERS.AUDITTRIAL;


DELETE FROM LOGS.OFFICES;
DELETE FROM LOGS.PERSONNEL;
DELETE FROM LOGS.POLLINGALLOCATION2;
DELETE FROM LOGS.PSPARAMETERS;
DELETE FROM LOGS.SECTOROFFICERS;
DELETE FROM LOGS.SECTORS;
DELETE FROM LOGS.SECTORSPS;
DELETE FROM LOGS.TRAININGPERSONNEL;
DELETE FROM LOGS.TRAININGSESSIONS;
DELETE FROM LOGS.TRAININGVENUES;



DROP  TABLE MASTERS.POLLINGSTATIONS20050112;
DROP  TABLE MASTERS.POLLINGSTATIONSALL;
DROP  TABLE MASTERS.POLLINGSTATIONSTEMP;


DROP  TABLE IMPORTS.EKHACPARTS;
DROP  TABLE IMPORTS.EKHBLOCKS;
DROP  TABLE IMPORTS.EKHSECTIONS;
DROP  TABLE IMPORTS.EWKHACPARTS;
DROP  TABLE IMPORTS.EWKHBLOCKS;
DROP  TABLE IMPORTS.EWKHSECTIONS;
DROP  TABLE IMPORTS.MKTACPARTS;
DROP  TABLE IMPORTS.MKTBLOCKS;
DROP  TABLE IMPORTS.MKTSECTIONS;
DROP  TABLE IMPORTS.RBDACPARTS;
DROP  TABLE IMPORTS.RBDBLOCKS;
DROP  TABLE IMPORTS.RBDSECTIONS;
DROP  TABLE IMPORTS.SOHRAACPARTS;
DROP  TABLE IMPORTS.SOHRABLOCKS;
DROP  TABLE IMPORTS.SOHRASECTIONS;
DROP  TABLE IMPORTS.WKHACPARTS;
DROP  TABLE IMPORTS.WKHBLOCKS;
 DROP TABLE IMPORTS.WKHSECTIONS;



DELETE FROM EROLLS.SUPPLEMENTS;
DELETE FROM EROLLS.ACPARTSLOCK;
DELETE FROM EROLLS.ELECTORALROLLSSUP;
DELETE FROM EROLLS.ELECTORALROLLS;
DELETE FROM EVMS.EVMALLOCATION1;
DELETE FROM EVMS.EVMALLOCATION2;
DELETE  FROM EVMS.VOTINGUNITS;



DELETE FROM SOURCES.SOURCEELECTORALROLLS






SELECT 'vofficesusers' AS TABLENAME , COUNT(*) FROM  elections.vofficesusers UNION ALL
SELECT 'vdistrictsusers' AS TABLENAME , COUNT(*) FROM  elections.vdistrictsusers UNION ALL
SELECT 'vwpersonnel' AS TABLENAME , COUNT(*) FROM  elections.vwpersonnel UNION ALL
SELECT 'trainingtypes' AS TABLENAME , COUNT(*) FROM  elections.trainingtypes UNION ALL
SELECT 'personnelexperience' AS TABLENAME , COUNT(*) FROM  elections.personnelexperience UNION ALL
SELECT 'personnelappointment' AS TABLENAME , COUNT(*) FROM  elections.personnelappointment UNION ALL
SELECT 'pollingallocation1' AS TABLENAME , COUNT(*) FROM  elections.pollingallocation1 UNION ALL
SELECT 'vwcountingallocation2' AS TABLENAME , COUNT(*) FROM  elections.vwcountingallocation2 UNION ALL
SELECT 'vwcountingallocation3' AS TABLENAME , COUNT(*) FROM  elections.vwcountingallocation3 UNION ALL
SELECT 'pollingreserves' AS TABLENAME , COUNT(*) FROM  elections.pollingreserves UNION ALL
SELECT 'pollingallocation2' AS TABLENAME , COUNT(*) FROM  elections.pollingallocation2 UNION ALL
SELECT 'vwpollingallocation2' AS TABLENAME , COUNT(*) FROM  elections.vwpollingallocation2 UNION ALL
SELECT 'vwpollingallocation3' AS TABLENAME , COUNT(*) FROM  elections.vwpollingallocation3 UNION ALL
SELECT 'vwtraining' AS TABLENAME , COUNT(*) FROM  elections.vwtraining UNION ALL
SELECT 'trainingphases' AS TABLENAME , COUNT(*) FROM  elections.trainingphases UNION ALL
SELECT 'trainingattendance' AS TABLENAME , COUNT(*) FROM  elections.trainingattendance UNION ALL
SELECT 'pollingallocation3' AS TABLENAME , COUNT(*) FROM  elections.pollingallocation3 UNION ALL
SELECT 'trainingpersonnel' AS TABLENAME , COUNT(*) FROM  elections.trainingpersonnel UNION ALL
SELECT 'countingreserves' AS TABLENAME , COUNT(*) FROM  elections.countingreserves UNION ALL
SELECT 'exemptedpersonnel' AS TABLENAME , COUNT(*) FROM  elections.exemptedpersonnel UNION ALL
SELECT 'otherpersonnel' AS TABLENAME , COUNT(*) FROM  elections.otherpersonnel UNION ALL
SELECT 'countinghallsacs' AS TABLENAME , COUNT(*) FROM  elections.countinghallsacs UNION ALL
SELECT 'countingtables' AS TABLENAME , COUNT(*) FROM  elections.countingtables UNION ALL
SELECT 'countingvenues' AS TABLENAME , COUNT(*) FROM  elections.countingvenues UNION ALL
SELECT 'countingallocation1' AS TABLENAME , COUNT(*) FROM  elections.countingallocation1 UNION ALL
SELECT 'countinghalls' AS TABLENAME , COUNT(*) FROM  elections.countinghalls UNION ALL
SELECT 'countingallocation3' AS TABLENAME , COUNT(*) FROM  elections.countingallocation3 UNION ALL
SELECT 'trainingvenues' AS TABLENAME , COUNT(*) FROM  elections.trainingvenues UNION ALL
SELECT 'trainingletternoformat' AS TABLENAME , COUNT(*) FROM  elections.trainingletternoformat UNION ALL
SELECT 'personnel' AS TABLENAME , COUNT(*) FROM  elections.personnel UNION ALL
SELECT 'countingallocation2' AS TABLENAME , COUNT(*) FROM  elections.countingallocation2 UNION ALL
SELECT 'personnelappointmentletters' AS TABLENAME , COUNT(*) FROM  elections.personnelappointmentletters UNION ALL
SELECT 'trainingsessions' AS TABLENAME , COUNT(*) FROM  elections.trainingsessions UNION ALL
SELECT 'vehicles' AS TABLENAME , COUNT(*) FROM  elections.vehicles UNION ALL
SELECT 'psparameters' AS TABLENAME , COUNT(*) FROM  logs.psparameters UNION ALL
SELECT 'pollingallocation2' AS TABLENAME , COUNT(*) FROM  logs.pollingallocation2 UNION ALL
SELECT 'trainingvenues' AS TABLENAME , COUNT(*) FROM  logs.trainingvenues UNION ALL
SELECT 'trainingsessions' AS TABLENAME , COUNT(*) FROM  logs.trainingsessions UNION ALL
SELECT 'trainingpersonnel' AS TABLENAME , COUNT(*) FROM  logs.trainingpersonnel UNION ALL
SELECT 'sectorsps' AS TABLENAME , COUNT(*) FROM  logs.sectorsps UNION ALL
SELECT 'offices' AS TABLENAME , COUNT(*) FROM  logs.offices UNION ALL
SELECT 'personnel' AS TABLENAME , COUNT(*) FROM  logs.personnel UNION ALL
SELECT 'sectors' AS TABLENAME , COUNT(*) FROM  logs.sectors UNION ALL
SELECT 'sectorofficers' AS TABLENAME , COUNT(*) FROM  logs.sectorofficers UNION ALL
SELECT 'psrandomizationtypes' AS TABLENAME , COUNT(*) FROM  masters.psrandomizationtypes UNION ALL
SELECT 'personnelcategories' AS TABLENAME , COUNT(*) FROM  masters.personnelcategories UNION ALL
SELECT 'vwacpartsps' AS TABLENAME , COUNT(*) FROM  masters.vwacpartsps UNION ALL
SELECT 'sectors' AS TABLENAME , COUNT(*) FROM  masters.sectors UNION ALL
SELECT 'sectorofficers' AS TABLENAME , COUNT(*) FROM  masters.sectorofficers UNION ALL
SELECT 'materialmovement' AS TABLENAME , COUNT(*) FROM  masters.materialmovement UNION ALL
SELECT 'parliamentaryconstituencies' AS TABLENAME , COUNT(*) FROM  masters.parliamentaryconstituencies UNION ALL
SELECT 'officesacs' AS TABLENAME , COUNT(*) FROM  masters.officesacs UNION ALL
SELECT 'states' AS TABLENAME , COUNT(*) FROM  masters.states UNION ALL
SELECT 'countingmastertable' AS TABLENAME , COUNT(*) FROM  masters.countingmastertable UNION ALL
SELECT 'rndcountingcategoriesmap' AS TABLENAME , COUNT(*) FROM  masters.rndcountingcategoriesmap UNION ALL
SELECT 'cells' AS TABLENAME , COUNT(*) FROM  masters.cells UNION ALL
SELECT 'rndpspersonnelcategoriesmap' AS TABLENAME , COUNT(*) FROM  masters.rndpspersonnelcategoriesmap UNION ALL
SELECT 'returningofficers' AS TABLENAME , COUNT(*) FROM  masters.returningofficers UNION ALL
SELECT 'reservesreporting' AS TABLENAME , COUNT(*) FROM  masters.reservesreporting UNION ALL
SELECT 'sectorsps' AS TABLENAME , COUNT(*) FROM  masters.sectorsps UNION ALL
SELECT 'sensitivities' AS TABLENAME , COUNT(*) FROM  masters.sensitivities UNION ALL
SELECT 'acparts' AS TABLENAME , COUNT(*) FROM  masters.acparts UNION ALL
SELECT 'votersflags' AS TABLENAME , COUNT(*) FROM  masters.votersflags UNION ALL
SELECT 'tadarates' AS TABLENAME , COUNT(*) FROM  masters.tadarates UNION ALL
SELECT 'pages' AS TABLENAME , COUNT(*) FROM  masters.pages UNION ALL
SELECT 'relations' AS TABLENAME , COUNT(*) FROM  masters.relations UNION ALL
SELECT 'processes' AS TABLENAME , COUNT(*) FROM  masters.processes UNION ALL
SELECT 'randomizationtypes' AS TABLENAME , COUNT(*) FROM  masters.randomizationtypes UNION ALL
SELECT 'psparameters' AS TABLENAME , COUNT(*) FROM  masters.psparameters UNION ALL
SELECT 'officecategories' AS TABLENAME , COUNT(*) FROM  masters.officecategories UNION ALL
SELECT 'genders' AS TABLENAME , COUNT(*) FROM  masters.genders UNION ALL
SELECT 'offices' AS TABLENAME , COUNT(*) FROM  masters.offices UNION ALL
SELECT 'pollingstations' AS TABLENAME , COUNT(*) FROM  masters.pollingstations UNION ALL
SELECT 'assemblyconstituencies' AS TABLENAME , COUNT(*) FROM  masters.assemblyconstituencies UNION ALL
SELECT 'identitycardsmasters' AS TABLENAME , COUNT(*) FROM  masters.identitycardsmasters UNION ALL
SELECT 'districts' AS TABLENAME , COUNT(*) FROM  masters.districts UNION ALL
SELECT 'mastertable' AS TABLENAME , COUNT(*) FROM  masters.mastertable UNION ALL
SELECT 'audittrial' AS TABLENAME , COUNT(*) FROM  users.audittrial UNION ALL
SELECT 'userpages' AS TABLENAME , COUNT(*) FROM  users.userpages UNION ALL
SELECT 'useroffices' AS TABLENAME , COUNT(*) FROM  users.useroffices UNION ALL
SELECT 'useraccounts' AS TABLENAME , COUNT(*) FROM  users.useraccounts ;
