ALTER TABLE ELECTIONS."EGH_Parts" RENAME TO EGHACPARTS;
ALTER TABLE ELECTIONS."EGH_sections" RENAME TO EGHSECTIONS;
ALTER TABLE ELECTIONS."EGH_blocks" RENAME TO EGHBLOCKS;

ALTER TABLE ELECTIONS.EGHACPARTS SET SCHEMA IMPORTS;
ALTER TABLE ELECTIONS.EGHSECTIONS SET SCHEMA IMPORTS;
ALTER TABLE ELECTIONS.EGHBLOCKS SET SCHEMA IMPORTS;

ALTER TABLE IMPORTS.EGHACPARTS ADD COLUMN BLOCKCODE SMALLINT;

SELECT COUNT(*) FROM IMPORTS .EGHACPARTS ;
SELECT COUNT(*) FROM IMPORTS .EGHSECTIONS  ;

SELECT DISTINCT BLOCKNAME FROM IMPORTS.EGHBLOCKS ;

SELECT DISTINCT BLOCKNAME FROM IMPORTS.EGHBLOCKS WHERE BLOCKNAME NOT IN (SELECT BLOCKNAME FROM MASTERS.BLOCKS);




SELECT 'UPDATE IMPORTS.EGHACPARTS SET BLOCKCODE = ' || BLOCKCODE || ' WHERE ACNO = ' || ACNO || ' AND PARTNO = ' || PARTNO || ';' 
FROM MASTERS.BLOCKS B INNER JOIN IMPORTS.EGHBLOCKS D ON TRIM(UPPER(B.BLOCKNAME)) = TRIM(UPPER(D.BLOCKNAME)) 




SELECT * FROM MASTERS.VILLAGES



UPDATE IMPORTS.EGHACPARTS SET MAINVILLAGECODE ='0500000000001017R' WHERE ACNO = 27 AND PARTNO = 40;
INSERT INTO MASTERS.VILLAGES VALUES ('0500000000000001U', 5, NULL, 'KIKI ADD 1', 'T', 1, CURRENT_TIMESTAMP);

INSERT INTO MASTERS.ACPARTS
SELECT ACNO, PARTNO, PARTNAME, PARTLOCATIONCATEGORY, LATITUDE, LONGITUDE, BLOCKCODE, PINCODEX, LEFT(POSTOFFICECODE,5) , LEFT(POLICESTATIONCODE,5), 
--regexp_replace(PSBUILDINGID, '\W', '', 'g'), 
LPAD(ACNO::TEXT,3,'0') || LPAD(PARTNO::TEXT,3,'0')  AS PSBUILDINGID,
regexp_replace(MAINVILLAGECODE, '\W', '', 'g'), FVTTYPE, PARTGENDERTYPE, 1, CURRENT_TIMESTAMP FROM IMPORTS.EGHACPARTS
ORDER BY ACNO, PARTNO;



SELECT * FROM IMPORTS.EGHACPARTS;

INSERT INTO MASTERS.POLLINGSTATIONS
SELECT ACNO, PARTNO, PARTNO, PARTNAME, PARTNAME,  
LPAD(ACNO::TEXT,3,'0') || LPAD(PARTNO::TEXT,3,'0')  AS PSBUILDINGID,
PS_BUILDING_NAME,
1, 1, CURRENT_TIMESTAMP FROM IMPORTS.EGHACPARTS
ORDER BY ACNO, PARTNO;



SELECT * FROM MASTERS.ACPARTS WHERE PSBUILDINGID NOT IN (SELECT PSBUILDINGID FROM MASTERS.POLLINGSTATIONS);

SELECT * FROM MASTERS.ACPARTS WHERE MAINVILLAGECODE NOT IN (SELECT VLOCATIONCODE FROM MASTERS.VILLAGES);

SELECT * FROM IMPORTS.EGHSECTIONS WHERE ACNO IS NULL OR PARTNO IS NULL OR SECTIONNO IS NULL OR SECTIONNAME IS NULL 
OR VLOCATIONCODE IS NULL;

INSERT INTO MASTERS.SECTIONS 
SELECT ACNO, PARTNO, SECTIONNO, SECTIONNAME, regexp_replace(VLOCATIONCODE, '\W', '', 'g'), PINCODEX, 1, CURRENT_TIMESTAMP FROM IMPORTS.EGHSECTIONS;

SELECT * FROM MASTERS.SECTIONS WHERE VLOCATIONCODE NOT IN (SELECT VLOCATIONCODE FROM MASTERS.VILLAGES);
