ALTER TABLE ELECTIONS."WGH_PARTS" RENAME TO WGHACPARTS;
ALTER TABLE ELECTIONS."WGH_sections" RENAME TO WGHSECTIONS;
ALTER TABLE ELECTIONS."WGH_blocks" RENAME TO WGHBLOCKS;

ALTER TABLE ELECTIONS.WGHACPARTS SET SCHEMA IMPORTS;
ALTER TABLE ELECTIONS.WGHSECTIONS SET SCHEMA IMPORTS;
ALTER TABLE ELECTIONS.WGHBLOCKS SET SCHEMA IMPORTS;

ALTER TABLE IMPORTS.WGHACPARTS ADD COLUMN BLOCKCODE SMALLINT;

SELECT COUNT(*) FROM IMPORTS.WGHACPARTS ;
SELECT COUNT(*) FROM IMPORTS.WGHSECTIONS  ;

SELECT * FROM MASTERS.DISTRICTS;
SELECT DISTINCT BLOCKNAME FROM IMPORTS.WGHBLOCKS ;

SELECT DISTINCT BLOCKNAME FROM IMPORTS.WGHBLOCKS WHERE TRIM(UPPER(BLOCKNAME)) NOT IN (SELECT TRIM(UPPER(BLOCKNAME)) FROM MASTERS.BLOCKS);


SELECT 'UPDATE IMPORTS.WGHACPARTS SET BLOCKCODE = ' || BLOCKCODE || ' WHERE ACNO = ' || ACNO || ' AND PARTNO = ' || PARTNO || ';' 
FROM MASTERS.BLOCKS B INNER JOIN IMPORTS.WGHBLOCKS D ON TRIM(UPPER(B.BLOCKNAME)) = TRIM(UPPER(D.BLOCKNAME)) 




--SELECT DISTINCT BLOCKNAME FROM IMPORTS.WGHBLOCKS WHERE TRIM(UPPER(BLOCKNAME)) NOT IN (SELECT TRIM(UPPER(BLOCKNAME)) FROM MASTERS.BLOCKS);


---- EXECUTED UPTO HERE

SELECT * FROM IMPORTS.WGHACPARTS 
WHERE regexp_replace(MAINVILLAGECODE, '\W', '', 'g')  NOT IN (SELECT TRIM(UPPER(VLOCATIONCODE)) FROM MASTERS.VILLAGES);



INSERT INTO MASTERS.ACPARTS
SELECT ACNO, PARTNO, PARTNAME, PARTLOCATIONCATEGORY, NULL AS LATITUDE, NULL AS LONGITUDE, BLOCKCODE, PINCODEX, LEFT(POSTOFFICECODE,5) , LEFT(POLICESTATIONCODE::TEXT,5), 
--regexp_replace(PSBUILDINGID, '\W', '', 'g'), 
LPAD(ACNO::TEXT,3,'0') || LPAD(PARTNO::TEXT,3,'0')  AS PSBUILDINGID,
regexp_replace(MAINVILLAGECODE, '\W', '', 'g'), FVTTYPE, PARTGENDERTYPE, 1, CURRENT_TIMESTAMP FROM IMPORTS.WGHACPARTS
ORDER BY ACNO, PARTNO;



SELECT * FROM IMPORTS.WGHACPARTS;

INSERT INTO MASTERS.POLLINGSTATIONS
SELECT ACNO, PARTNO, PARTNO, PARTNAME, PARTNAME,  
LPAD(ACNO::TEXT,3,'0') || LPAD(PARTNO::TEXT,3,'0')  AS PSBUILDINGID,
PS_BUILDING_NAME,
1, 1, CURRENT_TIMESTAMP FROM IMPORTS.WGHACPARTS
ORDER BY ACNO, PARTNO;

SELECT * FROM MASTERS.ACPARTS WHERE PSBUILDINGID NOT IN (SELECT PSBUILDINGID FROM MASTERS.POLLINGSTATIONS);
SELECT * FROM MASTERS.ACPARTS WHERE MAINVILLAGECODE NOT IN (SELECT VLOCATIONCODE FROM MASTERS.VILLAGES);

SELECT * FROM IMPORTS.WGHSECTIONS WHERE ACNO IS NULL OR PARTNO IS NULL OR SECTIONNO IS NULL OR SECTIONNAME IS NULL 
OR VLOCATIONCODE IS NULL;

INSERT INTO MASTERS.SECTIONS 
SELECT ACNO, PARTNO, SECTIONNO, SECTIONNAME, regexp_replace(VLOCATIONCODE, '\W', '', 'g'), PINCODEX, 1, CURRENT_TIMESTAMP FROM IMPORTS.WGHSECTIONS;

SELECT * FROM MASTERS.SECTIONS WHERE VLOCATIONCODE NOT IN (SELECT VLOCATIONCODE FROM MASTERS.VILLAGES);
