UPDATE MASTERS.ELECTORALROLLREVISIONS
SET 
REVISIONDESCRIPTION  ='Basic Roll of Revision, 2026, prepared in accordance with the extent of the newly delimited Areas and Constituency',
REVISIONYEAR = 2026,
QUALIFYINGDATE= '2026-01-01',
REVISIONTYPE = 'Draft Rolls 2026',
PUBLICATIONDATE = '2026-02-04',
ROLLTYPE = 'Mother Roll',
ENABLED = 'Y'
WHERE REVISIONNO = 0;


UPDATE MASTERS.IDENTITYCARDSMASTERS SET VALIDFROM = '2026-02-01', VALIDTO = '2026-04-30';

UPDATE MASTERS.MASTERTABLE SET ELECTIONDESCRIPTION =  'Elections to the Autonomous District Council - 2026' ,
HEADER3 = 'Elections to the Autonomous District Council - 2026' , 
POLLDATE = '2026-03-01';

 UPDATE MASTERS.ASSEMBLYCONSTITUENCIES SET ACNAME = 'Siju' WHERE ACNO = 1;
 UPDATE MASTERS.ASSEMBLYCONSTITUENCIES SET ACNAME = 'Wagesik  ' WHERE ACNO = 2;
 UPDATE MASTERS.ASSEMBLYCONSTITUENCIES SET ACNAME = 'Silkigre' WHERE ACNO = 3;
 UPDATE MASTERS.ASSEMBLYCONSTITUENCIES SET ACNAME = 'Rongrikimgre' WHERE ACNO = 4;
 UPDATE MASTERS.ASSEMBLYCONSTITUENCIES SET ACNAME = 'Gasuapara' WHERE ACNO = 5;
 UPDATE MASTERS.ASSEMBLYCONSTITUENCIES SET ACNAME = 'Barengapara' WHERE ACNO = 6;
 UPDATE MASTERS.ASSEMBLYCONSTITUENCIES SET ACNAME = 'Babelapara' WHERE ACNO = 7;
 UPDATE MASTERS.ASSEMBLYCONSTITUENCIES SET ACNAME = 'Amongpara' WHERE ACNO = 8;
 UPDATE MASTERS.ASSEMBLYCONSTITUENCIES SET ACNAME = 'Tura' WHERE ACNO = 9;
 UPDATE MASTERS.ASSEMBLYCONSTITUENCIES SET ACNAME = 'Dengnakpara' WHERE ACNO = 10;
 UPDATE MASTERS.ASSEMBLYCONSTITUENCIES SET ACNAME = 'Boldamgre' WHERE ACNO = 11;
 UPDATE MASTERS.ASSEMBLYCONSTITUENCIES SET ACNAME = 'Nogorpara' WHERE ACNO = 12;
 UPDATE MASTERS.ASSEMBLYCONSTITUENCIES SET ACNAME = 'Zikzak' WHERE ACNO = 13;
 UPDATE MASTERS.ASSEMBLYCONSTITUENCIES SET ACNAME = 'Betasing' WHERE ACNO = 14;
 UPDATE MASTERS.ASSEMBLYCONSTITUENCIES SET ACNAME = 'Rochonpara' WHERE ACNO = 15;
 UPDATE MASTERS.ASSEMBLYCONSTITUENCIES SET ACNAME = 'Asanang' WHERE ACNO = 16;
 UPDATE MASTERS.ASSEMBLYCONSTITUENCIES SET ACNAME = 'Balachanda' WHERE ACNO = 17;
 UPDATE MASTERS.ASSEMBLYCONSTITUENCIES SET ACNAME = 'Batabari' WHERE ACNO = 18;
 UPDATE MASTERS.ASSEMBLYCONSTITUENCIES SET ACNAME = 'Shyamnagar' WHERE ACNO = 19;
 UPDATE MASTERS.ASSEMBLYCONSTITUENCIES SET ACNAME = 'Raksamgre' WHERE ACNO = 20;
 UPDATE MASTERS.ASSEMBLYCONSTITUENCIES SET ACNAME = 'Naguapara' WHERE ACNO = 21;
 UPDATE MASTERS.ASSEMBLYCONSTITUENCIES SET ACNAME = 'Jengjal' WHERE ACNO = 22;
 UPDATE MASTERS.ASSEMBLYCONSTITUENCIES SET ACNAME = 'Rongrong' WHERE ACNO = 23;
 UPDATE MASTERS.ASSEMBLYCONSTITUENCIES SET ACNAME = 'Bolsong' WHERE ACNO = 24;
 UPDATE MASTERS.ASSEMBLYCONSTITUENCIES SET ACNAME = 'Damas' WHERE ACNO = 25;
 UPDATE MASTERS.ASSEMBLYCONSTITUENCIES SET ACNAME = 'Kharkutta' WHERE ACNO = 26;
 UPDATE MASTERS.ASSEMBLYCONSTITUENCIES SET ACNAME = 'Samandagre' WHERE ACNO = 27;
 UPDATE MASTERS.ASSEMBLYCONSTITUENCIES SET ACNAME = 'Darugre' WHERE ACNO = 28;
 UPDATE MASTERS.ASSEMBLYCONSTITUENCIES SET ACNAME = 'Williamnagar' WHERE ACNO = 29;



 SELECT * FROM MASTERS.OFFICESACS;

 UPDATE MASTERS.OFFICESACS SET OFFICECODE ='050001' WHERE ACNO = 27;
UPDATE MASTERS.OFFICESACS SET OFFICECODE ='050001' WHERE ACNO = 28;
UPDATE MASTERS.OFFICESACS SET OFFICECODE ='050001' WHERE ACNO = 29;
UPDATE MASTERS.OFFICESACS SET OFFICECODE ='100001' WHERE ACNO = 23;
UPDATE MASTERS.OFFICESACS SET OFFICECODE ='100001' WHERE ACNO = 24;
UPDATE MASTERS.OFFICESACS SET OFFICECODE ='100001' WHERE ACNO = 25;
UPDATE MASTERS.OFFICESACS SET OFFICECODE ='100001' WHERE ACNO = 26;
UPDATE MASTERS.OFFICESACS SET OFFICECODE ='070001' WHERE ACNO = 1;
UPDATE MASTERS.OFFICESACS SET OFFICECODE ='070001' WHERE ACNO = 2;
UPDATE MASTERS.OFFICESACS SET OFFICECODE ='070001' WHERE ACNO = 3;
UPDATE MASTERS.OFFICESACS SET OFFICECODE ='070001' WHERE ACNO = 4;
UPDATE MASTERS.OFFICESACS SET OFFICECODE ='070001' WHERE ACNO = 5;
UPDATE MASTERS.OFFICESACS SET OFFICECODE ='110011' WHERE ACNO = 11;
UPDATE MASTERS.OFFICESACS SET OFFICECODE ='110011' WHERE ACNO = 12;
UPDATE MASTERS.OFFICESACS SET OFFICECODE ='110011' WHERE ACNO = 13;
UPDATE MASTERS.OFFICESACS SET OFFICECODE ='110011' WHERE ACNO = 14;
UPDATE MASTERS.OFFICESACS SET OFFICECODE ='060001' WHERE ACNO = 6;
UPDATE MASTERS.OFFICESACS SET OFFICECODE ='060001' WHERE ACNO = 7;
UPDATE MASTERS.OFFICESACS SET OFFICECODE ='060001' WHERE ACNO = 8;
UPDATE MASTERS.OFFICESACS SET OFFICECODE ='060001' WHERE ACNO = 9;
UPDATE MASTERS.OFFICESACS SET OFFICECODE ='060001' WHERE ACNO = 10;
UPDATE MASTERS.OFFICESACS SET OFFICECODE ='060001' WHERE ACNO = 15;
UPDATE MASTERS.OFFICESACS SET OFFICECODE ='060001' WHERE ACNO = 16;
UPDATE MASTERS.OFFICESACS SET OFFICECODE ='060001' WHERE ACNO = 17;
UPDATE MASTERS.OFFICESACS SET OFFICECODE ='060001' WHERE ACNO = 18;
UPDATE MASTERS.OFFICESACS SET OFFICECODE ='060001' WHERE ACNO = 19;
UPDATE MASTERS.OFFICESACS SET OFFICECODE ='060001' WHERE ACNO = 20;
UPDATE MASTERS.OFFICESACS SET OFFICECODE ='060001' WHERE ACNO = 21;
UPDATE MASTERS.OFFICESACS SET OFFICECODE ='060001' WHERE ACNO = 22;

