ALTER TABLE ELECTIONS."DD_PARTS" RENAME TO DDACPARTS;
ALTER TABLE ELECTIONS."DD_sections" RENAME TO DDSECTIONS;
--ALTER TABLE ELECTIONS."DD_blocks" RENAME TO DDBLOCKS;

ALTER TABLE ELECTIONS.DDACPARTS SET SCHEMA IMPORTS;
ALTER TABLE ELECTIONS.DDSECTIONS SET SCHEMA IMPORTS;
ALTER TABLE ELECTIONS.DDBLOCKS SET SCHEMA IMPORTS;

ALTER TABLE IMPORTS.DDACPARTS ADD COLUMN BLOCKCODE SMALLINT;

SELECT COUNT(*) FROM IMPORTS.DDACPARTS ;

SELECT COUNT(*) FROM IMPORTS.DDSECTIONS  ;

SELECT * FROM MASTERS.DISTRICTS;
SELECT DISTINCT BLOCKNAME FROM IMPORTS.DDBLOCKS ;

SELECT DISTINCT BLOCKNAME FROM IMPORTS.DDBLOCKS WHERE TRIM(UPPER(BLOCKNAME)) NOT IN (SELECT TRIM(UPPER(BLOCKNAME)) FROM MASTERS.BLOCKS);


SELECT 'UPDATE IMPORTS.DDACPARTS SET BLOCKCODE = ' || BLOCKCODE || ' WHERE ACNO = ' || ACNO || ' AND PARTNO = ' || PARTNO || ';' 
FROM MASTERS.BLOCKS B INNER JOIN IMPORTS.DDBLOCKS D ON TRIM(UPPER(B.BLOCKNAME)) = TRIM(UPPER(D.BLOCKNAME)) 




--SELECT DISTINCT BLOCKNAME FROM IMPORTS.DDBLOCKS WHERE TRIM(UPPER(BLOCKNAME)) NOT IN (SELECT TRIM(UPPER(BLOCKNAME)) FROM MASTERS.BLOCKS);


SELECT * FROM IMPORTS.DDACPARTS ORDER BY ACNO, PARTNO


SELECT * FROM IMPORTS.DDACPARTS WHERE regexp_replace(MAINVILLAGECODE, '\W', '', 'g')  NOT IN (SELECT TRIM(UPPER(VLOCATIONCODE)) FROM MASTERS.VILLAGES);


UPDATE IMPORTS.DDACPARTS SET POSTOFFICECODE = 99999 WHERE POSTOFFICECODE IS NULL;

UPDATE IMPORTS.DDACPARTS SET POLICESTATIONCODE = 99999 WHERE POLICESTATIONCODE IS NULL;


INSERT INTO MASTERS.ACPARTS
SELECT ACNO, PARTNO, PARTNAME, PARTLOCATIONCATEGORY, NULL AS LATITUDE, NULL AS LONGITUDE, BLOCKCODE, PINCODEX, LEFT(POSTOFFICECODE,5) , 
regexp_replace(POLICESTATIONCODE, '\W', '', 'g'), 
--LEFT(POLICESTATIONCODE::TEXT,5), 
--regexp_replace(PSBUILDINGID, '\W', '', 'g'), 
LPAD(ACNO::TEXT,3,'0') || LPAD(PARTNO::TEXT,3,'0')  AS PSBUILDINGID,
regexp_replace(MAINVILLAGECODE, '\W', '', 'g'), FVTTYPE, PARTGENDERTYPE, 1, CURRENT_TIMESTAMP FROM IMPORTS.DDACPARTS
ORDER BY ACNO, PARTNO;



SELECT * FROM IMPORTS.DDACPARTS;

INSERT INTO MASTERS.POLLINGSTATIONS
SELECT ACNO, PARTNO, PARTNO, PARTNAME, PARTNAME,  
LPAD(ACNO::TEXT,3,'0') || LPAD(PARTNO::TEXT,3,'0')  AS PSBUILDINGID,
PS_BUILDING_NAME,
1, 1, CURRENT_TIMESTAMP FROM IMPORTS.DDACPARTS
ORDER BY ACNO, PARTNO;

SELECT * FROM MASTERS.ACPARTS WHERE PSBUILDINGID NOT IN (SELECT PSBUILDINGID FROM MASTERS.POLLINGSTATIONS);
SELECT * FROM MASTERS.ACPARTS WHERE MAINVILLAGECODE NOT IN (SELECT VLOCATIONCODE FROM MASTERS.VILLAGES);

SELECT * FROM IMPORTS.DDSECTIONS 
ORDER BY ACNO, PARTNO, SECTIONNO


--- EXECUTED UPTO HERE


INSERT INTO MASTERS.SECTIONS 
SELECT ACNO, PARTNO, SECTIONNO, SECTIONNAME, regexp_replace(VLOCATIONCODE, '\W', '', 'g'), PINCODEX, 1, CURRENT_TIMESTAMP FROM IMPORTS.DDSECTIONS;

SELECT * FROM MASTERS.SECTIONS WHERE VLOCATIONCODE NOT IN (SELECT VLOCATIONCODE FROM MASTERS.VILLAGES);
