ALTER TABLE ELECTIONS."NGH_Parts" RENAME TO NGHACPARTS;
ALTER TABLE ELECTIONS."NGH_sections" RENAME TO NGHSECTIONS;
ALTER TABLE ELECTIONS."NGH_blocks" RENAME TO NGHBLOCKS;

ALTER TABLE ELECTIONS.NGHACPARTS SET SCHEMA IMPORTS;
ALTER TABLE ELECTIONS.NGHSECTIONS SET SCHEMA IMPORTS;
ALTER TABLE ELECTIONS.NGHBLOCKS SET SCHEMA IMPORTS;

ALTER TABLE IMPORTS.NGHACPARTS ADD COLUMN BLOCKCODE SMALLINT;

SELECT COUNT(*) FROM IMPORTS.NGHACPARTS ;
SELECT COUNT(*) FROM IMPORTS.NGHSECTIONS  ;

SELECT * FROM MASTERS.DISTRICTS;
SELECT DISTINCT BLOCKNAME FROM IMPORTS.NGHBLOCKS ;

SELECT DISTINCT BLOCKNAME FROM IMPORTS.NGHBLOCKS WHERE TRIM(UPPER(BLOCKNAME)) NOT IN (SELECT TRIM(UPPER(BLOCKNAME)) FROM MASTERS.BLOCKS);


SELECT 'UPDATE IMPORTS.NGHACPARTS SET BLOCKCODE = ' || BLOCKCODE || ' WHERE ACNO = ' || ACNO || ' AND PARTNO = ' || PARTNO || ';' 
FROM MASTERS.BLOCKS B INNER JOIN IMPORTS.NGHBLOCKS D ON TRIM(UPPER(B.BLOCKNAME)) = TRIM(UPPER(D.BLOCKNAME)) 




--SELECT DISTINCT BLOCKNAME FROM IMPORTS.NGHBLOCKS WHERE TRIM(UPPER(BLOCKNAME)) NOT IN (SELECT TRIM(UPPER(BLOCKNAME)) FROM MASTERS.BLOCKS);


---- EXECUTED UPTO HERE

SELECT * FROM IMPORTS.NGHACPARTS 
WHERE regexp_replace(MAINVILLAGECODE, '\W', '', 'g')  NOT IN (SELECT TRIM(UPPER(VLOCATIONCODE)) FROM MASTERS.VILLAGES);



INSERT INTO MASTERS.ACPARTS
SELECT ACNO, PARTNO, PARTNAME, PARTLOCATIONCATEGORY, NULL AS LATITUDE, NULL AS LONGITUDE, BLOCKCODE, PINCODEX, LEFT(POSTOFFICECODE,5) , LEFT(POLICESTATIONCODE::TEXT,5), 
--regexp_replace(PSBUILDINGID, '\W', '', 'g'), 
LPAD(ACNO::TEXT,3,'0') || LPAD(PARTNO::TEXT,3,'0')  AS PSBUILDINGID,
regexp_replace(MAINVILLAGECODE, '\W', '', 'g'), FVTTYPE, PARTGENDERTYPE, 1, CURRENT_TIMESTAMP FROM IMPORTS.NGHACPARTS
ORDER BY ACNO, PARTNO;



SELECT * FROM IMPORTS.NGHACPARTS;

INSERT INTO MASTERS.POLLINGSTATIONS
SELECT ACNO, PARTNO, PARTNO, PARTNAME, PARTNAME,  
LPAD(ACNO::TEXT,3,'0') || LPAD(PARTNO::TEXT,3,'0')  AS PSBUILDINGID,
PS_BUILDING_NAME,
1, 1, CURRENT_TIMESTAMP FROM IMPORTS.NGHACPARTS
ORDER BY ACNO, PARTNO;

SELECT * FROM MASTERS.ACPARTS WHERE PSBUILDINGID NOT IN (SELECT PSBUILDINGID FROM MASTERS.POLLINGSTATIONS);
SELECT * FROM MASTERS.ACPARTS WHERE MAINVILLAGECODE NOT IN (SELECT VLOCATIONCODE FROM MASTERS.VILLAGES);

SELECT * FROM IMPORTS.NGHSECTIONS WHERE ACNO IS NULL OR PARTNO IS NULL OR SECTIONNO IS NULL OR SECTIONNAME IS NULL 
OR VLOCATIONCODE IS NULL;

INSERT INTO MASTERS.SECTIONS 
SELECT ACNO, PARTNO, SECTIONNO, SECTIONNAME, regexp_replace(VLOCATIONCODE, '\W', '', 'g'), PINCODEX, 1, CURRENT_TIMESTAMP FROM IMPORTS.NGHSECTIONS;

SELECT * FROM MASTERS.SECTIONS WHERE VLOCATIONCODE NOT IN (SELECT VLOCATIONCODE FROM MASTERS.VILLAGES);
