ALTER TABLE ELECTIONS."SGH_Parts" RENAME TO SGHACPARTS;
ALTER TABLE ELECTIONS."SGH_sections" RENAME TO SGHSECTIONS;
ALTER TABLE ELECTIONS."SGH_blocks" RENAME TO SGHBLOCKS;

ALTER TABLE ELECTIONS.SGHACPARTS SET SCHEMA IMPORTS;
ALTER TABLE ELECTIONS.SGHSECTIONS SET SCHEMA IMPORTS;
ALTER TABLE ELECTIONS.SGHBLOCKS SET SCHEMA IMPORTS;

ALTER TABLE IMPORTS.SGHACPARTS ADD COLUMN BLOCKCODE SMALLINT;

SELECT COUNT(*) FROM IMPORTS .SGHACPARTS ;

SELECT COUNT(*) FROM IMPORTS .SGHSECTIONS  ;

SELECT DISTINCT BLOCKNAME FROM IMPORTS.SGHBLOCKS ;


UPDATE IMPORTS.SGHBLOCKS SET BLOCKNAME = 'CHOKPOT' WHERE BLOCKNAME ='CHOKPPOT';


SELECT * FROM MASTERS.DISTRICTS

SELECT DISTINCT BLOCKNAME FROM IMPORTS.SGHBLOCKS WHERE BLOCKNAME NOT IN (SELECT BLOCKNAME FROM MASTERS.BLOCKS);




SELECT 'UPDATE IMPORTS.SGHACPARTS SET BLOCKCODE = ' || BLOCKCODE || ' WHERE ACNO = ' || ACNO || ' AND PARTNO = ' || PARTNO || ';' 
FROM MASTERS.BLOCKS B INNER JOIN IMPORTS.SGHBLOCKS D ON TRIM(UPPER(B.BLOCKNAME)) = TRIM(UPPER(D.BLOCKNAME)) 




SELECT * FROM MASTERS.VILLAGES



UPDATE IMPORTS.SGHACPARTS SET MAINVILLAGECODE ='0500000000001017R' WHERE ACNO = 27 AND PARTNO = 40;
INSERT INTO MASTERS.VILLAGES VALUES ('0700000000000001U', 5, NULL, 'BAGHMARA', 'T', 1, CURRENT_TIMESTAMP);


SELECT * FROM MASTERS.POSTOFFICES;

SELECT * FROM IMPORTS.SGHACPARTS;


UPDATE IMPORTS.SGHACPARTS SET POSTOFFICECODE = '07008' WHERE POSTOFFICECODE = '7008';
UPDATE IMPORTS.SGHACPARTS SET POSTOFFICECODE = '07018' WHERE POSTOFFICECODE = '7018';
UPDATE IMPORTS.SGHACPARTS SET POSTOFFICECODE = '07005' WHERE POSTOFFICECODE = '7005';
UPDATE IMPORTS.SGHACPARTS SET POSTOFFICECODE = '0' || POSTOFFICECODE  WHERE LENGTH(TRIM(POSTOFFICECODE)) =4;


UPDATE IMPORTS.SGHACPARTS SET POLICESTATIONCODE = '07001' WHERE POLICESTATIONCODE = '7001';
UPDATE IMPORTS.SGHACPARTS SET POLICESTATIONCODE = '07003' WHERE POLICESTATIONCODE = '7003';
UPDATE IMPORTS.SGHACPARTS SET POLICESTATIONCODE = '07005' WHERE POLICESTATIONCODE = '7005';

UPDATE IMPORTS.SGHACPARTS SET POLICESTATIONCODE = '0' || POLICESTATIONCODE  WHERE LENGTH(TRIM(POLICESTATIONCODE)) =4



INSERT INTO MASTERS.ACPARTS
SELECT ACNO, PARTNO, PARTNAME, PARTLOCATIONCATEGORY, NULL LATITUDE, NULL LONGITUDE, BLOCKCODE, PINCODEX, LEFT(POSTOFFICECODE,5) , LEFT(POLICESTATIONCODE,5), 
--regexp_replace(PSBUILDINGID, '\W', '', 'g'), 
LPAD(ACNO::TEXT,3,'0') || LPAD(PARTNO::TEXT,3,'0')  AS PSBUILDINGID,
regexp_replace(MAINVILLAGECODE, '\W', '', 'g'), FVTTYPE, PARTGENDERTYPE, 1, CURRENT_TIMESTAMP FROM IMPORTS.SGHACPARTS
ORDER BY ACNO, PARTNO;



SELECT * FROM IMPORTS.SGHACPARTS;

INSERT INTO MASTERS.POLLINGSTATIONS
SELECT ACNO, PARTNO, PARTNO, PARTNAME, PARTNAME,  
LPAD(ACNO::TEXT,3,'0') || LPAD(PARTNO::TEXT,3,'0')  AS PSBUILDINGID,
PS_BUILDING_NAME,
1, 1, CURRENT_TIMESTAMP FROM IMPORTS.SGHACPARTS
ORDER BY ACNO, PARTNO;



SELECT * FROM MASTERS.ACPARTS WHERE PSBUILDINGID NOT IN (SELECT PSBUILDINGID FROM MASTERS.POLLINGSTATIONS);

SELECT * FROM MASTERS.ACPARTS WHERE MAINVILLAGECODE NOT IN (SELECT VLOCATIONCODE FROM MASTERS.VILLAGES);

SELECT * FROM IMPORTS.SGHSECTIONS WHERE ACNO IS NULL OR PARTNO IS NULL OR SECTIONNO IS NULL OR SECTIONNAME IS NULL 
OR VLOCATIONCODE IS NULL;

INSERT INTO MASTERS.SECTIONS 
SELECT ACNO, PARTNO, SECTIONNO, SECTIONNAME, regexp_replace(VLOCATIONCODE, '\W', '', 'g'), PINCODEX, 1, CURRENT_TIMESTAMP FROM IMPORTS.SGHSECTIONS;

SELECT * FROM MASTERS.SECTIONS WHERE VLOCATIONCODE NOT IN (SELECT VLOCATIONCODE FROM MASTERS.VILLAGES);
