/*
INSERT INTO SOURCES.AC_LIST SELECT "ID", "DISTRICT_CD", "STATE_CD", "ASMBLY_NAME", "ASMBLY_NO", "ASMBLY_NAME",  NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL,  NULL, NULL, NULL, NULL, NULL FROM IMPORTS."ECI_AC_LIST";

SELECT * FROM SOURCES.AC_LIST ORDER BY ASMBLY_NO;


INSERT INTO SOURCES.PART_LIST
SELECT 
"SLNO",
"DISTRICT_CD",
"STATE_CD",
"ASMBLY_NO",
"PART_NAME",
"PART_NUMBER",
"PART_NAME_L1",
"PART_CATEGORY",
"PART_NAME_L2",
0,
"PART_LAT_LONG",
"PART_LONG",
"BLOCK_MUNICIPAL_NO",
"REV_CIRCLE_NO",
0,
"POST_OFFICE_ID",
"POLICE_ST_ID",
"PSBUILDING_ID",
"PSBUILDING_NAME_AND_ADDRESS",
"PS_ROOM_DETAILS",
"PSBUILDING_NAMEL1_AND_ADDRESSL1",
"PS_ROOM_DETAILS_L1",
"PS_ROOM_DETAILS_L2",
"TOWN_NO",
"PANCHAYAT_NO",
"WARD_NO",
"MAIN_VILLAGE",
"CAPACITY",
"VILLAGE_ID",
"FVT_TYPE",
"PART_NUMBER_OLD",
"PS_TYPE",
"PS_TYPE_V1",
"PS_TYPE_V2"
"ID",
0
FROM IMPORTS."ECI_PART_LIST" SELECT * FROM SOURCES.PART_LIST WHERE ASMBLY_NO = '60'
*/

INSERT INTO SOURCES.SECTION_LIST
SELECT 
"SLNO",
"DISTRICT_CD",
"STATE_CD",
"ASMBLY_NO",
"PART_NO",
"SECTION_NAME",
"SECTION_NO",
"SECTION_NAME_L1",
"PANCHAYAT_ID",
"SECTION_NAME_L2",
"TOWN_NO",
"PIN_CODE",
"WARD_NO",
"ID",
"VLOCATION"
FROM IMPORTS."ECI_SECTION_LIST";


SELECT * FROM SOURCES.SECTION_LIST
ORDER BY ASMBLY_NO, PART_NO;


UPDATE IMPORTS."ECI_POLICE_STATIONS" SET "PSTATION_NAME" = 'DAMALGRE.' WHERE "PS_ID"= 6009	AND 	"PSTATION_NAME" = 'DAMALGRE'
UPDATE IMPORTS."ECI_POLICE_STATIONS" SET "PSTATION_NAME" = 'DALU.' WHERE "PS_ID"= 11004	AND 	"PSTATION_NAME" = 'DALU'

INSERT INTO MASTERS.POLICESTATIONS
SELECT  D.SLNO, "POLICEST_NO", "PS_ID", "PSTATION_NAME", 1, current_timestamp FROM SOURCES.DIST_LIST D INNER JOIN IMPORTS."ECI_POLICE_STATIONS" PS ON D.DISTRICT_CD = PS."DISTRICT_CD";


UPDATE MASTERS.POLICESTATIONS SET POLICESTATIONCODE = '0' || POLICESTATIONCODE WHERE LENGTH(POLICESTATIONCODE)= 4;



INSERT INTO MASTERS.POSTOFFICES
SELECT  D.SLNO, "POSTOFF_NO",  LEFT("POST_OFFICE_ID",5), "POST_OFFICE_NAME", "PO_PIN" , 1, current_timestamp FROM SOURCES.DIST_LIST D INNER JOIN IMPORTS."ECI_POST_OFFICES" PS ON D.DISTRICT_CD = PS."DISTRICT_CD";

INSERT INTO MASTERS.BLOCKS 
SELECT DISTINCT D.SLNO, 
--B."SLNO", 
65 + ROW_NUMBER() OVER(ORDER BY D.SLNO, "BLOCK_MUNICIPAL_NAME") , 
"BLOCK_MUNICIPAL_NO", "BLOCK_MUNICIPAL_NAME" , 1, CURRENT_DATE FROM SOURCES.DIST_LIST D INNER JOIN IMPORTS."ECI_BLOCKS" B  ON D.DISTRICT_CD = B."DISTRICT_CD" WHERE 1 = 1 
AND "SLNO" <> 15 
ORDER BY D.SLNO, "BLOCK_MUNICIPAL_NAME";


INSERT INTO MASTERS.VILLAGES 
SELECT regexp_replace(VLOCATION, '\W', '', 'g'), D.SLNO, "PANCHAYAT_ID", "VILLAGE_NAME", "VILLAGE_TYPE", 1, CURRENT_TIMESTAMP FROM 
SOURCES.DIST_LIST D INNER JOIN IMPORTS."ECI_VILLAGES" V ON D.DISTRICT_CD = V."DISTRICT_CD";
