SELECT 'SELECT ''' || TABLE_NAME || ''' AS TABLENAME, COUNT(*) FROM ' || TABLE_SCHEMA || '.' ||  TABLE_NAME || ' UNION ALL '   FROM INFORMATION_SCHEMA.TABLES 
WHERE TABLE_SCHEMA IN ('elections', 'erolls', 'evms', 'imports', 'logs', 'masters', 'sources', 'users')
ORDER BY TABLE_SCHEMA, TABLE_NAME;


 SELECT 'countingallocation1' AS TABLENAME, COUNT(*) FROM elections.countingallocation1 UNION ALL  
 SELECT 'countingallocation2' AS TABLENAME, COUNT(*) FROM elections.countingallocation2 UNION ALL  
 SELECT 'countingallocation3' AS TABLENAME, COUNT(*) FROM elections.countingallocation3 UNION ALL  
 SELECT 'countinghalls' AS TABLENAME, COUNT(*) FROM elections.countinghalls UNION ALL  
 SELECT 'countinghallsacs' AS TABLENAME, COUNT(*) FROM elections.countinghallsacs UNION ALL  
 SELECT 'countingreserves' AS TABLENAME, COUNT(*) FROM elections.countingreserves UNION ALL  
 SELECT 'countingtables' AS TABLENAME, COUNT(*) FROM elections.countingtables UNION ALL  
 SELECT 'countingvenues' AS TABLENAME, COUNT(*) FROM elections.countingvenues UNION ALL  
 SELECT 'exemptedpersonnel' AS TABLENAME, COUNT(*) FROM elections.exemptedpersonnel UNION ALL  
 SELECT 'otherpersonnel' AS TABLENAME, COUNT(*) FROM elections.otherpersonnel UNION ALL  
 SELECT 'personnel' AS TABLENAME, COUNT(*) FROM elections.personnel UNION ALL  
 SELECT 'personnelappointment' AS TABLENAME, COUNT(*) FROM elections.personnelappointment UNION ALL  
 SELECT 'personnelappointmentletters' AS TABLENAME, COUNT(*) FROM elections.personnelappointmentletters UNION ALL  
 SELECT 'personnelexperience' AS TABLENAME, COUNT(*) FROM elections.personnelexperience UNION ALL  
 SELECT 'pollingallocation1' AS TABLENAME, COUNT(*) FROM elections.pollingallocation1 UNION ALL  
 SELECT 'pollingallocation2' AS TABLENAME, COUNT(*) FROM elections.pollingallocation2 UNION ALL  
 SELECT 'pollingallocation3' AS TABLENAME, COUNT(*) FROM elections.pollingallocation3 UNION ALL  
 SELECT 'pollingreserves' AS TABLENAME, COUNT(*) FROM elections.pollingreserves UNION ALL  
 SELECT 'trainingattendance' AS TABLENAME, COUNT(*) FROM elections.trainingattendance UNION ALL  
 SELECT 'trainingletternoformat' AS TABLENAME, COUNT(*) FROM elections.trainingletternoformat UNION ALL  
 SELECT 'trainingpersonnel' AS TABLENAME, COUNT(*) FROM elections.trainingpersonnel UNION ALL  
 SELECT 'trainingphases' AS TABLENAME, COUNT(*) FROM elections.trainingphases UNION ALL  
 SELECT 'trainingsessions' AS TABLENAME, COUNT(*) FROM elections.trainingsessions UNION ALL  
 SELECT 'trainingtypes' AS TABLENAME, COUNT(*) FROM elections.trainingtypes UNION ALL  
 SELECT 'trainingvenues' AS TABLENAME, COUNT(*) FROM elections.trainingvenues UNION ALL  
 SELECT 'vdistrictsusers' AS TABLENAME, COUNT(*) FROM elections.vdistrictsusers UNION ALL  
 SELECT 'vehicles' AS TABLENAME, COUNT(*) FROM elections.vehicles UNION ALL  
 SELECT 'vofficesusers' AS TABLENAME, COUNT(*) FROM elections.vofficesusers UNION ALL  
 SELECT 'vwcountingallocation2' AS TABLENAME, COUNT(*) FROM elections.vwcountingallocation2 UNION ALL  
 SELECT 'vwcountingallocation3' AS TABLENAME, COUNT(*) FROM elections.vwcountingallocation3 UNION ALL  
 SELECT 'vwpersonnel' AS TABLENAME, COUNT(*) FROM elections.vwpersonnel UNION ALL  
 SELECT 'vwpollingallocation2' AS TABLENAME, COUNT(*) FROM elections.vwpollingallocation2 UNION ALL  
 SELECT 'vwpollingallocation3' AS TABLENAME, COUNT(*) FROM elections.vwpollingallocation3 UNION ALL  
 SELECT 'vwtraining' AS TABLENAME, COUNT(*) FROM elections.vwtraining UNION ALL  
 SELECT 'acpartslock' AS TABLENAME, COUNT(*) FROM erolls.acpartslock UNION ALL  
 SELECT 'electoralrolls' AS TABLENAME, COUNT(*) FROM erolls.electoralrolls UNION ALL  
 SELECT 'electoralrollssup' AS TABLENAME, COUNT(*) FROM erolls.electoralrollssup UNION ALL  
 SELECT 'electoralrollstemp' AS TABLENAME, COUNT(*) FROM erolls.electoralrollstemp UNION ALL  
 SELECT 'supplements' AS TABLENAME, COUNT(*) FROM erolls.supplements UNION ALL  
 SELECT 'evmallocation1' AS TABLENAME, COUNT(*) FROM evms.evmallocation1 UNION ALL  
 SELECT 'evmallocation2' AS TABLENAME, COUNT(*) FROM evms.evmallocation2 UNION ALL  
 SELECT 'evmreservepercentages' AS TABLENAME, COUNT(*) FROM evms.evmreservepercentages UNION ALL  
 SELECT 'votingunits' AS TABLENAME, COUNT(*) FROM evms.votingunits UNION ALL  
 SELECT 'offices' AS TABLENAME, COUNT(*) FROM logs.offices UNION ALL  
 SELECT 'personnel' AS TABLENAME, COUNT(*) FROM logs.personnel UNION ALL  
 SELECT 'pollingallocation2' AS TABLENAME, COUNT(*) FROM logs.pollingallocation2 UNION ALL  
 SELECT 'psparameters' AS TABLENAME, COUNT(*) FROM logs.psparameters UNION ALL  
 SELECT 'sectorofficers' AS TABLENAME, COUNT(*) FROM logs.sectorofficers UNION ALL  
 SELECT 'sectors' AS TABLENAME, COUNT(*) FROM logs.sectors UNION ALL  
 SELECT 'sectorsps' AS TABLENAME, COUNT(*) FROM logs.sectorsps UNION ALL  
 SELECT 'trainingpersonnel' AS TABLENAME, COUNT(*) FROM logs.trainingpersonnel UNION ALL  
 SELECT 'trainingsessions' AS TABLENAME, COUNT(*) FROM logs.trainingsessions UNION ALL  
 SELECT 'trainingvenues' AS TABLENAME, COUNT(*) FROM logs.trainingvenues UNION ALL  
 SELECT 'acparts' AS TABLENAME, COUNT(*) FROM masters.acparts UNION ALL  
 SELECT 'assemblyconstituencies' AS TABLENAME, COUNT(*) FROM masters.assemblyconstituencies UNION ALL  
 SELECT 'blocks' AS TABLENAME, COUNT(*) FROM masters.blocks UNION ALL  
 SELECT 'cells' AS TABLENAME, COUNT(*) FROM masters.cells UNION ALL  
 SELECT 'countingmastertable' AS TABLENAME, COUNT(*) FROM masters.countingmastertable UNION ALL  
 SELECT 'districts' AS TABLENAME, COUNT(*) FROM masters.districts UNION ALL  
 SELECT 'electoralrollrevisions' AS TABLENAME, COUNT(*) FROM masters.electoralrollrevisions UNION ALL  
 SELECT 'genders' AS TABLENAME, COUNT(*) FROM masters.genders UNION ALL  
 SELECT 'identitycardsmasters' AS TABLENAME, COUNT(*) FROM masters.identitycardsmasters UNION ALL  
 SELECT 'mastertable' AS TABLENAME, COUNT(*) FROM masters.mastertable UNION ALL  
 SELECT 'materialmovement' AS TABLENAME, COUNT(*) FROM masters.materialmovement UNION ALL  
 SELECT 'officecategories' AS TABLENAME, COUNT(*) FROM masters.officecategories UNION ALL  
 SELECT 'offices' AS TABLENAME, COUNT(*) FROM masters.offices UNION ALL  
 SELECT 'officesacs' AS TABLENAME, COUNT(*) FROM masters.officesacs UNION ALL  
 SELECT 'pages' AS TABLENAME, COUNT(*) FROM masters.pages UNION ALL  
 SELECT 'parliamentaryconstituencies' AS TABLENAME, COUNT(*) FROM masters.parliamentaryconstituencies UNION ALL  
 SELECT 'personnelcategories' AS TABLENAME, COUNT(*) FROM masters.personnelcategories UNION ALL  
 SELECT 'policestations' AS TABLENAME, COUNT(*) FROM masters.policestations UNION ALL  
 SELECT 'pollingstations' AS TABLENAME, COUNT(*) FROM masters.pollingstations UNION ALL  
 SELECT 'postoffices' AS TABLENAME, COUNT(*) FROM masters.postoffices UNION ALL  
 SELECT 'processes' AS TABLENAME, COUNT(*) FROM masters.processes UNION ALL  
 SELECT 'psparameters' AS TABLENAME, COUNT(*) FROM masters.psparameters UNION ALL  
 SELECT 'psrandomizationtypes' AS TABLENAME, COUNT(*) FROM masters.psrandomizationtypes UNION ALL  
 SELECT 'randomizationtypes' AS TABLENAME, COUNT(*) FROM masters.randomizationtypes UNION ALL  
 SELECT 'relations' AS TABLENAME, COUNT(*) FROM masters.relations UNION ALL  
 SELECT 'reservesreporting' AS TABLENAME, COUNT(*) FROM masters.reservesreporting UNION ALL  
 SELECT 'returningofficers' AS TABLENAME, COUNT(*) FROM masters.returningofficers UNION ALL  
 SELECT 'rndcountingcategoriesmap' AS TABLENAME, COUNT(*) FROM masters.rndcountingcategoriesmap UNION ALL  
 SELECT 'rndpspersonnelcategoriesmap' AS TABLENAME, COUNT(*) FROM masters.rndpspersonnelcategoriesmap UNION ALL  
 SELECT 'sections' AS TABLENAME, COUNT(*) FROM masters.sections UNION ALL  
 SELECT 'sectorofficers' AS TABLENAME, COUNT(*) FROM masters.sectorofficers UNION ALL  
 SELECT 'sectors' AS TABLENAME, COUNT(*) FROM masters.sectors UNION ALL  
 SELECT 'sectorsps' AS TABLENAME, COUNT(*) FROM masters.sectorsps UNION ALL  
 SELECT 'sensitivities' AS TABLENAME, COUNT(*) FROM masters.sensitivities UNION ALL  
 SELECT 'states' AS TABLENAME, COUNT(*) FROM masters.states UNION ALL  
 SELECT 'tadarates' AS TABLENAME, COUNT(*) FROM masters.tadarates UNION ALL  
 SELECT 'villages' AS TABLENAME, COUNT(*) FROM masters.villages UNION ALL  
 SELECT 'villagestmp' AS TABLENAME, COUNT(*) FROM masters.villagestmp UNION ALL  
 SELECT 'votersflags' AS TABLENAME, COUNT(*) FROM masters.votersflags UNION ALL  
 SELECT 'votingunittypes' AS TABLENAME, COUNT(*) FROM masters.votingunittypes UNION ALL  
 SELECT 'vwacpartsps' AS TABLENAME, COUNT(*) FROM masters.vwacpartsps UNION ALL  
 SELECT 'ac_list' AS TABLENAME, COUNT(*) FROM sources.ac_list UNION ALL  
 SELECT 'blocks' AS TABLENAME, COUNT(*) FROM sources.blocks UNION ALL  
 SELECT 'dist_list' AS TABLENAME, COUNT(*) FROM sources.dist_list UNION ALL  
 SELECT 'nnn' AS TABLENAME, COUNT(*) FROM sources.nnn UNION ALL  
 SELECT 'officesacs' AS TABLENAME, COUNT(*) FROM sources.officesacs UNION ALL  
 SELECT 'part_list' AS TABLENAME, COUNT(*) FROM sources.part_list UNION ALL  
 SELECT 'police_stations' AS TABLENAME, COUNT(*) FROM sources.police_stations UNION ALL  
 SELECT 'post_offices' AS TABLENAME, COUNT(*) FROM sources.post_offices UNION ALL  
 SELECT 'ps_buildings' AS TABLENAME, COUNT(*) FROM sources.ps_buildings UNION ALL  
 SELECT 'section_list' AS TABLENAME, COUNT(*) FROM sources.section_list UNION ALL  
 SELECT 'sourceelectoralrolls' AS TABLENAME, COUNT(*) FROM sources.sourceelectoralrolls UNION ALL  
 SELECT 'sub_divisions' AS TABLENAME, COUNT(*) FROM sources.sub_divisions UNION ALL  
 SELECT 'villages' AS TABLENAME, COUNT(*) FROM sources.villages UNION ALL  
 SELECT 'audittrial' AS TABLENAME, COUNT(*) FROM users.audittrial UNION ALL  
 SELECT 'useraccounts' AS TABLENAME, COUNT(*) FROM users.useraccounts UNION ALL  
 SELECT 'useroffices' AS TABLENAME, COUNT(*) FROM users.useroffices UNION ALL  
 SELECT 'userpages' AS TABLENAME, COUNT(*) FROM users.userpages