SQL SERVER - DUPLICATE SL NO




ALTER TABLE DBO.EROLL_DATA ADD TOBEMIGRATED CHAR(1) NOT NULL DEFAULT 'Y';

-- UNIQUE AC, PARTNO, SLNOINPART
SELECT  ASSEMBLY_CONSTITUENCY_NUMBER , PART_NUMBER ,PART_SERIAL_NUMBER 
FROM EROLL_DATA WHERE 1= 1
GROUP BY ASSEMBLY_CONSTITUENCY_NUMBER , PART_NUMBER ,PART_SERIAL_NUMBER 
HAVING COUNT(*) = 1 ;



-- UNIQUE AC, PARTNO, SLNOINPART
SELECT  ASSEMBLY_CONSTITUENCY_NUMBER , PART_NUMBER ,PART_SERIAL_NUMBER 
FROM EROLL_DATA WHERE 1= 1
GROUP BY ASSEMBLY_CONSTITUENCY_NUMBER , PART_NUMBER ,PART_SERIAL_NUMBER 
HAVING COUNT(*) > 2 ;


SELECT	D.ASSEMBLY_CONSTITUENCY_NUMBER,
        D.PART_NUMBER,
        D.PART_SERIAL_NUMBER, 
		VOTER_EPIC EPIC_NUMBER, APPLICANT_FIRST_NAME_L1 APPLICANT_FIRST_NAME, APPLICANT_LAST_NAME_L1 APPLICANT_LAST_NAME, RELATION_TYPE, VOTER_RELATION_NAME RELATION_NAME, HOUSE_NUMBER, 
DOB, VOTER_RELATION_LNAME RELATION_L_NAME , IS_ACTIVE
FROM EROLL_DATA e
JOIN (
    SELECT ASSEMBLY_CONSTITUENCY_NUMBER,PART_NUMBER, PART_SERIAL_NUMBER
    FROM EROLL_DATA WHERE 1 = 1 
    GROUP BY ASSEMBLY_CONSTITUENCY_NUMBER, PART_NUMBER, PART_SERIAL_NUMBER
    HAVING COUNT(*) > 1
) d
ON  e.ASSEMBLY_CONSTITUENCY_NUMBER = d.ASSEMBLY_CONSTITUENCY_NUMBER
AND e.PART_NUMBER = d.PART_NUMBER
AND e.PART_SERIAL_NUMBER = d.PART_SERIAL_NUMBER
WHERE IS_ACTIVE <> 'Y'
ORDER BY D.ASSEMBLY_CONSTITUENCY_NUMBER,D.PART_NUMBER, D.PART_SERIAL_NUMBER;

then update the column TOBEMIGRATED TO 'N' FOR THOSE DUPLICATES AND WHERE IS_ACTIVE <> 'Y'
