INSERT INTO MASTERS.DISTRICTS VALUES (13,'AMLAREM','AMLAREM','S', 17, 275,'AML','1 - Shillong (ST) Parliamentary Constituency');
INSERT INTO MASTERS.DISTRICTS VALUES (14,'PYNURSLA','PYNURSLA','S', 17, 275,'PYN','1 - Shillong (ST) Parliamentary Constituency');
INSERT INTO MASTERS.DISTRICTS VALUES (15,'SOHRA','SOHRA','S', 17, 275,'SOH','1 - Shillong (ST) Parliamentary Constituency');
INSERT INTO MASTERS.DISTRICTS VALUES (16,'CHOKPOT','CHOKPOT','S', 17, 275,'CKT','2 - Tura (ST) Parliamentary Constituency');
INSERT INTO MASTERS.DISTRICTS VALUES (17,'RAKSAMGRE','RAKSAMGRE','S', 17, 275,'RAK','2 - Tura (ST) Parliamentary Constituency');
INSERT INTO MASTERS.DISTRICTS VALUES (18,'DADENGGRE','DADENGGRE','S', 17, 275,'DAD','2 - Tura (ST) Parliamentary Constituency');
INSERT INTO MASTERS.DISTRICTS VALUES (19,'MAWSHYNRUT','MAWSHYNRUT','S', 17, 275,'MRT','2 - Tura (ST) Parliamentary Constituency');


ALTER TABLE MASTERS.DISTRICTS ADD COLUMN REFERENCEDISTRICTCODE SMALLINT DEFAULT 1;

UPDATE MASTERS.DISTRICTS SET REFERENCEDISTRICTCODE = DISTRICTCODE WHERE DISTRICTSDO = 'D';
UPDATE MASTERS.DISTRICTS SET REFERENCEDISTRICTCODE = 1 WHERE DISTRICTCODE = 13;
UPDATE MASTERS.DISTRICTS SET REFERENCEDISTRICTCODE = 3 WHERE DISTRICTCODE = 14;
UPDATE MASTERS.DISTRICTS SET REFERENCEDISTRICTCODE = 3 WHERE DISTRICTCODE = 15;
UPDATE MASTERS.DISTRICTS SET REFERENCEDISTRICTCODE = 7 WHERE DISTRICTCODE = 16;
UPDATE MASTERS.DISTRICTS SET REFERENCEDISTRICTCODE = 6 WHERE DISTRICTCODE = 17;
UPDATE MASTERS.DISTRICTS SET REFERENCEDISTRICTCODE = 6 WHERE DISTRICTCODE = 18;
UPDATE MASTERS.DISTRICTS SET REFERENCEDISTRICTCODE = 4 WHERE DISTRICTCODE = 19;

INSERT INTO MASTERS.BLOCKS SELECT "DIST_NO", CASE WHEN "SUB_DIV_NO" = 0 THEN NULL ELSE "SUB_DIV_NO" END,  "BLOCK_NO", "BLOCK_NAME_EN", 1, CURRENT_DATE FROM  IMPORTS.BLOCKS ;


