ALTER TABLE ELECTIONS.WJHACPARTS SET SCHEMA IMPORTS;
ALTER TABLE ELECTIONS.WJHSECTIONS SET SCHEMA IMPORTS;
ALTER TABLE ELECTIONS.WJHBLOCKS SET SCHEMA IMPORTS;


SELECT *  FROM MASTERS.ACPARTS;

SELECT LENGTH(POSTOFFICECODE) FROM MASTERS.POSTOFFICES;



INSERT INTO MASTERS.ACPARTS
SELECT ACNO, PARTNO, PARTNAME, PARTLOCATIONCATEGORY, LATITUDE, LONGITUDE, NULL, PINCODEX, LEFT(POSTOFFICECODE,5) , LEFT(POLICESTATIONCODE,5), regexp_replace(PSBUILDINGID, '\W', '', 'g'), MAINVILLAGECODE, FVTTYPE, PARTGENDERTYPE, 1, CURRENT_TIMESTAMP FROM IMPORTS.WJHACPARTS;


SELECT * FROM MASTERS.ACPARTS WHERE PSBUILDINGID IS NULL;
SELECT * FROM MASTERS.ACPARTS WHERE PSBUILDINGID NOT IN (SELECT PSBUILDINGID FROM MASTERS.POLLINGSTATIONS);

-- POPULATE THE PS WHICH ARE NOT AVAILAABLE IN THE MASTER POLLING STATIONS
INSERT INTO MASTERS.POLLINGSTATIONS SELECT ACNO, PARTNO, 1, 'N.A.', 'N.A.', PSBUILDINGID, 'N.A.', 1,1,CURRENT_TIMESTAMP FROM MASTERS.ACPARTS WHERE PSBUILDINGID NOT IN (SELECT PSBUILDINGID FROM MASTERS.POLLINGSTATIONS);
SELECT 'UPDATE MASTERS.ACPARTS SET BLOCKCODE = ' || BLOCKCODE || ' WHERE ACNO = ' || ACNO || ' AND PARTNO = ' || PARTNO || ';' FROM MASTERS.BLOCKS B INNER JOIN IMPORTS.WJHBLOCKS D ON TRIM(UPPER(B.BLOCKNAME)) = TRIM(UPPER(D.BLOCKNAME)) 


SELECT * FROM MASTERS.ACPARTS WHERE MAINVILLAGECODE IS NULL;

SELECT * FROM MASTERS.ACPARTS WHERE MAINVILLAGECODE NOT IN (SELECT VLOCATIONCODE FROM MASTERS.VILLAGES);

UPDATE MASTERS.ACPARTS SET MAINVILLAGECODE = (SELECT VLOCATIONCODE FROM MASTERS.VILLAGES WHERE VILLAGENAME = 'NONGPOH' ) WHERE DISTRICTCODE = 2 AND FVTTYPE = 'T';


UPDATE MASTERS.ACPARTS SET BLOCKCODE = (SELECT BLOCKCODE FROM MASTERS.BLOCKS WHERE TRIM(UPPER(BLOCKNAME)) ='JIRANG') WHERE ACNO = 1;
UPDATE MASTERS.ACPARTS SET BLOCKCODE = (SELECT BLOCKCODE FROM MASTERS.BLOCKS WHERE TRIM(UPPER(BLOCKNAME)) ='UMLING') WHERE ACNO = 2;
UPDATE MASTERS.ACPARTS SET BLOCKCODE = (SELECT BLOCKCODE FROM MASTERS.BLOCKS WHERE TRIM(UPPER(BLOCKNAME)) ='UMSNING') WHERE ACNO = 3;
UPDATE MASTERS.ACPARTS SET BLOCKCODE = (SELECT BLOCKCODE FROM MASTERS.BLOCKS WHERE TRIM(UPPER(BLOCKNAME)) ='UMSNING') WHERE ACNO = 4;
UPDATE MASTERS.ACPARTS SET BLOCKCODE = (SELECT BLOCKCODE FROM MASTERS.BLOCKS WHERE TRIM(UPPER(BLOCKNAME)) ='UMROI') WHERE ACNO = 5;


INSERT INTO MASTERS.SECTIONS SELECT ACNO, PARTNO, SECTIONNO, SECTIONNAME, VLOCATIONCODE, PINCODEX, 1, CURRENT_TIMESTAMP FROM IMPORTS.WJHSECTIONS;

SELECT * FROM MASTERS.SECTIONS WHERE VLOCATIONCODE NOT IN (SELECT VLOCATIONCODE FROM MASTERS.VILLAGES);

UPDATE MASTERS.SECTIONS SET VLOCATIONCODE = (SELECT VLOCATIONCODE FROM MASTERS.VILLAGES WHERE VILLAGENAME = 'NONGPOH' )
WHERE ACNO = 2 AND VLOCATIONCODE LIKE '%U';




