ALTER TABLE IMPORTS."AC_LIST" RENAME TO aclist;
ALTER TABLE IMPORTS."BLOCKS" RENAME TO blocks;
ALTER TABLE IMPORTS."DIST_AC" RENAME TO distac;
ALTER TABLE IMPORTS."DIST_LIST" RENAME TO distlist;
ALTER TABLE IMPORTS."NNN" RENAME TO nnn;
ALTER TABLE IMPORTS."PART_LIST" RENAME TO partlist;
ALTER TABLE IMPORTS."POLICE_STATION" RENAME TO policestation;
ALTER TABLE IMPORTS."PS_BUILDINGS" RENAME TO psbuildings;
ALTER TABLE IMPORTS."PS_DETAILS" RENAME TO psdetails;
ALTER TABLE IMPORTS."SECTION_LIST" RENAME TO sectionlist;
ALTER TABLE IMPORTS."SUB_DIVISIONS" RENAME TO subdivisions;
ALTER TABLE IMPORTS."VILLAGES" RENAME TO villages;
ALTER TABLE IMPORTS."POLICE_STATION" RENAME TO policestation;
ALTER TABLE IMPORTS."POST_OFFICES" RENAME TO postofices;

ALTER TABLE IMPORTS."STATE_EROLL_DATA" RENAME TO stateerolldata;




SELECT 'ALTER TABLE ' || TABLE_SCHEMA || '.' || TABLE_NAME || ' RENAME COLUMN ' || COLUMN_NAME || ' TO  ' || LOWER(REPLACE(COLUMN_NAME, '_', '')) || ' ;'  
FROM INFORMATION_SCHEMA.COLUMNS WHERE TABLE_SCHEMA ='imports'

