

SELECT * FROM IMPORTS.STATEEROLLDATA
WHERE 1 = 1
--AND "ASSEMBLY_CONSTITUENCY_NUMBER" = 14
--AND "GENDER"='FEMALE'
AND "AGE" BETWEEN 35 AND 45
--AND TRIM(UPPER("APPLICANT_FIRST_NAME")) LIKE '%SO%'
AND TRIM(UPPER("APPLICANT_LAST_NAME")) LIKE '%HEK%'

ORDER BY "GENDER", "AGE", "APPLICANT_FIRST_NAME"
LIMIT 100